PrinterCommunication/PrinterConnectionAndCommunication.cs
Ensures that "Port in Use" is avoided for this known disconnect behavior. Calls AbortConnectionAttempt to close down open resources before notifying the application of the disconnect through OnConnectionFailed. See https://www.pivotaltracker.com/story/show/85321330 for more details
=> Cleanup resources after USB disconnect while Connected - Fixes #85321330

App.config, MatterControl.csproj, packages.config
This reverts commit 0761a9b75c1908856cb392f6ab8e8f1c98f2cf37.
=> Revert OpenTK upgrade

PrinterControls/PrinterConnections/SetupStepMakeModelName.cs
Auto Name will now suggest names without numbers if there are no printers of the same make and model
Auto Name will now suggest the lowest possible number if there are printers of the same make and model
=> Updated Printer Auto Name

PrinterControls/PrinterConnections/BaseConnectionWidget.cs, PrinterControls/PrinterConnections/EditConnectionWidget.cs
- Remove local SerialPortButtonsList, expose base SerialPortButtonsList as protected
=> Resolve edit->printer->save regression

PartPreviewWindow/View3D/View3DCreateSelecitonData.cs, PartPreviewWindow/View3D/View3DWidget.cs, PartPreviewWindow/ViewControls3D.cs, PartPreviewWindow/ViewGcodeBasic.cs
- Show trackball controls during mouse overrides
=> Make ViewControls3D display actual mode during overrides

MatterControl.sln
=> Play nice with case-sensitive file systems

ConfigurationPage/LanguageSelector.cs, StaticData/Translations/fr/Translation.txt, StaticData/Translations/readme.txt
Added/updated French translation
=> Add French translation 

PrinterCommunication/PrinterConnectionAndCommunication.cs
- Scope dataLastRead to ReadFromPrinter to ensure one connection attempt does not effect another
=> Abort connection attempts when \n is missing and too many '?' are found

ApplicationView/MenuRow/ApplicationMenuRow.cs, ApplicationView/WidescreenPanel.cs, StaticData/Translations/Master.txt, VersionManagement/WebRequestHandler.cs
- Hook SendReqeuest to detect invalid credentials/expired sessions
- Prevent AddRightElement delegate from being invoked twice
- Make UpdateNotificationMark public for reuse in the Authentication plugin
=> Add SessionKey validation

Library/PrintLibraryWidget.cs, Library/Provider/LibraryProvider.cs, Library/Provider/LibraryProviderSelector.cs, VersionManagement/WebRequestHandler.cs
- Prevent the LibraryProviderSelector from creating new providers when it already has ones loaded, stored and referenced
- Add WebRequest2 type to support custom post/request values
=> Reduce library flickering

Library/LibraryRowItem.cs, Library/LibraryRowItemCollection.cs, Library/LibraryRowItemPart.cs, SlicerConfiguration/SlicerMapping/MappingClasses.cs
- Remove hard-coded place holder tokens
- Fix extruder number comments in exported gcode
=> Prevent interaction with library placeholder collections

BrailleBuilder/BrailleGrade2.cs, BrailleBuilder/BrailleGrade2Mapping.cs
Mappings of Grade 2 Contractions added dynamically
Added Capital Contraction (A -> ,a)
=> Added full list of Grade 2 contractions

Library/LibraryRowItemPart.cs
=> Guard against invalid file paths in "Add to Queue" operation

PrinterControls/TerminalWindow/TerminalWidget.cs
- Streamlines the user experience and only adds the keyboard overhead to users who need it
=> Prevent automatic focus of input field on Android Console view

PrinterControls/PrinterConnections/SetupStepMakeModelName.cs, SlicerConfiguration/SliceSettingsWidget.cs
- Fixes #104492002 - Linux bottleneck
=> Run DB save operations in a transaction

PrinterControls/PrinterConnections/EditConnectionWidget.cs
=> Add KeyboardContentOffset to reveal baud rate input field on Android

AboutPage/ContactForm.cs, BrailleBuilder/BrailleBuilderMainWindow.cs, ConfigurationPage/ApplicationSettings/ApplicationSettingsView.cs, EeProm/EePromMarlinWindow.cs, EeProm/EePromRepetierWindow.cs, PartPreviewWindow/PartPreviewMainWindow.cs, PartPreviewWindow/SaveAsWindow.cs, PrinterControls/PrinterConnections/EditConnectionWidget.cs, PrinterControls/TerminalWindow/TerminalWindow.cs, TextCreator/TextCreatorMainWindow.cs
- Remove keyboardHeight from constructor
- Latest agg
=> Revise Android softkeyboard support

ActionBar/PrintActionRow.cs
-  Ensure RootedObjectEventHandler events are pushed to UI thread  - Fixes #106067186
=> Invoke SetButtonStates on UI thread

MatterControlApplication.cs
=> Prevent image publish during camera preview

BrailleBuilder/BrailleBuilder.csproj, BrailleBuilder/BrailleGrade2.cs, BrailleBuilder/BrailleGrade2Mapping.cs, BrailleBuilder/View3DBrailleBuilder.cs
Filled in remaining incomplete translations
beforeWord/Prepositional Phrases implemented
Fixed show text tool tip to properly label text as above braille
=> Braille Contractions complete

BrailleBuilder/BrailleGrade2.cs, BrailleBuilder/BrailleGrade2Mapping.cs, BrailleBuilder/View3DBrailleBuilder.cs
- Numbers Translated
- Punctuation translated
- "Prepositional Phrases" implemented
Braille 2 show text now Shows original text
=> Braille2 Now passes Unit tests and ShowText shows original text

PrinterCommunication/PrinterConnectionAndCommunication.cs
- Fixes #108023844
- Revise whitespace
- Refactor to use optional BreakInDebugger parameter
=> Suppress error reporting and abort on COM AccessDenied errors

Library/LibraryRowItemPart.cs, Library/PrintLibraryWidget.cs, Library/Provider/LibraryProviderFileSystem.cs, Library/Provider/LibraryProviderHistory.cs, Library/Provider/LibraryProviderQueue.cs, Library/Provider/LibraryProviderSelector.cs, Library/Provider/LibraryProviderSqlite.cs
- Use Task.FromResult where needed
=> Remove async modifiers from non-async methods

Tests/MatterControl.AutomationTests/MatterControl.AutomationTests.csproj, Tests/MatterControl.AutomationTests/app.config, Tests/MatterControl.AutomationTests/packages.config, Tests/MatterControl.Tests/MatterControl.Tests.csproj
- Fix Nunit version
- Add app.config
- Update agg/matterslice
=> Fix 'processor architecture mismatch' warnings

Tests/TestRunner/MatterControl.nunit, Tests/TestRunner/MatterControlAutomation.nunit, Tests/TestRunner/TestRunner/NunitConsoleRunner.cs, Tests/TestRunner/TestRunner/Program.cs, Tests/TestRunner/TestRunner/TestRunner.csproj
- Remove automation tests from nunit project file
- Add automation project file
=> Extract console runner from program.cs

SlicerConfiguration/SlicePresetsWindow/SlicePresetDetailWidget.cs, SlicerConfiguration/SliceSettingsWidget.cs, StaticData/SliceSettings/Properties.json
- Revise settings iteration for clarity
- Update HelpText per support
=> Rename Simple to Basic

Utilities/WebUtilities/RequestManager.cs, VersionManagement/WebRequestHandler.cs
- Add timeouts to RequestManager request model
- Support timeouts in WebRequestBase<T> requests
=> Clear spinner on http request failures

PartPreviewWindow/View3D/View3DWidget.cs
- Fixes #111335412 - Part is deleted from Downloads after Edit>Save
- Fixes #111379492 - Data loss and confusing file duplication when editing STLs in FileSystemProviders folders
=> Revise View3DWidget save behavior for FileSystemProviders

AboutPage/AboutWindow.cs, AboutPage/HTMLParser/HtmlWidget.cs
- Remove buttonRowContainer blocking mouse input to html content
- Fixes #104208890 - Help>About>Clear Cache no longer works
=> Restore Clear Cache functionality

ApplicationView/MainApplicationWidget.cs, ApplicationView/MenuRow/MenuOptionFile.cs, ApplicationView/WidescreenPanel.cs, ControlElements/PopOutManager.cs, CustomWidgets/LibrarySelector/FolderBreadCrumbWidget.cs, MatterControlApplication.cs, PartPreviewWindow/PartPreviewContent.cs, PartPreviewWindow/ViewGcodeBasic.cs, StaticData/Translations/Master.txt
- Rename CloseAndRemoveAllChildren
=> Add support for closing MatterControl while printing

ConfigurationPage/ApplicationSettings/ApplicationSettingsView.cs
=> Change path to Master.txt file

CustomWidgets/DisableableWidget.cs, PrinterControls/ControlWidgets/MovementControls.cs, PrinterControls/ManualPrinterControls.cs
- Sync macroControls naming with siblings and Android
- Switch invalid ErrorEventArgs signature to EventArgs
=> ManualPrinterControls.cs micro-merge with Android

PrinterControls/PrinterConnections/PrinterChooser.cs, PrinterControls/PrinterConnections/SetupStepMakeModelName.cs
- Ensure list items use the ASCII file system values
- Use mapped Unicode manufacturer names where appropriate
=> Revise ManufacturerNameMapping DropList support

Queue/QueueDataWidget.cs, SlicerConfiguration/SlicingQueue.cs
- Ensure invalid extensions don't make it into the queue
- Ignore invalid extensions when slicing
=> Fix NotImplementedException during slicing

MatterControlApplication.cs, PrinterControls/PrinterConnections/PrinterSetupStatus.cs, Tests/MatterControl.Tests/MatterControl/Slicing/SliceLayersTests.cs
- Be more clear about when we return null
- Spelling
=> Revise naming to reflect behavior - LoadSettingsFromConfigFile

VersionManagement/VersionFileHandler.cs
- Consolidate three classes to expose four properties into one
=> Reduce VersionInfo to minimal complexity

PartPreviewWindow/View3D/View3DWidget.cs, SettingsManagement/ApplicationSettings.cs, StaticData/Translations/Master.txt, Tests/MatterControl.AutomationTests/PartPreviewTests.cs
- Restore file save behavior
- Perform test cleanup before running Downloads test
- Add .mcx to Library files filter
=> Fix failing automation tests in part preview

SlicerConfiguration/Settings/SettingsProfile.cs, SlicerConfiguration/SliceSettingsWidget.cs
=> Validate settings against properties.json rather than BaseLayer

PrinterCommunication/Io/WaitForTempStream.cs
This makes M190 act correctly. When given S, it continues if the temperature is at or above the target. When given R, it will wait for the temperature to cool down if it is above the target.
This solves an issue where prints would not finish on the Lulzbot Mini or the TAZ 6.
http://forums.matterhackers.com/topic/126/after-recent-update-lulzbot-mini-will-no-longer-finish-prints
=> Add R code for M190

SlicerConfiguration/Settings/SettingsProfile.cs, SlicerConfiguration/SliceSettingsWidget.cs
- Fixes #709
----
Seems like a working solution with some indirection happening around the SlicerConfigName, which hopefully is tolerable but could be reconsider if not
=> Machine specific ComPort settings

PrinterControls/ControlWidgets/MacroControls.cs, PrinterControls/EditMacrosWindow.cs, SlicerConfiguration/Settings/LayeredProfile.cs
- Make the Add->Save feature work for Macros
=> Fix Macro null reference errors

Tests/MatterControl.AutomationTests/CheckBoxInLibraryIsClickable.cs, Tests/MatterControl.AutomationTests/CreateLibraryFolder.cs, Tests/MatterControl.AutomationTests/ExportItemWindowTests.cs, Tests/MatterControl.AutomationTests/FileMenuTest.cs, Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs, Tests/MatterControl.AutomationTests/LibraryDownloadsTest.cs, Tests/MatterControl.AutomationTests/LocalLibraryTests.cs, Tests/MatterControl.AutomationTests/MatterControl.AutomationTests.csproj, Tests/MatterControl.AutomationTests/OptionsTabTests.cs, Tests/MatterControl.AutomationTests/PartPreviewTests.cs, Tests/MatterControl.AutomationTests/PrintQueueTests.cs, Tests/MatterControl.AutomationTests/SliceSetingsTests.cs, Tests/MatterControl.AutomationTests/SqLiteLibraryProvider.cs, Tests/MatterControl.Tests/MatterControl.Tests.csproj, Tests/MatterControl.Tests/MatterControl/LibraryProviderSqliteTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Change namespaces to MatterHackers.MatterControl.Tests.Automation
- Cleanup using statements
=> Move automation tests to "MatterControl.UI.Automation" category

ConfigurationPage/PrinterSettings/PrinterSettingsView.cs, DataStorage/Classic/ClassicSqlitePrinterProfiles.cs, SlicerConfiguration/Settings/ActiveSliceSettings.cs, SlicerConfiguration/SettingsControlSelectors.cs
- Invert Camera image
- Set first imported profile as active
- Import profiles from db if missing
- Edit presets button should do nothing on '- default -'
=> Fix icons and improve profile imports

ControlElements/ThemeFactory.cs, CustomWidgets/ThemeColorSelectorWidget.cs, DataStorage/Classic/ClassicSqlitePrinterProfiles.cs, SlicerConfiguration/Settings/ActiveSliceSettings.cs, SlicerConfiguration/Settings/LayeredProfile.cs
=> Experimental support for per printer themes

ActionBar/PrintStatusRow.cs, ActionBar/PrinterActionRow.cs, CustomWidgets/PopOutTextTab.cs
Made print level icon go to leveling settings
=> Made pop out tabs take automation correctly.

ActionBar/PrintStatusRow.cs
=> UI Label change

ActionBar/PrintActionRow.cs, ActionBar/PrintStatusRow.cs, ActionBar/PrinterActionRow.cs, ControlElements/AttentionGetter.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, SlicerConfiguration/SliceSettingsWidget.cs, StaticData/Translations/Master.txt
Common ui navigation functions
Improved highlight utility
Made Edit Fields have names that can be discovered
Refactoring
=> Made some help when connecting to a printer without a com port set

SlicerConfiguration/Settings/SettingsProfile.cs, SlicerConfiguration/SlicerMapping/EngineMappingSlic3r.cs
=> Remove invalid settings from slic3r config files

ControlElements/AttentionGetter.cs
Only one run navigation at a time
only allow one highlight per widget at a time.
=> Made sure Attention getter is done done

PrinterControls/PrinterConnections/PrinterChooser.cs, PrinterControls/PrinterConnections/SetupStepMakeModelName.cs, SettingsManagement/OemSettings.cs, Tests/MatterControl.Tests/MatterControl/PrinterChooserUnitTests.cs
=> Decouple make/model droplists

MatterControl.csproj, MatterControl.sln, PrinterControls/PrinterConnections/ShowAuthPanel.cs, SetupWizard/WizardWindow.cs
- Completed first pass at completing User is prompted to login in printer setup wizard if they are not signed in
- Invoke delegate and show login prompt based on whether or not they are currently signed in.
- Fixes #825
=> Add conditional user auth panel before ChangeToAddPrinter

PrinterControls/PrinterConnections/SetupStepMakeModelName.cs, SettingsManagement/OemSettings.cs, Tests/MatterControl.Tests/MatterControl/PrinterChooserUnitTests.cs
=> Pull make/model data from http endpoint

PrinterControls/PrinterConnections/SetupConnectionWidgetBase.cs, SetupWizard/SetupWizardConnect.cs, SetupWizard/SetupWizardTroubleshooting.cs, SetupWizard/SetupWizardWifi.cs, SetupWizard/WizardPanel.cs
- Issue #846
- Move ActivePrinter to SetupConnectionWigetBase
- Remove local theme variables
- Allow subclass to set widget factory defaults
=> Remove duplication in SetupConnectionWidgetBase

PrinterCommunication/PrinterConnectionAndCommunication.cs
Fixed consistency error where resend would fail to send \r\n at end of line
=> Fixed resend Consistency

Tests/MatterControl.Tests/MatterControl/ConfigIniTests.cs
=> Run validation tests on slice presets

ActionBar/PrintStatusRow.cs, ApplicationView/MainApplicationWidget.cs, ApplicationView/WidescreenPanel.cs, ControlElements/AttentionGetter.cs, SlicerConfiguration/Settings/ActiveSliceSettings.cs
Made touchscreen on desktop update the view correctly on printer change.
=> Took out the move to print leveling settings

ControlElements/AttentionGetter.cs, SetupWizard/WizardWindow.cs, StaticData/Translations/Master.txt
=> make sure we close editor on delete printer

DataStorage/Classic/ClassicSqlitePrinterProfiles.cs, SlicerConfiguration/Settings/ActiveSliceSettings.cs, SlicerConfiguration/Settings/LayeredProfile.cs, SlicerConfiguration/Settings/SettingsProfile.cs, SlicerConfiguration/SettingsControlSelectors.cs, SlicerConfiguration/SlicePresetsWindow/SlicePresetsWindow.cs
- Add migration for existing profiles
=> Convert preset layers from Dictionaries to Lists

AboutPage/ContactForm.cs, SetupWizard/EditPrinterSettingsPage.cs, SlicerConfiguration/SliceSettingsWidget.cs
Added BaudRate to printer edit wizard
=> Made all panels update when edited in any panel (printer wizard)

SlicerConfiguration/SliceSettingsDetailControl.cs
=> Preserve some user overrides during Reset to Defaults

MatterControl.csproj, SetupWizard/ImportSettingsPage.cs, SlicerConfiguration/Settings/ActiveSliceSettings.cs, SlicerConfiguration/Settings/SettingsProfile.cs, SlicerConfiguration/SliceSettingsDetailControl.cs
- Move ClearUserOverrides to SettingsProfile
=> Add ImportSettings page for new import behavior

SlicerConfiguration/SliceSettingsDetailControl.cs
=> Fix master.txt corruption due to \r\n in loc string

PrinterControls/PrinterConnections/ConnectionWizardPage.cs, PrinterControls/PrinterConnections/SetupStepBaudRate.cs, PrinterControls/PrinterConnections/SetupStepComPortManual.cs, PrinterControls/PrinterConnections/SetupStepMakeModelName.cs, SlicerConfiguration/Settings/ActiveSliceSettings.cs, SlicerConfiguration/Settings/SettingsProfile.cs
- Remove excess properties from PrinterInfo
- Remove call to Parent.Close from onPrinterStatusChanged
=> Remove ActivePrinter variable from ConnectionWizard

SlicerConfiguration/SettingsControlSelectors.cs
=> Assign active material with preset key rather than name

SetupWizard/ImportSettingsPage.cs, SetupWizard/WizardWindow.cs, SlicerConfiguration/Settings/ActiveSliceSettings.cs, SlicerConfiguration/Settings/SettingsProfile.cs, StaticData/Translations/Master.txt
Made a new success page for the input wizard
Made cancel file selection do the right thing
Update profile selector on add
Load from ini can handle a bad ini file now
=> Improving import wizard

ActionBar/PrinterSelector.cs, DataStorage/Classic/ClassicSqlitePrinterProfiles.cs, MatterControl.csproj, MatterControlApplication.cs, PrinterControls/PrinterConnections/SetupStepMakeModelName.cs, SetupWizard/ImportSettingsPage.cs, SlicerConfiguration/Settings/ActiveSliceSettings.cs, SlicerConfiguration/Settings/LayeredProfile.cs, SlicerConfiguration/Settings/ProfileManager.cs, SlicerConfiguration/Settings/SettingsProfile.cs, SlicerConfiguration/SettingsControlSelectors.cs, SlicerConfiguration/SlicePresetsWindow/SlicePresetsWindow.cs, SlicerConfiguration/SliceSettingsWidget.cs
- Use on disk profiles.json
- Support MarkedForDelete functionality
- Issue #930
=> Extract profile management to ProfileManager class

SlicerConfiguration/Settings/ProfileManager.cs
- Add code to save ProfileManager contents on Add Printer
- Revise and rerun printer profile generation tool
- Move CollectionChanged registration, don't run during deserialization
- CollectionChanged.Remove no longer valid as Deletes are deferred
- Fixes #982, #983
- Remove dead code
=> Fix missing printers and presets

PrinterControls/PrinterConnections/ShowAuthPanel.cs, StaticData/Translations/Master.txt
=> Improving setup experience.

SetupWizard/ImportSettingsPage.cs, SlicerConfiguration/Settings/ProfileMigrations.cs
Don't throw on cura file in release.
=> Don't try to load material and quality settings if there aren't any.

CustomWidgets/PartThumbnailWidget.cs
=> Change the too big to render message to Reduce Polygons to Render

DataStorage/Classic/ClassicSqlitePrinterProfiles.cs, SlicerConfiguration/Settings/LayeredProfile.cs, SlicerConfiguration/Settings/ProfileManager.cs, Tests/MatterControl.Tests/MatterControl/ConfigIniTests.cs
=> Removing settings base layer from being strode in users data

BrailleBuilder/View3DBrailleBuilder.cs, PartPreviewWindow/PlatingHelper.cs, PartPreviewWindow/View3D/SideBar/ScaleControls.cs, PartPreviewWindow/View3D/View3DCopyGroup.cs, PartPreviewWindow/View3D/View3DWidget.cs, SlicerConfiguration/SliceSettingsWidget.cs, TextCreator/View3DTextCreator.cs
scale control was in transition and this makes it usable. fixes #1005
made clearing an override send an update message.
=> Made the scale control work with single transforms

SlicerConfiguration/Settings/ProfileManager.cs, Tests/MatterControl.AutomationTests/RetrievePublicProfileTest.cs, VersionManagement/RetrievePublicProfileRequest.cs
=> Loading printer profile now follows local cache fallback when offline

PartPreviewWindow/ViewGcodeBasic.cs, SlicerConfiguration/SlicerMapping/EngineMapingBase.cs, StaticData/SliceSettings/Layouts.txt, StaticData/SliceSettings/Properties.json, StaticData/Translations/Master.txt
I also corrected the mass calculation to use a filament density specified in the settings, instead of the hardcoded value for PLA.
=> Added print cost estimate to Layer View

ActionBar/PrinterSelector.cs, ApplicationView/MainApplicationWidget.cs, SlicerConfiguration/Settings/ActiveSliceSettings.cs, SlicerConfiguration/Settings/ProfileManager.cs, StaticData/Translations/Master.txt
Don't allow login or logout while printing.
=> Don't allow change printer while printing.

SlicerConfiguration/Settings/SettingsProfile.cs, SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs, StaticData/Translations/Master.txt, Tests/MatterControl.Tests/MatterControl.Tests.csproj, Tests/MatterControl.Tests/MatterControl/ConfigIniTests.cs, Tests/MatterControl.Tests/MatterControl/PrinterConfigurationTests.cs, Tests/MatterControl.Tests/MatterControl/SettingsParseTests.cs
Refactored first_layer_extrusion_width into a fixed string
=> Wrote a new test for first_layer_extrusion_width being parsed correctly

ApplicationView/MainApplicationWidget.cs, MatterControl.csproj, Queue/OptionsMenu/QueueOptionsMenu.cs, SetupWizard/PrinterProfileHistoryPage.cs, SlicerConfiguration/SliceSettingsDetailControl.cs
Added retrieve printer profile history and revert to previous profile functionality
=> 	Added retrieve printer profile history and revert to previous profile functionality

DataStorage/Classic/ClassicSqlitePrinterProfiles.cs
=> Set imported ComPort to machine specific name

ControlElements/AttentionGetter.cs, SetupWizard/EditPrinterSettingsPage.cs, SetupWizard/WizardWindow.cs
- Remove unused GetSystemWindow helper function
- Remove used member, resolve compiler warning
- Rename runningAttentions variable
=> Move event registration and overrides into EditPrinterSettingsPage type

MatterControl.csproj, MatterControlApplication.cs, SetupWizard/PrinterProfileHistoryPage.cs, SetupWizard/SyncingPrintersPage.cs, StaticData/Translations/Master.txt
Prompt to log in now Properly launched if no user is logged in and sync only called if user is logged in
Removed comments from PrinterProfileHistoryPage that were meant to outline process
=> Created Wizard Page to Sync Profiles after log in.

ActionBar/PrintActionRow.cs, SetupWizard/SetupWizardTroubleshooting.cs
When the connect button is clicked and we don't find a usb port we run the
trouble shooting wizard and can find the board.
=> Added the ability to run the trouble shooting wizard if can't connect

ConfigurationPage/PrinterSettings/PrinterSettingsView.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, SlicerConfiguration/Settings/SettingsProfile.cs
=> Making sure we only select MatterSlice when it is the only engine.

SetupWizard/CopyGuestProfilesToUser.cs, SetupWizard/WizardWindow.cs, SlicerConfiguration/Settings/ActiveSliceSettings.cs, SlicerConfiguration/SliceSettingsDetailControl.cs, SlicerConfiguration/SliceSettingsWidget.cs, StaticData/Translations/Master.txt
Go to driver install rather than not
Make sure delete printer updates settings view
Printer History -> Settings History
Make Settings Options menu not too big
Border on Delete Printer button
=> Changed upload to sync

SlicerConfiguration/Settings/SettingsHelpers.cs, Tests/MatterControl.Tests/MatterControl/ConfigIniTests.cs
=> Created M109 test

PartPreviewWindow/ViewGcodeBasic.cs
Side note: Since we update the mass and cost when the settings change, shouldn't we update the filament length as well since it depends on the diameter?
=> Fixed estimated cost

ApplicationView/MainApplicationWidget.cs
*  Check to see if there is a specially named file on disk
*  If the file exists we skip the PrinterSetupWizard
* Then we connect to a printer, add a file to the queue, slice, then start printing
=> Added ability to start a print when MatterControl initially loads.

ApplicationView/MainApplicationWidget.cs, SettingsManagement/OemSettings.cs, SlicerConfiguration/Settings/ProfileManager.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, Tests/MatterControl.AutomationTests/RetrievePublicProfileTest.cs
=> Make LoadCacheable collector return instance of T rather than string

PrinterControls/PrinterConnections/ShowAuthPanel.cs, SetupWizard/CopyGuestProfilesToUser.cs, SetupWizard/ExportSettingsPage.cs, SetupWizard/ImportSettingsPage.cs, SetupWizard/LicenseAgreementPage.cs, SlicerConfiguration/SliceSettingsWidget.cs
Changed the signature of WMrappedTextWidget
=> Made the license agreement text do wrapping in a background thread.

ActionBar/PrintActionRow.cs, ActionBar/PrinterActionRow.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, SetupWizard/AndroidConnectDevicePage.cs
only user initiated connect attempts bring up the wizard
refactoring
=> Made auto connect not pop up the serial port helper

PrinterCommunication/Io/ResumePrintingStream.cs, PrinterControls/PrinterConnections/ShowAuthPanel.cs, SetupWizard/WizardPage.cs, Tests/MatterControl.AutomationTests/CheckBoxInLibraryIsClickable.cs, Tests/MatterControl.AutomationTests/CreateLibraryFolder.cs, Tests/MatterControl.AutomationTests/ExportItemWindowTests.cs, Tests/MatterControl.AutomationTests/FileMenuTest.cs, Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs, Tests/MatterControl.AutomationTests/LibraryDownloadsTest.cs, Tests/MatterControl.AutomationTests/LocalLibraryTests.cs, Tests/MatterControl.AutomationTests/OptionsTabTests.cs, Tests/MatterControl.AutomationTests/PartPreviewTests.cs, Tests/MatterControl.AutomationTests/PrintQueueTests.cs, Tests/MatterControl.AutomationTests/SliceSetingsTests.cs, Tests/MatterControl.AutomationTests/SqLiteLibraryProvider.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
Made automation tests call it.
=> Making a function to prep MatterControl prior to runing tests.

SlicerConfiguration/Settings/PrinterSettings.cs, SlicerConfiguration/Settings/ProfileMigrations.cs
- Disable old migrations
-  Issue MatterHackers/MCCentral#252
=> Skip migrations if DocumentVersion missing

DataStorage/Classic/ClassicSqlitePrinterProfiles.cs
- MatterHackers/MatterControl#1259
=> Ensure preset name/ID set during import

ApplicationView/MainApplicationWidget.cs, ConfigurationPage/ApplicationSettings/ApplicationSettingsView.cs, ConfigurationPage/PrintLeveling/LevelWizardBase.cs, Library/PrintLibraryWidget.cs, Tests/MatterControl.AutomationTests/LocalLibraryTests.cs, Tests/MatterControl.AutomationTests/PartPreviewTests.cs
New function ReloadLibraryUI
Called when updating purchased and shared folder
=> Making less calls to reload all

SetupWizard/ImportSettingsPage.cs, SlicerConfiguration/Settings/PrinterSettingsLayer.cs, SlicerConfiguration/Settings/ProfileMigrations.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SettingsControlSelectors.cs, SlicerConfiguration/SlicePresetsWindow/SlicePresetsWindow.cs, SlicerConfiguration/SliceSettingsWidget.cs, Tests/MatterControl.Tests/MatterControl/OemProfileTests.cs
Made the drop list name update interactively.
=> Made settings names save when empty

PrinterCommunication/PrinterConnectionAndCommunication.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SliceSettingsWidget.cs, SlicerConfiguration/SlicerMapping/EngineMapingBase.cs, SlicerConfiguration/SlicerMapping/MappingClasses.cs, StaticData/SliceSettings/Layouts.txt, StaticData/SliceSettings/Properties.json, StaticData/Translations/Master.txt, Tests/MatterControl.Tests/MatterControl/SettingsParseTests.cs
Made it able to be turned on and off
=> Defaulted resume failed print to off

StaticData/SliceSettings/Properties.json
=> spelling error

PartPreviewWindow/ViewGcodeBasic.cs
just adding a ³ instead of the 3 in cm3.
=> fixing cm3 superscript in LAYER VIEW

MatterControlApplication.cs, SlicerConfiguration/Settings/ProfileManager.cs
MatterHackers/MatterControl#1207
=> On first run we effectively sign out user so that they will be forced to sign in and import printers

App.config
- Issue MatterHackers/MCCentral#307
=> Add assembly binding redirect

Library/PrintLibraryWidget.cs
- Reuse Reload function in constructor initialization
- Issue MatterHackers/MatterControl#1298
=> Wire up LibraryItemsSelected event to Reloaded items

ActionBar/PrinterSelector.cs, SetupWizard/CopyGuestProfilesToUser.cs, SlicerConfiguration/SliceSettingsWidget.cs
- Fixes list not refreshing after import
- Issue MatterHackers/MCCentral#288
=> Rebuild printers droplist on ProfilesListChanged event

ApplicationView/MainApplicationWidget.cs
- Issue MatterHackers/MCCentral#318
=> Conditionally execute UserChanged

ApplicationView/MainApplicationWidget.cs, SettingsManagement/OemSettings.cs, SetupWizard/SyncingPrintersPage.cs, StaticData/Translations/Master.txt
- Both private and public profiles report
- public profiles are not called to report but can be later
Issue : MatterHackers/MCCentral#301
=> Sync printer page updates progress of syncing operations

SlicerConfiguration/SettingsControlSelectors.cs
- Use common string for default menu text
- Localize default menu text
- Issue MatterHackers/MatterControl#1295
=> Disable Edit Preset button on default item

ApplicationView/MainApplicationWidget.cs, SettingsManagement/ApplicationSettings.cs, StaticData/OEMSettings/Settings.json
Made the ability to get the application instance count
=> Each unique version of MC requires a separate login

ApplicationView/MainApplicationWidget.cs, PrinterControls/PrinterConnections/ShowAuthPanel.cs, SetupWizard/AndroidSetupOptionsPage.cs, SetupWizard/CopyGuestProfilesToUser.cs, StaticData/Translations/Master.txt, Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs, Tests/MatterControl.AutomationTests/PrintQueueTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs, Utilities/WebUtilities/RequestManager.cs
issue MatterHackers/MCCentral#322
Change all 'login' 'sign in' to be consistent -> 'Sign in' and 'Sign Out'
=> Changed Login -> Sign in & Logout -> Sign Out

ApplicationView/MainApplicationWidget.cs, PrinterControls/PrinterConnections/ShowAuthPanel.cs, StaticData/Translations/Master.txt
issue MatterHackers/MCCentral#331
Add option to ignore sign in reminder during MatterControl startup
=> added  "Don't  ask me again" to ShowAuthPanel.

AboutPage/AboutWidget.cs, ApplicationView/MainApplicationWidget.cs, CustomWidgets/ThemeColorSelectorWidget.cs, DataStorage/Classic/ClassicSqlitePrinterProfiles.cs, MatterControlApplication.cs, SettingsManagement/UserSettings.cs, SlicerConfiguration/Settings/ActiveSliceSettings.cs, SlicerConfiguration/Settings/PrinterSettings.cs, SlicerConfiguration/Settings/ProfileManager.cs, SlicerConfiguration/Settings/ProfileMigrations.cs, SlicerConfiguration/Settings/SettingsHelpers.cs
Moved setting to UserrSettingsKey
MatterHackers/MCCentral#337
Change default theme to light blue
=> Made the default theme blue - light.

SlicerConfiguration/Settings/ActiveSliceSettings.cs, SlicerConfiguration/SliceSettingsDetailControl.cs
MatterHackers/MCCentral#330
Settings History menu should be disabled when not signed in
=> Made the settings history be disabled when not signed in.

ActionBar/PrinterActionRow.cs
MatterHackers/MCCentral#335
Disable connect button when no printer selected
=> Disable connect button when no printer selected

SlicerConfiguration/Settings/PrinterSettings.cs, SlicerConfiguration/Settings/ProfileManager.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SlicePresetsWindow/SlicePresetsWindow.cs
- Issue MatterHackers/MCCentral#302
=> Use short printer ID for local features and DeviceToken for remote

Library/Provider/LibraryProviderSqlite.cs, PrinterControls/PrinterConnections/SetupStepMakeModelName.cs, SlicerConfiguration/Settings/ProfileManager.cs, StaticData/Profiles/Airwolf 3D/HD.printer, StaticData/SliceSettings/Properties.json, StaticData/Translations/Master.txt
The item that will be added is the first item in the OEMSettings -> settings.json -> "PreloadLibraryFiles" list.
MatterHackers/MCCentral#334
On initial load prepopulate queue with item under all circumstances
=> Always add at least one item to the queue.

ApplicationView/MainApplicationWidget.cs, SettingsManagement/OemSettings.cs
- Fixed a bug in downloading profiles from web would write "null" to file if it failed to get a proper file
=> Loadcacheable properly loads profiles from static data

MatterControlApplication.cs
MatterHackers/MCCentral#333
Increase size of application window on initial load
=> MatterControl now defaults to larger window size

SlicerConfiguration/Settings/ProfileManager.cs
- Issue MatterHackers/MatterControl#1346
=> Add to ProfileManager before invoking methods that call .Save()

ApplicationView/MainApplicationWidget.cs, SettingsManagement/ApplicationSettings.cs, SlicerConfiguration/Settings/ProfileManager.cs, StaticData/Profiles/oemprofiles.json
- Extract existing file delete to resusable function - ClearCachedCredentials
- Reuse ClearCachedCredentials in SetClientToken
- MatterHackers/MCCentral#321
=> Clear cached credentials after acquiring new ClientToken

SetupWizard/PrinterProfileHistoryPage.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SliceSettingsDetailControl.cs
=> Make settings history consistent across references

SlicerConfiguration/Settings/SettingsHelpers.cs
Added fire and forget for task
Added WaitUntil function on Automation Runner
Added some documentation
=> Fixed the key to delete profiles on

ApplicationView/MainApplicationWidget.cs, SlicerConfiguration/Settings/ProfileManager.cs
Make less possible threading issues on ProfileManager
=> Make sure we dons't call user changed until we are done loading.

PrinterCommunication/Io/GCodeStream.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs, StaticData/Profiles/Lulzbot/Mini.printer, StaticData/Profiles/OpenBeam/Kossel Pro.printer, StaticData/Profiles/SeeMeCNC/Eris.printer, StaticData/Profiles/SeeMeCNC/Orion.printer, StaticData/Profiles/SeeMeCNC/Rostock MAX.printer, StaticData/SliceSettings/Layouts.txt, Tests/MatterControl.AutomationTests/LibraryDownloadsTest.cs, Tests/MatterControl.AutomationTests/MatterControl.AutomationTests.csproj, Tests/MatterControl.AutomationTests/PrinterDropDownTests.cs, Tests/MatterControl.Tests/MatterControl/GCodeStreamTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
=> Added the ability to emit 'G0' for movement

Tests/MatterControl.AutomationTests/PrinterDropDownTests.cs
Now we check the printer dropdown list to make sure it gets updated with the name change.
=> Made improvements to printer name change test

CustomWidgets/ExportPrintItemWindow.cs
MatterHackers/MatterControl#1384
Use gcode stream processors to do gcode export
=> Use gcode streams to export gcode

SlicerConfiguration/Settings/PrinterSettings.cs, SlicerConfiguration/Settings/SettingsHelpers.cs
- Now compares last known server thumbprint to latest content thumbprint
- Fixes need to continually reset flag based on save conditions
- Will be accurate as long as ServerSHA1 is updated any time we pull updates
=> Revise IsDirty property - perform actual thumbprint comparison

ActionBar/PrinterActionRow.cs, PrinterEmulatorConfig.json, SlicerConfiguration/SliceSettingsWidget.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
Working on start print from sync test
=> Added utility function for starting printer emulator

Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Ensures that console window does not catch automation input
=> Startup com0com window in a minimized state

ActionBar/PrinterSelector.cs
MatterHackers/MatterControl#1391
=> Bug Fix: Printer selection menu gets stuck on "Add New Printer"

ApplicationView/MainApplicationWidget.cs, SlicerConfiguration/Settings/SettingsHelpers.cs
- Added Additional guard to saving profile
=> Remove Run on Idle due too regression

Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
MatterHackers/MCCentral#443
Automation tests fail to sign out users due to new 'user' dropdown
=> Created new sign out function of automation tests

MatterControlApplication.cs, PrinterEmulator.py, Tests/MatterControl.AutomationTests/SliceSetingsTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
Made LaunchAndConnectToPrinterEmulator
Working on pause on layer test
Updated version to 1.6
=> Made the emulator parse commands better (temps)

DataStorage/Datastore.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
=> Convert additional automation tests to NUnit3 compat

Tests/MatterControl.AutomationTests/PrintQueueTests.cs
- Expose test false positives, failing tests need fixed
=> Change assignment  statements to conditionals

ActionBar/PrintActionRow.cs, PartPreviewWindow/ViewGcodeBasic.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs, Tests/MatterControl.AutomationTests/PrintQueueTests.cs, Tests/MatterControl.AutomationTests/PrinterDropDownTests.cs, Tests/MatterControl.AutomationTests/SliceSetingsTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs, Tests/MatterControl.Tests/MatterControl/ReleaseBuildTests.cs
Test that MatterControl vanilla actually stars up
Finished the resume print test
Set backup to 0
Created a SwitchToAdvancedSettings function
=> Working on Queue done button working test (+2 squashed commit)

Tests/MatterControl.AutomationTests/PrintQueueTests.cs
=> Fixed a test

DataStorage/Classic/ClassicSqlitePrinterProfiles.cs, SlicerConfiguration/Settings/PrinterSettings.cs, SlicerConfiguration/Settings/ProfileMigrations.cs, SlicerConfiguration/Settings/SettingsHelpers.cs
- Create and use SettingsKey for print_leveling_data
- Issue MatterHackers/MCCentral#472
=> Clear print_leveling_data on 'Reset To Defaults'

Tests/MatterControl.AutomationTests/PrinterDropDownTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Document AddTestResult calls with descriptions
- Issue MatterHackers/MCCentral#478
=> Fix PrinterNameStaysChanged test

ApplicationView/MainApplicationWidget.cs, SetupWizard/CopyGuestProfilesToUser.cs, StaticData/Translations/Master.txt
MatterHackers/MCCentral#489
Inconsistent action description
=> Changing to "Migrate Printers" description

EeProm/EePromMarlinSettings.cs, EeProm/EePromMarlinWindow.cs, EeProm/EePromRepetierWindow.cs
=> Attempting to fix keyboard pop up in android

EeProm/EePromMarlinWindow.cs, MatterControlApplication.cs, PrinterControls/TerminalWindow/TerminalWidget.cs
Make sure we don't close the Database until after we Call OnApplicationClosed
MatterHackers/MCCentral#498
Android: Cannot put away keyboard on EEPROM screen android
Fix terminal widget closing on android.
=> Changed the way eeprom window lays out

PrinterControls/PrinterConnections/PrinterChooser.cs, PrinterControls/PrinterConnections/SetupStepMakeModelName.cs
- Turn on TabStop for make/model DropLists
- Add focus indicator for make/model DropLists
=> Improve keyboard support for make/model selectors

DataStorage/Datastore.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Improve layout in NUnit console output
- Remove stacktrace workarounds for NUnit2
=> Revise test output formatting

ApplicationView/TouchscreenTabView.cs, PrinterControls/XYZJogControls.cs
MatterHackers/MatterControl#1369
=> Fix: Scroll bar disappears from Controls page in touchscreen mode

ActionBar/PrintStatusRow.cs, ActionBar/PrinterConnectAndSelectControl.cs
MatterHackers/MCCentral#511
UI Tweaks
=> Fixing string issues

SlicerConfiguration/Settings/SettingsHelpers.cs
- Ensures the popup SystemWindow in TouchScreen mode gets refreshed
- Issue MatterHackers/MCCentral#358
=> Fire ProfilesListChanged after SetMarkedForDelete

Tests/MatterControl.AutomationTests/MatterControl.AutomationTests.csproj, Tests/MatterControl.AutomationTests/packages.config, Tests/MatterControl.Tests/MatterControl.Tests.csproj, Tests/MatterControl.Tests/packages.config
- Issue MatterHackers/MCCentral#525
=> Upgrade to latest NUnit.ApplicationDomain package

SlicerConfiguration/Settings/ProfileManager.cs, SlicerConfiguration/Settings/SettingsHelpers.cs
- Issue MatterHackers/MCCentral#499
=> Proactively invoke Sync process on printer changed events

Tests/MatterControl.AutomationTests/LibraryDownloadsTest.cs
- Possible fix for Automation Tests 'file access' error
=> Attempt to delete Downloads subdirectory, suppress error on fail

Tests/MatterControl.AutomationTests/SliceSetingsTests.cs
- Fixes failing automation test
=> Adjust ClearingCheckBoxClearsUserOverride expected pass count

PrinterCommunication/PrinterConnectionAndCommunication.cs, SetupWizard/ImportSettingsPage.cs, SlicerConfiguration/Settings/PrinterSettings.cs, Tests/MatterControl.Tests/MatterControl.Tests.csproj, Tests/MatterControl.Tests/MatterControl/ImportSettingsTests.cs
Moved merge into PrinterSettings
With test
=> Import Settings now working

BrailleBuilder/View3DBrailleBuilder.cs, ControlElements/TextImageButtonFactory.cs, PartPreviewWindow/View3D/SideBar/MirrorControls.cs, PartPreviewWindow/View3D/SideBar/ScaleControls.cs, PartPreviewWindow/View3D/View3DWidget.cs, PartPreviewWindow/ViewGcodeBasic.cs, TextCreator/View3DTextCreator.cs
MatterHackers/MCCentral#538
Lost down arrow for edit options on 3D view
=> Fixed down arrows on edit model page

SettingsManagement/ApplicationSettings.cs, SlicerConfiguration/Settings/ProfileManager.cs, Utilities/AuthenticationData.cs
- Fixes MatterHackers/MCCentral#548
=> Load session values during construction, remove LoadFirstInstance

ActionBar/TemperatureWidgetBed.cs
renaming Slice Settings to SETTINGS.
=> UI text change

PartPreviewWindow/View3D/SideBar/ScaleControls.cs, StaticData/Profiles/Me3D/Me2.printer, StaticData/Translations/Master.txt, Tests/MatterControl.AutomationTests/PrintQueueTests.cs
MatterHackers/MCCentral#580
Scale -> Ration -> Reset(1) no longer valid
=> Don't apply the scale directly

SlicerConfiguration/Settings/ProfileManager.cs
- Issue MatterHackers/MCCentral#610
=> Prevent invoke on SyncPrinterProfiles if null

Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs, Tests/MatterControl.AutomationTests/SliceSetingsTests.cs
- No guarantee that all test method code will run
- Issue MatterHackers/MatterControl#1501
- Issue MatterHackers/MCCentral#614
=> Ensure spawned process is killed along all codepaths

ApplicationView/MainApplicationWidget.cs, CustomWidgets/ThemeColorSelectorWidget.cs, SlicerConfiguration/Settings/ActiveSliceSettings.cs
- The color is also set as the printer's active theme
=> Creating a new printer maintains the current color

SlicerConfiguration/Settings/ActiveSliceSettings.cs, SlicerConfiguration/Settings/ProfileManager.cs
Write the current color into printers on creation
=> Fixed a bug with wipe towers

Tests/MatterControl.AutomationTests/CheckBoxInLibraryIsClickable.cs, Tests/MatterControl.AutomationTests/CreateLibraryFolder.cs, Tests/MatterControl.AutomationTests/ExportItemWindowTests.cs, Tests/MatterControl.AutomationTests/FileMenuTest.cs, Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs, Tests/MatterControl.AutomationTests/LibraryDownloadsTest.cs, Tests/MatterControl.AutomationTests/LocalLibraryTests.cs, Tests/MatterControl.AutomationTests/OptionsTabTests.cs, Tests/MatterControl.AutomationTests/PartPreviewTests.cs, Tests/MatterControl.AutomationTests/PrintQueueTests.cs, Tests/MatterControl.AutomationTests/PrinterDropDownTests.cs, Tests/MatterControl.AutomationTests/SliceSetingsTests.cs, Tests/MatterControl.AutomationTests/SqLiteLibraryProvider.cs, Tests/MatterControl.AutomationTests/app.config, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs, Tests/MatterControl.Tests/MatterControl/ReleaseBuildTests.cs, Tests/MatterControl.Tests/app.config
- Remove AutomationRunner construction from test bodies
- Pass AutomationRunner into test method
=> Consolidate AutomationTesterHarness into AutomationRunner

MatterControlApplication.cs
=> Removed test code from 1.6

CustomWidgets/PartThumbnailWidget.cs, PrinterControls/PrinterConnections/SetupStepComPortTwo.cs, StaticData/Translations/Master.txt
=> Put a try catch around the load.

ApplicationView/MainApplicationWidget.cs, SetupWizard/AndroidSetupOptionsPage.cs
fixes MatterHackers/MCCentral#515
On android login status not updating after login/logout
=> Created new ReloadAllRequested event

SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs, SlicerConfiguration/SlicerMapping/EngineMappingSlic3r.cs, StaticData/SliceSettings/Layouts.txt, StaticData/SliceSettings/Properties.json, StaticData/Translations/Master.txt
Fixes a possible regression in slicing
=> Put in the ability to turn off Merge Overlapping Lines

SettingsManagement/OemSettings.cs
- Issue MatterHackers/MCCentral#689
=> Load OemProfiles from cache or fall back to StaticData if missing

PartPreviewWindow/ViewControls2D.cs, PartPreviewWindow/ViewControls3D.cs
Fixes MatterHackers/MCCentral#690
Fix home icon width on touch
=> Fixed home icon being the wronge size on touch.

ConfigurationPage/ApplicationSettings/ApplicationSettingsView.cs
=> Touch, Switching to display advanced mode not reloading screen

PrinterControls/PrinterConnections/ShowAuthPanel.cs
- Issue MatterHackers/MCCentral#683
=> Revise SystemWindow Close/Open calls to fix out of order SysWindow stack

Tests/MatterControl.AutomationTests/LocalLibraryTests.cs
- Add Assert messages
- Migrate comment details to message arg to assist in troubleshooting
- Eliminate superfluous variables
- Issue MatterHackers/MCCentral#716
=> Revise LibraryItemThumbnailClickedOpensPartPreview

Tests/MatterControl.AutomationTests/LocalLibraryTests.cs
- Add Assert messages
- Migrate varname details to message arg to assist in troubleshooting
- Eliminate superfluous variables
- Issue MatterHackers/MCCentral#717
=> Revise RemoveButtonClickedRemovesMultipleItems

Tests/MatterControl.AutomationTests/PartPreviewTests.cs, Tests/MatterControl.AutomationTests/PrintQueueTests.cs
- Rename test
- Wait to enter edit mode
- Use Assert.AreEqual for clarity
- Add Assert message for troubleshooting
- Wait for expected condition rather than fixed duration
- Use .Count instead of .Count()
- Issue MatterHackers/MCCentral#720
=> Revise UndoRedoDelete

Tests/MatterControl.AutomationTests/PrintQueueTests.cs
- Rename test
- Use Assert.AreEqual for clarity
- Add Assert messages for troubleshooting
- Wait for expected condition rather than fixed duration
- Attempt file cleanup inside of a try/catch and ignore failures
- Issue MatterHackers/MCCentral#721
=> Revise ExportToZipMenuItemClicked

Queue/QueueDataWidget.cs, Tests/MatterControl.AutomationTests/PrintQueueTests.cs
- Rename test to reflect actual behavior
- Add Assert messages for troubleshooting
- Add fixed wait times for menu clicks
- Issue MatterHackers/MCCentral#723
=> Revise SendMenuItemClickedNoSignIn

Tests/MatterControl.AutomationTests/PrintQueueTests.cs
- Add Assert messages for troubleshooting
- Wait for expected conditions
=> Revise CopyButtonMakesACopyOfPartInTheQueue

SlicerConfiguration/Settings/ProfileManager.cs
- Issue MatterHackers/MCCentral#729
=> Restore environment specific Profile directories

Tests/MatterControl.AutomationTests/PrintQueueTests.cs
=> Revise failing test - RemoveButtonRemovesSingleItem

Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Add WaitForReload function
- Remove invalid WaitFor("Connection Wizard...") -2 seconds per call
- Remove fixed 2 second wait, waitfor known condition
=> Remove fixed wait values, wait for known conditions

CustomWidgets/LibrarySelector/LibrarySelectorRowItem.cs, Library/LibraryRowItem.cs, Library/LibraryRowItemPart.cs, Queue/QueueRowItem.cs
Make sure we are using the correct events
Fixes: MatterHackers/MCCentral#734
Hover controls that appear on focus failing to lose focus and disappear on Android
=> Fixed library hover effect on android

Queue/QueueDataView.cs
- Issue MatterHackers/MCCentral#754
=> Workaround for Library selection crash

SetupWizard/AndroidSetupOptionsPage.cs
fixes: MatterHackers/MCCentral#757
Signed in user is missing printers, no indication that sync isn't working
=> Show sign in status message on android

Library/Provider/LibraryProviderSelector.cs, SetupWizard/AndroidSetupOptionsPage.cs
- Issue MatterHackers/MCCentral#780
Crash during startup when acquiring a client token and firing CloudSyncStatusChanged
=> Prevent invoke on null references

SetupWizard/LicenseAgreementPage.cs
- Issue MatterHackers/MCCentral#783
Android -> EULA -> Cancel should not close the systemwindow, should exit
=> Close application on EULA cancel

SlicerConfiguration/Settings/SettingsHelpers.cs
- Workaround for server side requirements
- Issue MatterHackers/MCCentral#806
Offline printers (never synced) marked for delete are never removed
=> Force Make/Model to Other/Other if null or empty

BrailleBuilder/BrailleBuilder.csproj, BrailleBuilder/BrailleGrade2.cs, BrailleBuilder/BrailleGrade2Mapping.cs, BrailleBuilder/packages.config, Tests/MatterControl.Tests/MatterControl.Tests.csproj, Tests/MatterControl.Tests/MatterControl/BrailleGrade2Tests.cs
- Issue MatterHackers/MCCentral#814
=> Remove nunit from production code

ApplicationView/MainApplicationWidget.cs, ApplicationView/MenuRow/MenuOptionFile.cs, MatterControlApplication.cs, SetupWizard/AndroidSetupOptionsPage.cs
MatterHackers/MCCentral#817
Redeem Purchase/Share code are non functional
=> fixed the redeem share code

PrinterCommunication/PrinterConnectionAndCommunication.cs
Don't merge this until we know it won't break anything.
I tested with Marlin on the TAZ and it doesn't cause any problems. Need to try it with Repetier.
=> Fixed sending/receiving double lines with Smoothie

PrinterCommunication/PrinterConnectionAndCommunication.cs, SetupWizard/EditPrinterSettingsPage.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SliceSettingsOrganizer.cs, SlicerConfiguration/SliceSettingsWidget.cs, SlicerConfiguration/SlicerMapping/EngineMapingBase.cs, StaticData/SliceSettings/Layouts.txt, StaticData/SliceSettings/Properties.json, StaticData/Translations/Master.txt
- Added Networked printing support
- Sailfish printing is now a configurable option
- Updated settingsOnChange to support check boxes
- Updated settingsOnChange to support changing to non-current value values
=> Networked printing

ApplicationView/MainApplicationWidget.cs, SetupWizard/CopyGuestProfilesToUser.cs, SlicerConfiguration/Settings/ProfileManager.cs, Tests/MatterControl.AutomationTests/PrintQueueTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Issue  MatterHackers/MatterControl#1664
=> Ensure 'Import Printers' window appears after authentication 

MatterControlApplication.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
Made a new argument to do thumbnails as orthographic
Significantly speeds up tests
=> Make it possible to pass command line arguments in test.

Tests/MatterControl.AutomationTests/ExportItemWindowTests.cs, Tests/MatterControl.AutomationTests/OptionsTabTests.cs
=> Fix ExportItemsFromDownloads.ExportAsGcode

ActionBar/PrintActionRow.cs, ApplicationView/FirstPanelTabView.cs, ApplicationView/TouchscreenTabView.cs, Library/Provider/LibraryProviderQueue.cs, Queue/QueueData.cs, Queue/QueueDataView.cs, Queue/QueueDataWidget.cs, Queue/QueueRowItem.cs, StaticData/Translations/Master.txt, Tests/MatterControl.AutomationTests/FileMenuTest.cs, Tests/MatterControl.AutomationTests/LocalLibraryTests.cs, Tests/MatterControl.AutomationTests/PrintQueueTests.cs
Working to fix
MatterHackers/MCCentral#896
Looking int hockeyapp crash set_SelectedPrintItem
=> Refactoring select queue items

Queue/QueueData.cs, Queue/QueueDataView.cs, Queue/QueueDataWidget.cs, StaticData/Translations/Master.txt, Tests/MatterControl.AutomationTests/PartPreviewTests.cs
If single item selected add to array
Make sure we update selection visibility when going in and out of editor
Fixed some tests
=> Make sure the queue is passing all unit tests

Tests/MatterControl.AutomationTests/LocalLibraryTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Issue MatterHackers/MCCentral#916
New Test: Clicking 'Print' on library item
=> Add PrintLibraryItem test, suppress Process.Kill exceptions

PartPreviewWindow/BaseClasses/PartPreview3DWidget.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
Make sure we don't ref a null mesh on rebuild bed
=> Fixed merge error in test

ActionBar/ActionBarPlus.cs, ActionBar/PrintActionRow.cs, ActionBar/PrintStatusRow.cs, ActionBar/PrinterConnectAndSelectControl.cs, ActionBar/TemperatureWidgetBase.cs, ApplicationView/MenuRow/MenuOptionAction.cs, ApplicationView/TouchscreenTabView.cs, CustomWidgets/ExportPrintItemWindow.cs, CustomWidgets/PartThumbnailWidget.cs, CustomWidgets/PrintProgressBarWidget.cs, History/PrintHistoryListItem.cs, PartPreviewWindow/BaseClasses/PartPreview3DWidget.cs, PartPreviewWindow/ViewGcodeBasic.cs, Queue/QueueDataWidget.cs, Queue/QueueRowItem.cs, SlicerConfiguration/SliceSettingsWidget.cs
same for on active printer changed
=> Working to reduce theme changed calls as they will reload all after.

ActionBar/PrinterSelector.cs, ApplicationView/MainApplicationWidget.cs, CustomWidgets/AltGroupBox.cs, PrinterControls/PrinterConnections/SetupStepComPortManual.cs, PrinterControls/PrinterConnections/SetupStepComPortOne.cs, PrinterControls/PrinterConnections/SetupStepComPortTwo.cs, PrinterControls/PrinterConnections/SetupStepMakeModelName.cs, PrinterControls/PrinterConnections/ShowAuthPanel.cs, SetupWizard/AndroidConnectDevicePage.cs, SetupWizard/AndroidSetupOptionsPage.cs, SetupWizard/SetupWizardTroubleshooting.cs, SetupWizard/WizardWindow.cs, SlicerConfiguration/Settings/ActiveSliceSettings.cs, StaticData/Translations/Master.txt
Made the android printer select window fix its colors on change
=> Get the starting color set correctly

PrinterCommunication/PrinterConnectionAndCommunication.cs, SetupWizard/EditPrinterSettingsPage.cs, StaticData/SliceSettings/Layouts.txt, StaticData/SliceSettings/Properties.json, StaticData/Translations/Master.txt
Took out the automatic changes to other settings
=> Refactored network printing settings to match the other printer settings

Tests/MatterControl.AutomationTests/PrintQueueTests.cs
This is to test a regression that was fixed today.
=> Wrote a test to validate that we remove the last queue item correctly

SlicerConfiguration/Settings/PrinterSettings.cs, SlicerConfiguration/Settings/ProfileMigrations.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SliceSettingsOrganizer.cs, StaticData/Profiles/Airwolf 3D/Axiom.printer, StaticData/Profiles/BCN/Sigma.printer, StaticData/Profiles/IRA3D/Poetry Infinity_25.printer, StaticData/Profiles/IRA3D/Poetry Infinity_40.printer, StaticData/Profiles/IRA3D/Poetry Infinity_80.printer, StaticData/Profiles/Lulzbot/TAZ 6 Software Leveling.printer, StaticData/Profiles/PrintSpace/Altair_25.printer, StaticData/Profiles/PrintSpace/Altair_40.printer, StaticData/Profiles/Revolution 3D Printers/INF3D-AF1-DE.printer, StaticData/Profiles/Revolution 3D Printers/INF3D-AF1-SE.printer, StaticData/Profiles/SeeMeCNC/Eris.printer, StaticData/Profiles/SeeMeCNC/Orion.printer, StaticData/Profiles/SeeMeCNC/Rostock MAX v3.printer, Tests/MatterControl.Tests/MatterControl/OemProfileTests.cs
- Issue MatterHackers/MCCentral#976
- Issue MatterHackers/MCCentral#985
- Issue MatterHackers/MCCentral#986
=> Add LayerGCodeHasExpectedValue test

PrinterCommunication/Io/PrintRecoveryStream.cs
Fixes MatterHackers/MCCentral#1031
Not handling bed heating correctly in print recovery
=> Include bed heating to recover consideration

AboutPage/HTMLParser/HtmlWidget.cs, ApplicationView/MainApplicationWidget.cs
- Long-term this will get moved into the network stack
=> Move DownloadToImageAsync to ApplicationController

CustomWidgets/ExportPrintItemWindow.cs, CustomWidgets/PluginChooserWindow.cs, PrinterControls/EditMacrosWindow.cs, PrinterControls/EditManualMovementSpeedsWindow.cs, PrinterControls/EditTemperaturePresetsWindow.cs, PrinterControls/PrinterConnections/ConnectionWizardPage.cs, SetupWizard/LicenseAgreementPage.cs, SlicerConfiguration/SliceSettingsWidget.cs
- Use .Localize() extension function
=> Add missing localizations

PrinterCommunication/PrinterConnectionAndCommunication.cs, PrinterEmulator.py, Tests/MatterControl.AutomationTests/MatterControl.AutomationTests.csproj, Tests/MatterControl.AutomationTests/PrintingTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
Fixed the test to pass
Made emulator turn off bed temp correctly.
=> Created a new printer turns of temps test

PrinterCommunication/Io/PrinterMove.cs, PrinterCommunication/Io/RelativeToAbsoluteStream.cs
Fixes:
MatterHackers/MCCentral#1041
Customer reports printing .GCode file exported from Simplify3D causes printer to extrude wildly
=> Added support for M83 and M82 extruder relative / absolute positioning

PrinterCommunication/Io/BabyStepsStream.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, PrinterControls/ControlWidgets/MovementControls.cs, PrinterControls/XYZJogControls.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs, StaticData/SliceSettings/Layouts.txt, StaticData/SliceSettings/Properties.json, StaticData/Translations/Master.txt
Fixes:
MatterHackers/MatterControl#803
Save baby step offset on first layer
=> Saving and restoring baby stepping

PartPreviewWindow/PartPreviewContent.cs, PartPreviewWindow/View3D/View3DWidget.cs, PartPreviewWindow/ViewGcodeBasic.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, Queue/QueueDataView.cs, Queue/QueueRowItem.cs, Tests/MatterControl.AutomationTests/PartPreviewTests.cs, Tests/MatterControl.AutomationTests/SqLiteLibraryProvider.cs
ensure 'view' part has no selection
Added Select All to 3d view
=> Fixed group ungroup test

SetupWizard/AndroidNetworkTroubleshootingPage.cs, SetupWizard/AndroidSetupOptionsPage.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs, Utilities/WebUtilities/RequestManager.cs, VersionManagement/WebRequestHandler.cs
- Issue MatterHackers/MCCentral#852
Android: Warn user if no internet connection when login in or creating account
- Issue MatterHackers/MCCentral#768
Sign-out -> Cancel on Android removes Sign-out buttons
=> Android sign in revisions

Tests/MatterControl.AutomationTests/PartPreviewTests.cs, Tests/MatterControl.AutomationTests/PrintQueueTests.cs
- Issue MatterHackers/MCCentral#1066
Investigate failing FixNeeded Tests
=> Revise failing tests, bring passing tests online

PrinterCommunication/Io/BabyStepsStream.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, PrinterControls/ControlWidgets/MovementControls.cs, PrinterControls/TemperatureIndicator.cs, SlicerConfiguration/SliceSettingsWidget.cs
- Issue MatterHackers/MCCentral#1069
Put in cancel baby stepping button and always show the current value (even 0)
=> Revise UI elements that reveal babystep Z values and expose easy reset

PrinterDriverInstaller/InfInstaller.cs, PrinterDriverInstaller/InfInstaller.csproj
- Fixes failure to launch InfInstaller/pnputil from InnoSetup
- Issue MatterHackers/MCCentral#1090
InnoSetup installer fails to install serial port drivers
=> Remove InfInstaller Agg dependencies, prevent ShellExecute on launch

AboutPage/UpdateControlView.cs, ActionBar/TemperatureWidgetBase.cs, ActionBar/TemperatureWidgetBed.cs, ActionBar/TemperatureWidgetExtruder.cs, CustomWidgets/PrintingWindow.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs
- Issue MatterHackers/MCCentral#1129
Create Extruder/temp/progress control
=> Add ExtruderStatusWidget

MatterControlApplication.cs, SettingsManagement/ApplicationSettings.cs
- Issue MatterHackers/MCCentral#1127
Fix startup window sizing
=> Revise window auto-centering, add maximize persistence

SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs, SlicerConfiguration/SlicerMapping/EngineMappingSlic3r.cs, SlicerConfiguration/SlicerMapping/MappingClasses.cs, SlicerConfiguration/SlicingQueue.cs, StaticData/Translations/Master.txt
Fixed slic3r bed shape
Fixed slic3r centering
Fixes: MatterHackers/MatterControl#773
Slic3r homing problem on Delta machines.
=> Made a mapping for slic3r

SlicerConfiguration/Settings/PrinterSettings.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs, StaticData/Translations/Master.txt
MatterHackers/MatterControl#1841
Outside Perimeters (Extrusion Width) setting does not have an error for invalid entries
=> Put in error for external perimeter being bad value.

PrinterControls/ControlWidgets/MacroControls.cs, Tests/MatterControl.Tests/MatterControl/LibraryProviderTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
MatterHackers/MatterControl#1859
Large amount of macros will cause some to not be visible in "Controls" panel.
=> Macro button wrapping.

CustomWidgets/DisableableWidget.cs, PrinterControls/ControlWidgets/AdjustmentControls.cs, PrinterControls/ControlWidgets/MacroControls.cs, Tests/MatterControl.AutomationTests/MatterControl.AutomationTests.csproj, Tests/MatterControl.AutomationTests/PrintingTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Guard for MatterHackers/MCCentral#1160
New exception thrown when closing MatterControl
=> Add test for MatterHackers/MCCentral#1139

SlicerConfiguration/SliceSettingsWidget.cs
- Issue MatterHackers/MCCentral#634
Changing COM port while connected is confusing
=> Prevent droplist interaction while connected

ActionBar/PrintActionRow.cs, ActionBar/PrinterConnectAndSelectControl.cs, History/PrintHistoryData.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, StaticData/Translations/Master.txt
and reconnects if auto connect
and works when not connected (like it is supposed to)
MatterHackers/MatterControl#1839
Disconnect and reconnect printer when reset is pressed, in order to enable print recovery
=> Made sure that reset connection disconnects

ActionBar/PrintActionRow.cs
- Remove single use variables
- Assign events after object creation
=> Refactor PrintActionRow

PrinterCommunication/Io/ExtrusionMultiplyerStream.cs, PrinterCommunication/Io/FeedRateMultiplyerStream.cs, PrinterCommunication/Io/GCodeFileStream.cs, PrinterCommunication/Io/GCodeStream.cs, Tests/MatterControl.Tests/MatterControl/GCodeStreamTests.cs
- Issue MatterHackers/MCCentral#1192
Feedrate adjustment is ignored - always 100%
=> Issue 1192

ActionBar/PrintActionRow.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs
Only finishing gcode sets the printer to connected not canceling (it still needs to print cancel gcode if present)
=> Un-broke print cancel

PrinterCommunication/PrinterConnectionAndCommunication.cs, StaticData/Translations/ar/Translation.txt, StaticData/Translations/cs/Translation.txt, StaticData/Translations/da/Translation.txt, StaticData/Translations/de/Translation.txt, StaticData/Translations/el/Translation.txt, StaticData/Translations/es/Translation.txt, StaticData/Translations/fa/Translation.txt, StaticData/Translations/fr/Translation.txt, StaticData/Translations/he/Translation.txt, StaticData/Translations/hi/Translation.txt, StaticData/Translations/it/Translation.txt, StaticData/Translations/ja/Translation.txt, StaticData/Translations/ko/Translation.txt, StaticData/Translations/nl/Translation.txt, StaticData/Translations/no/Translation.txt, StaticData/Translations/pl/Translation.txt, StaticData/Translations/ro/Translation.txt, StaticData/Translations/ru/Translation.txt, StaticData/Translations/tr/Translation.txt, StaticData/Translations/zh/Translation.txt
MatterHackers/MCCentral#1202
Jog controls make dangerous moves to incorrect positions
=> 	Make sure we get our position any time we create stream processors.

ActionBar/PrintActionRow.cs, ApplicationView/MainApplicationWidget.cs, CustomWidgets/PrintingWindow.cs
- Revise screensaver styling to better match template
=> Move CancelPrint code for reuse in screensaver

SlicerConfiguration/Settings/ProfileManager.cs
- Issue MatterHackers/MCCentral#1216
Import Printer throws exception if no printer selected
=> Guard against null reference

CustomWidgets/PartThumbnailWidget.cs, CustomWidgets/PrintingWindow.cs, SlicerConfiguration/SliceSettingsDetailControl.cs, SlicerConfiguration/SlicingQueue.cs, Tests/MatterControl.AutomationTests/PrintQueueTests.cs
colorize image
move show help into options menu
=> Get the right thumbnail to show for screen saver

CustomWidgets/PrintingWindow.cs, StaticData/Translations/Master.txt
Not a problem on a real printer. Did put in guard for divide by zero.
=> Made more of the printing window work

CustomWidgets/PrintingWindow.cs, PrinterControls/ManualPrinterControls.cs
=> Better positioning of movement controls

ApplicationView/AdvancedControlsPanel.cs, Tests/MatterControl.AutomationTests/PrintingTests.cs
- Issue MatterHackers/MCCentral#1266
New structure of ManualPrinterControls breaks existing test
=> Fix path to ScrollableWidget, remove dead code

PartPreviewWindow/PartPreviewContent.cs, PrinterControls/ManualPrinterControls.cs
Fixed tab background color on part preview window
Change the background color back for controls
=> Made the tuning controls layout correctly (hack)

ActionBar/PrintActionRow.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs
- Issue MatterHackers/MCCentral#1261
Wifi printing does not work on Android
=> Skip USB port validation when TCP/IP printing

CustomWidgets/DisableableWidget.cs, PrinterControls/ManualPrinterControls.cs, PrinterControls/XYZJogControls.cs
Make sure we always set the enabled level correctly when parent changed
=> Fixed the e controls to disable correctly.

ActionBar/PrinterConnectAndSelectControl.cs
- Issue MatterHackers/MCCentral#1276
No border on disabled Connect button, icon not disabled
=> Adjust border and image colors of disabled Connect button

PrinterCommunication/PrinterConnectionAndCommunication.cs, SlicerConfiguration/SliceSettingsWidget.cs
- Issue MatterHackers/MCCentral#1296
Can't connect to usb attached printer from Android after TCP/IP configuration
=> Ensure that dependant properties are updated on .ClearValue

CustomWidgets/PrintingWindow.cs, StaticData/Translations/Master.txt
Fixed theme on printing window vertical lines
=> Fixed reporting of completion on streamed gcode files

MatterControlApplication.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, PrinterEmulator/Emulator.cs, Tests/MatterControl.AutomationTests/PrintingTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
Wrote regression test for cancel print code
Made the emulator able to simulate sd card files
=> Fixed regression where we turned off sd card printing temps.

ActionBar/PrintStatusRow.cs, PrinterCommunication/Io/ExtrusionMultiplyerStream.cs, PrinterCommunication/Io/FeedRateMultiplyerStream.cs, PrinterControls/ControlWidgets/AdjustmentControls.cs, Tests/MatterControl.AutomationTests/PrintingTests.cs, Tests/MatterControl.Tests/MatterControl/GCodeStreamTests.cs
- Issue MatterHackers/MCCentral#1323
Remove Speed Multiplier persistence
=> Tuning adjustments default to 1.0 on application restart

Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Fix test timing issue where UI elements do not exist within the narrow .2 second duration
=> Wait up to 1 second for SettingsAndControls to appear

PrinterCommunication/PrinterConnectionAndCommunication.cs
- Issue MatterHackers/MCCentral#1306
System.FormatException: An invalid IP address was specified
=> Call PortIsAvailable on PortFactory

MatterControlApplication.cs
- Issue MatterHackers/MCCentral#1333
Throttle total bugs single client can send
=> Add RaygunMaxNotifications and enforce per instance reporting limits

PartPreviewWindow/View3D/UndoCommands/UngroupCommand.cs
- Ensures that ungrouped content inherits parent transforms
- Issue MatterHackers/MCCentral#1354
Ungroup command moves content positions
=> Add new UngroupCommand implementation

ApplicationView/MainApplicationWidget.cs, PartPreviewWindow/View3D/View3DWidget.cs, Queue/QueueDataWidget.cs
- Issue MatterHackers/MCCentral#1368
Rebase image DragDrop implementation on to new Agg DragDrop changes
=> Add DragDrop support for image content

StaticData/Translations/Master.txt
It's going to be a long time until design tools so putting incremental updates to 1.7.
=> Put in firmware update options.

PrinterCommunication/Io/QueuedCommandsStream.cs, PrinterCommunication/Io/RequestTemperaturesStream.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs
Make sure we don't send a 105 while waiting for position
Make sure we send a M114 immediately after G28, G29, G30
Better error timing for sending commands (less resend issues)
=> Fixed code related to position reads

PrinterCommunication/PrinterConnectionAndCommunication.cs, StaticData/SliceSettings/Properties.json, StaticData/Translations/Master.txt
=> Fixed bug with manual send of M999 and M110

PrinterCommunication/PrinterConnectionAndCommunication.cs
=> Fixed another bug with manual send of M999

PrinterControls/XYZJogControls.cs
Only z and it adds to baby stepping.
=> Make sure keyboard jog controls work correctly while printing

ControlElements/StyledMessageBoxWindow.cs, PrinterCommunication/Io/PauseHandlingStream.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, Queue/OptionsMenu/ExportToFolderProcess.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SlicerMapping/EngineMapingBase.cs, StaticData/SliceSettings/Layouts.txt, StaticData/SliceSettings/Properties.json, StaticData/Translations/Master.txt
Made the ok button on message box customizable.
=> Added support for pause message on auto pause and filament run out.

SetupWizard/SetupWizardWifi.cs
- Issue MatterHackers/MCCentral#1468
Crash on T10 out of the box when clicking Wifi Setup -> Skip
=> Use RunOnIdle to prevent Collection Modified exceptions

PrinterCommunication/PrinterConnectionAndCommunication.cs, PrinterControls/TemperatureIndicator.cs
fixes: MatterHackers/MCCentral#1470
Unable to connect to printer
=> Add output message for timeout exception

EeProm/EePromMarlinWindow.cs, EeProm/EePromRepetierWindow.cs
Fixes: MatterHackers/MCCentral#1423
EEProm windows should close on printer disconnect
=> Close the eeprom window if the printer disconnects.

CustomWidgets/WizardControl.cs, Tests/MatterControl.AutomationTests/PrintingTests.cs, Tests/MatterControl.AutomationTests/SliceSettingsTests.cs
Fixed disabled color on leveling wizard
=> Fixed test to consider new pause behavior

PrinterCommunication/PrinterConnectionAndCommunication.cs, PrinterEmulator/Emulator.cs, Tests/MatterControl.AutomationTests/PrintingTests.cs
Fixed resend bug with board reset
Improved emulator to do resend correctly
=> Wrote new test for resend

Utilities/AuthenticationData.cs
- Issue MatterHackers/MCCentral#1457
First run, enable wifi, sign-in fails with 'Enable wifi' page
=> Add method to mark as offline

Library/Widgets/ListView/ListView.cs
- Issue MatterHackers/MCCentral#1497
=> Only switch to container if not null

MatterControlApplication.cs
- Issue MatterHackers/MCCentral#1498
Incorrect startup position
=> Constrain window height to desktop bounds

ActionBar/ActionBarPlus.cs, ActionBar/PrintStatusRow.cs, ActionBar/PrinterConnectAndSelectControl.cs, ApplicationView/AdvancedControlsPanel.cs, ApplicationView/ApplicationController.cs, ConfigurationPage/PrinterConfigurationPage.cs, CustomWidgets/LibrarySelector/FolderBreadCrumbWidget.cs, Library/Widgets/PrintLibraryWidget.cs, PartPreviewWindow/OverflowDropdown.cs, PartPreviewWindow/PartPreviewContent.cs, PartPreviewWindow/View3D/PrinterActionsBar.cs, PartPreviewWindow/View3D/View3DWidget.cs, PartPreviewWindow/ViewControls3D.cs, PrinterControls/ManualPrinterControls.cs, SlicerConfiguration/SliceSettingsWidget.cs
- Fix temperature widget flow orientation for toolbar
- Create reusable constructor function for tabcontrols
- Conditional printer tab title of "Printer" or [PrinterName]
=> Sync tab styling

ApplicationView/ApplicationController.cs, MatterControlApplication.cs, PartPreviewWindow/BaseClasses/PartPreview3DWidget.cs, PartPreviewWindow/BaseClasses/PartPreviewWidget.cs, PartPreviewWindow/OverflowDropdown.cs, PartPreviewWindow/PartPreviewContent.cs, PartPreviewWindow/View3D/PrinterActionsBar.cs, PartPreviewWindow/View3D/View3DWidget.cs, PartPreviewWindow/ViewControls3D.cs, PartPreviewWindow/ViewGcodeBasic.cs, Tests/MatterControl.Tests/SceneTests.cs
- Revert to 1.7/ViewGcodeBasic code and make functional
=> Fix Layer3D view in design_tools, sync part/layer views on enter

ActionBar/PrinterConnectAndSelectControl.cs, MatterControl.csproj, MatterControlApplication.cs, PartPreviewWindow/OverflowDropdown.cs, PartPreviewWindow/PartPreviewContent.cs, PartPreviewWindow/View3D/GridOptionsPanel.cs, PartPreviewWindow/View3D/PrinterActionsBar.cs, PartPreviewWindow/View3D/SideBar/MirrorControls.cs, PartPreviewWindow/View3D/SideBar/RotateControls.cs, PartPreviewWindow/View3D/SideBar/ScaleControls.cs, PartPreviewWindow/View3D/View3DWidget.cs, PartPreviewWindow/ViewGcodeBasic.cs
- Use IIgnoredPopupChild marker interface
- Extract RotateControl to new file
- Use PopupActionPanel base for conditional close behavior
- Extract Grid options to new GridOptionsPanel.cs
- Fix null reference on translate/scale of gcodeViewWidget
- Issue MatterHackers/MCCentral#1528
Popup widget should support controls which do not cause menu close
=> Add support for conditional close to menus

PartPreviewWindow/View3D/View3DWidget.cs
=> Got decent filtering working correctly

ConfigurationPage/PrintLeveling/PrintLevelPages.cs, PartPreviewWindow/View3D/View3DWidget.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, SlicerConfiguration/Settings/PrinterSettings.cs, StaticData/Translations/Master.txt
Removed dead code
Fixed bug with smoothie asking for next line
=> Added error message for z offset > 2mm

ApplicationView/ApplicationController.cs, PartPreviewWindow/BaseClasses/PartPreview3DWidget.cs, PartPreviewWindow/PartPreviewContent.cs, PartPreviewWindow/View3D/Gui3D/HeightValueDisplay.cs, PartPreviewWindow/View3D/Gui3D/SnapingIndicator.cs, PartPreviewWindow/View3D/Gui3D/UpArrow3D.cs, PartPreviewWindow/View3D/View3DWidget.cs, PartPreviewWindow/ViewGcodeWidget.cs
- Host on MeshViewer in MatterControl
- Issue MatterHackers/MCCentral#1536
TrackballTumble perspective should not change after clicking Generate
=> Move world transforms outs of TrackballTumbleWidget

PartPreviewWindow/ViewGcodeBasic.cs
- Hook meshViewer close and persist world transforms if visible
- Apply meshViewer world transforms on load if initialized
- Release event handlers on load if initialized (must occur after Close)
- Issue MatterHackers/MCCentral#1536
TrackballTumble perspective should not change after clicking Generate
=> Restore perspective after Generate button creates new children

ConfigurationPage/PrintLeveling/LevelWizard7PointRadial.cs, ConfigurationPage/PrintLeveling/LevelWizardMesh.cs, ConfigurationPage/PrintLeveling/PrintLevelPages.cs, ConfigurationPage/PrintLeveling/PrintLevelingData.cs, PrinterCommunication/Io/PrintLevelingStream.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SlicerMapping/EngineMapingBase.cs, StaticData/SliceSettings/Layouts.txt, StaticData/SliceSettings/Properties.json, StaticData/Translations/Master.txt
=> Made sure leveling solution recalculated on change

StaticData/Translations/Master.txt, StaticData/Translations/ar/Translation.txt, StaticData/Translations/cs/Translation.txt, StaticData/Translations/da/Translation.txt, StaticData/Translations/de/Translation.txt, StaticData/Translations/el/Translation.txt, StaticData/Translations/es/Translation.txt, StaticData/Translations/fa/Translation.txt, StaticData/Translations/fr/Translation.txt, StaticData/Translations/he/Translation.txt, StaticData/Translations/hi/Translation.txt, StaticData/Translations/it/Translation.txt, StaticData/Translations/ja/Translation.txt, StaticData/Translations/ko/Translation.txt, StaticData/Translations/nl/Translation.txt, StaticData/Translations/no/Translation.txt, StaticData/Translations/pl/Translation.txt, StaticData/Translations/ro/Translation.txt, StaticData/Translations/ru/Translation.txt, StaticData/Translations/tr/Translation.txt, StaticData/Translations/zh/Translation.txt
=> New translations

Library/Providers/MatterControl/SqliteLibraryContainer.cs, PartPreviewWindow/View3D/PrinterActionsBar.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs, Tests/MatterControl.AutomationTests/LocalLibraryTests.cs, Tests/MatterControl.AutomationTests/PrintingTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Issue MatterHackers/MCCentral#1557
SqliteContainer -> AddItems results in library item with generated rather than original file name
- Issue MatterHackers/MCCentral#1505
Tests assume 'Start Print' is available but that behavior was coupled with Queue Selection/ActivePrintItem
=> SqliteLibrary tests

Library/Providers/MatterControl/SqliteLibraryContainer.cs, Tests/MatterControl.AutomationTests/LocalLibraryTests.cs
- Issue MatterHackers/MCCentral#1558
Zip files added to SqliteContainer are not expanded
=> Expand zips on add to SqliteContainer

Library/ContentProviders/MeshContentProvider.cs, Tests/MatterControl.AutomationTests/ExportItemWindowTests.cs, Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs, Tests/MatterControl.AutomationTests/MatterControl.AutomationTests.csproj, Tests/MatterControl.AutomationTests/MatterControlTests.cs, Tests/MatterControl.AutomationTests/PrinterDropDownTests.cs, Tests/MatterControl.AutomationTests/SliceSettingsTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Issue MatterHackers/MCCentral#1567
Thumbnail rendering mode ignored by MeshContentProvider
=> Fix thumbnail rendering, update tests

Library/ContentProviders/MeshContentProvider.cs, Tests/MatterControl.AutomationTests/PartPreviewTests.cs
- Issue MatterHackers/MCCentral#1574
Test automation of IObject3D elements not functioning due to name mismatches
=> Fix naming issues with IObject3D and FindNamedChildrenRecursive

Library/Widgets/PrintLibraryWidget.cs, PartPreviewWindow/SaveAsWindow.cs, PartPreviewWindow/View3D/View3DWidget.cs, PartPreviewWindow/ViewGcodeBasic.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, Tests/MatterControl.AutomationTests/PartPreviewTests.cs, Tests/MatterControl.AutomationTests/PrintingTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Issue MatterHackers/MCCentral#1576
Changes on bedplate are not reflected when slicing
=> Ensure bedplate is saved before slicing 

History/PrintHistoryListItem.cs, Library/Providers/MatterControl/SqliteLibraryContainer.cs, PartPreviewWindow/View3D/View3DWidget.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, Queue/QueueData.cs, Tests/MatterControl.AutomationTests/PartPreviewTests.cs, Tests/MatterControl.AutomationTests/PrintQueueTests.cs, Tests/MatterControl.AutomationTests/SqLiteLibraryProvider.cs
- Issue MatterHackers/MCCentral#1573
QueueData.Instance.SelectedIndex
=> Remove SelectedIndex/Selection functionality from QueueData

ConfigurationPage/ApplicationSettings/ApplicationSettingsView.cs, MatterControlApplication.cs, PartPreviewWindow/View3D/View3DWidget.cs, SettingsManagement/UserSettings.cs, StaticData/Translations/Master.txt
Turned off control and shift from changing view state.
=> Making control add to selection.

SlicerConfiguration/SliceSettingsDetailControl.cs, SlicerConfiguration/SliceSettingsWidget.cs, Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs, Tests/MatterControl.AutomationTests/PrinterDropDownTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Test helper should auto open SliceSettings overflow menu
- Fix product bug with null settingsLevel
=> Revise PrinterNameChangePersists test, fix blocking test issue

ApplicationView/AdvancedControlsPanel.cs, ApplicationView/MenuRow/MenuOptionSettings.cs, ApplicationView/WidescreenPanel.cs, CustomWidgets/DockingTabControl.cs, MatterControl.csproj, PartPreviewWindow/OverflowDropdown.cs, PartPreviewWindow/PartPreviewContent.cs
=> Improved docking control

PartPreviewWindow/OverflowDropdown.cs, PartPreviewWindow/PartPreviewContent.cs, PartPreviewWindow/View3D/PrinterActionsBar.cs
Put terminal into tab controls
=> Moved tab controls into printer

ApplicationView/ApplicationController.cs, ApplicationView/WidescreenPanel.cs, CustomWidgets/DockingTabControl.cs, PartPreviewWindow/View3D/View3DWidget.cs, Tests/MatterControl.AutomationTests/PrintingTests.cs, Tests/MatterControl.AutomationTests/SliceSettingsTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Fix tests
- Gracefully shutdown ThumbnailGeneration task
- Resolve ActivePrintItem regression - MatterHackers/MCCentral#1612
Null ActivePrintItem regression causing missing Generate button & failing tests
=> Switch tests to Controls tab as needed

PrinterCommunication/Io/PauseHandlingStream.cs, Tests/MatterControl.AutomationTests/CheckBoxInLibraryIsClickable.cs, Tests/MatterControl.AutomationTests/ExportItemWindowTests.cs, Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs, Tests/MatterControl.AutomationTests/LibraryActionTests.cs, Tests/MatterControl.AutomationTests/LibraryDownloadsTest.cs, Tests/MatterControl.AutomationTests/LocalLibraryTests.cs, Tests/MatterControl.AutomationTests/PartPreviewTests.cs, Tests/MatterControl.AutomationTests/PrintQueueTests.cs, Tests/MatterControl.AutomationTests/PrintQueueUncertain.cs, Tests/MatterControl.AutomationTests/PrinterDropDownTests.cs, Tests/MatterControl.AutomationTests/PrintingTests.cs, Tests/MatterControl.AutomationTests/SliceSettingsTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs, Tests/MatterControl.Tests/MatterControl/PerformanceTests.cs
- Issue MatterHackers/MCCentral#1619
Automation ClickByName should not take a timeout value, should use sane default
- Issue MatterHackers/MCCentral#1613
Typo in pause dialog
=> Remove timeout from ClickByName

ConfigurationPage/PrintLeveling/LevelWizard3Point.cs, ConfigurationPage/PrintLeveling/LevelWizard7PointRadial.cs, ConfigurationPage/PrintLeveling/LevelWizardMesh.cs, ConfigurationPage/PrintLeveling/PrintLevelPages.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SlicerMapping/EngineMapingBase.cs, StaticData/SliceSettings/Layouts.txt, StaticData/SliceSettings/Properties.json
Put z height on leveling wizard
=> Took out z can be negative.

PartPreviewWindow/View3D/View3DWidget.cs
- Issue MatterHackers/MCCentral#1645
Drag/drop from shell to View3DWidget not allowed
=> Fix regression in drag/drop to View3DWidget

AboutPage/ContactForm.cs, ApplicationView/ApplicationController.cs, CustomWidgets/PrintProgressBarWidget.cs, History/PrintHistoryListItem.cs, Library/ContentProviders/GCodeContentProvider.cs, Library/Widgets/ListView/ListView.cs, Library/Widgets/ListView/ListViewItemBase.cs, Library/Widgets/PrintLibraryWidget.cs, MatterControl.csproj, PartPreviewWindow/PartPreviewMainWindow.cs, PartPreviewWindow/View3D/View3DWidget.cs, SlicerConfiguration/Settings/ActiveSliceSettings.cs, StaticData/Translations/Master.txt, Tests/MatterControl.AutomationTests/PrintingTests.cs
- Issue MatterHackers/MCCentral#1647
Theme factories not fully intialized on load
- MatterHackers/MCCentral#1572
Determine what CancelingSdCardPrintLeavesHeatAndFanOn is validating and port to new model
=> Design tools

ConfigurationPage/PrintLeveling/LevelWizardBase.cs, ConfigurationPage/PrintLeveling/PrintLevelPages.cs, StaticData/Translations/Master.txt
Server auto leveling working with marlin firmware
=> Fixed the M280 command to work with marlin

PrinterControls/ManualPrinterControls.cs
- Issue MatterHackers/MCCentral#1616
Investigate FirmwareUpdaterDetectsDeviceFirmware failure
=> Execute AddPlugins logic at load time

CustomWidgets/ExportPrintItemWindow.cs, MatterControl.csproj, PrinterCommunication/Io/ProcessWriteRegexStream.cs, PrinterCommunication/Io/RequestTemperaturesStream.cs, PrinterCommunication/PrinterConnectionAndCommunication.cs, StaticData/Translations/Master.txt
Made it work with gcode export
=> Moved ProcessWriteRegex to stream

MatterControl.csproj, PartPreviewWindow/ViewGcodeBasic.cs, packages.config
- Issue MatterHackers/MCCentral#1687
Slicing hangs at Generating Layer Outlines
=> Downgrade ValueTuple to 4.3.0, fix null reference in ViewGCodeBasic

PrinterEmulator/Emulator.cs
- More clearly indicate non-used Read/Write signatures with exceptions
=> Use queues for send/receive buffers, only Wait for received commands

ApplicationView/ApplicationController.cs, MatterControl.OpenGL/GCodeRenderer/GCodeRenderInfo.cs, PartPreviewWindow/GCode2DWidget.cs, PartPreviewWindow/ViewGcodeBasic.cs
- Issue MatterHackers/MCCentral#1694
Changing Layer view options has no effect
=> Update RenderType on settings change

SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs, StaticData/SliceSettings/Layouts.txt, StaticData/SliceSettings/Properties.json, StaticData/Translations/Master.txt
Made the change islands retract always occur if requested.
=> Put in the ability to ramp the extra extrusion after move

PartPreviewWindow/SaveAsWindow.cs, PartPreviewWindow/View3D/View3DWidget.cs
- Issue MatterHackers/MCCentral#1720
Remove confusing SaveAsReturnInfo from View3DWidget.SaveChanges
=> Remove SaveAsReturnInfo from primary save function

SlicerConfiguration/SlicingQueue.cs
- Issue MatterHackers/MCCentral#1724
Unable to slice bedplate
=> Fix exception during slicing - use zero based index

Library/Widgets/ListView/ListViewItemBase.cs, PartPreviewWindow/View3D/DragDropLoadProgress.cs, PartPreviewWindow/View3D/Gui3D/MoveInZControl.cs, PartPreviewWindow/View3D/Gui3D/SnapingIndicator.cs
- Issue MatterHackers/MCCentral#1725
Progress bars no longer appearing when items added to bed
=> Restore View3D progress bars for loading drag items

Library/Widgets/ListView/ListViewItemBase.cs
- Issue MatterHackers/MCCentral#1728
Filter RayTracing thumbnail operations to drawing items only
=> Skip queued thumbnail generation tasks for off-screen items

PartPreviewWindow/PrinterTabPage.cs, PartPreviewWindow/View3D/DragDropLoadProgress.cs, PartPreviewWindow/View3D/SceneActions.cs
- Issue MatterHackers/MCCentral#1723
Can't ungroup .mcx files
- Issue MatterHackers/MCCentral#1733
Progress bar updates only occur during drags
=> Improve progress bar updates and allow ungroup of .mcx files

ApplicationView/ApplicationController.cs, CustomWidgets/ExportPrintItemWindow.cs, Library/ContentProviders/MeshContentProvider.cs, Library/Providers/MatterControl/SqliteLibraryContainer.cs, Library/Widgets/ListView/ListViewItem.cs, MatterControl.Printing/GCode/GCodeFile.cs, MatterControl.Printing/GCode/GCodeMemoryFile.cs, PartPreviewWindow/CreateDiscreteMeshes.cs, PartPreviewWindow/View3D/DragDropLoadProgress.cs, PartPreviewWindow/View3D/Gui3D/MoveInZControl.cs, PartPreviewWindow/View3D/MeshViewerWidget.cs, PartPreviewWindow/View3D/PrinterActionsBar.cs, PartPreviewWindow/View3D/SceneActions.cs, PartPreviewWindow/View3D/View3DWidget.cs, PartPreviewWindow/ViewGcodeBasic.cs, PrinterCommunication/PrinterConnection.cs, Queue/OptionsMenu/ExportToFolderProcess.cs, SlicerConfiguration/SlicingQueue.cs, Tests/MatterControl.Tests/MatterControl/Slicing/SliceLayersTests.cs, Tests/MatterControl.Tests/SceneTests.cs
- Issue MatterHackers/MCCentral#1736
Progress reporting and task cancellation should be separated and improved
=> Revise ReportProgressRatio implementation

CustomWidgets/ExportPrintItemWindow.cs, MatterControlApplication.cs, PartPreviewWindow/View3D/View3DWidget.cs, TextCreator/CardHolderTool/CardHolder.cs
- Issue MatterHackers/MCCentral#1735
Drag-drop delay - loading simple .mcx file takes ~5 seconds
=> Convert PluginFinder to static class with generic methods

Tests/MatterControl.Tests/MatterControl.Tests.csproj
- Issue MatterHackers/MCCentral#1755
Get Linux builds scripts working in GCE
=> Fix casing issue on mono

PrinterCommunication/PrinterConnectionAndCommunication.cs
- Issue MatterHackers/MCCentral#1683
Dropped comment lines should output to Terminal for log replays
=> Write comments to terminal to support log replays and debugging

CustomWidgets/NamedAction.cs, Library/Widgets/ListContainerBrowser.cs, Library/Widgets/PrintLibraryWidget.cs, PartPreviewWindow/View3D/PrinterActionsBar.cs
- Issue MatterHackers/MCCentral#1786
Printer overflow menu should host menuitems not buttons
- Issue MatterHackers/MCCentral#1787
Implement breadcrumb and search bars in new container browser
- Issue MatterHackers/MCCentral#1785
EEProm action should move into overflow menu
=> Switch buttons to menuitems, move eeprom, revise container browser

PartPreviewWindow/View3D/BaseObject3DEditor.cs
=> Set solid color when clicked

PartPreviewWindow/View3D/View3DWidget.cs
- Issue MatterHackers/MCCentral#1794
Selections need more than a single editor
=> Wildcard map Object3D editors onto all types

ActionBar/TemperatureWidgetBed.cs, ActionBar/TemperatureWidgetExtruder.cs
- Issue MatterHackers/MCCentral#1760
Complete Heated Bed popup
=> Add temperature targets to extruder/bed dropdown panels

ApplicationView/ApplicationController.cs, Library/Interfaces/ILibraryContainerLink.cs, Library/Providers/DynamicContainerLink.cs, Library/Providers/FileSystem/FileSystemContainer.cs, Library/Providers/MatterControl/SqliteLibraryContainer.cs, Library/Providers/Zip/LocalZipContainerLink.cs, Library/Widgets/ListView/ListView.cs, PartPreviewWindow/SaveAsWindow.cs
- Filter SaveAs dialog to writable containers only
- Issue MatterHackers/MCCentral#1792
SaveAs window should only show writable locations
=> Add support for ListView filtering & property for container IsReadOnly

ApplicationView/ThemeConfig.cs, PartPreviewWindow/View3D/BaseObject3DEditor.cs
- Issue MatterHackers/MCCentral#1797
Inconsistent button styling
=> Make button styling consistent with siblings

SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SliceSettingsOrganizer.cs, SlicerConfiguration/SliceSettingsWidget.cs, SlicerConfiguration/SlicerMapping/EngineMapingBase.cs, SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs, SlicerConfiguration/SlicerMapping/MappingClasses.cs, StaticData/SliceSettings/Layouts.txt, StaticData/SliceSettings/Properties.json
Made slice settings disable work
=> Put in a enable retract setting

ConfigurationPage/ApplicationSettings/ApplicationSettingsView.cs, Library/Providers/GeneratorItem.cs, Library/Providers/LibraryConfig.cs
- Issue MatterHackers/MCCentral#1801
Restore Rebuild Thumbnails functionality
- Issue MatterHackers/MCCentral#1802
Colorize primitives thumbnails
=> Colorize primitives

Library/Widgets/ListView/ListViewItemBase.cs, Library/Widgets/PrintLibraryWidget.cs
- MatterHackers/MCCentral#1816
"Add to Plate" does not work on primitives
=> Update AddToPlate to support ContentItem & ContentStream interfaces

PartPreviewWindow/View3D/View3DWidget.cs
Work on enable disable of actions
This needs more design consideration but is a good start.
=> Put in a start at the align control

PartPreviewWindow/View3D/View3DWidget.cs, StaticData/Translations/Master.txt
=> Make sure we can ungroup meshes

Library/Widgets/ListView/IconListView.cs
- Issue MatterHackers/MCCentral#1765
Library Reflow
=> Reflow library on bounds changed

ApplicationView/ApplicationController.cs, Library/Widgets/ListView/IconListView.cs
- Issue MatterHackers/MCCentral#1784
Enlarge scroll container thumb on mouse over
=> Expand scrollbar thumb bounds on hover, fix regression

PartPreviewWindow/View3D/BedMeshGenerator.cs, PartPreviewWindow/View3D/GeneralObject3DEditor.cs, PartPreviewWindow/View3D/MeshViewerWidget.cs, PartPreviewWindow/View3D/View3DWidget.cs
=> Better selection rendering

ApplicationView/ApplicationController.cs, CustomWidgets/DockingTabControl.cs, Library/Widgets/ListView/IconListView.cs, MatterControlApplication.cs, PartPreviewWindow/PrinterTabPage.cs, PrinterControls/ControlWidgets/MacroControls.cs, SlicerConfiguration/SliceSettingsWidget.cs, StaticData/Translations/Master.txt
Make the default slice settings size better
Make a minimum dock window size
fixed terminal in floating mode
found text wrapping bug (actually is center | fit)
improved icon layout in part view (better padding vs margin)
put minimum size on text of slice setting
removed extra unused gui widget from settings name
put in debug stack navigation F2 F3
=> Make un-pin keep the current window open

PartPreviewWindow/View3D/MeshViewerWidget.cs, PartPreviewWindow/View3D/SceneActions.cs, PartPreviewWindow/View3D/View3DWidget.cs
=> Faster transform

AboutPage/HTMLParser/HtmlParser.cs, AboutPage/HTMLParser/HtmlWidget.cs, ApplicationView/ApplicationController.cs, ControlElements/MHTextEditWidget.cs, MatterControl.csproj, PartPreviewWindow/View3D/View3DWidget.cs, PrinterCommunication/PrinterConnection.cs, SetupWizard/CopyGuestProfilesToUser.cs, SetupWizard/PublishPartToMatterHackers.cs
Started work on a publish to MatterHackers
=> Made the bed change on printer change

AboutPage/CheckForUpdatesPage.cs, PartPreviewWindow/PartPreviewContent.cs, StaticData/Translations/Master.txt
Made the check for update text wrap
=> Made the update available text show up when available

.yaspellerrc, ActionBar/TemperatureWidgetBase.cs, ActionBar/TemperatureWidgetBed.cs, ActionBar/TemperatureWidgetExtruder.cs, CustomWidgets/EditableNumberDisplay.cs, Library/Widgets/PrintLibraryWidget.cs, PrinterCommunication/PrinterConnection.cs, PrinterControls/ControlWidgets/FanControls.cs, SlicerConfiguration/SettingsControlSelectors.cs, SlicerConfiguration/SlicePresetsWindow/SlicePresetsWindow.cs, StaticData/Translations/Master.txt, Tests/MatterControl.AutomationTests/SliceSettingsTests.cs
Theme  the folders check box
Make sure we reset the macros when we start them (made clear by unload -> cancel -> unload)
Made fan controls more consistent with actual data model of printer
improved edit number display to be more consistent with 3d number edits
=> Wrote test for Hotend drop down

ActionBar/TemperatureWidgetExtruder.cs, ConfigurationPage/RunningMacroPage.cs, CustomWidgets/PrintingWindow.cs, PrinterCommunication/Io/MacroProcessingStream.cs, PrinterCommunication/Io/WaitForTempStream.cs, PrinterCommunication/PrinterConnection.cs, Tests/MatterControl.AutomationTests/PrintingTests.cs, Tests/MatterControl.AutomationTests/SliceSettingsTests.cs
Refactoring extruder to hotend where true
=> Finished the temperature widget tests and implementation

ApplicationView/ThemeConfig.cs, CustomWidgets/SolidSlider.cs, PartPreviewWindow/PrinterTabPage.cs, PartPreviewWindow/View3D/MeshViewerWidget.cs, PartPreviewWindow/View3D/SceneActions.cs, PartPreviewWindow/View3D/View3DWidget.cs, PrinterControls/ControlWidgets/AdjustmentControls.cs, Queue/OptionsMenu/PartsSheetCreator.cs, TextCreator/Braille/BrailleEditor.cs, TextCreator/Braille/BrailleGenerator.cs, TextCreator/Text/TextGenerator.cs
=> Refactoring VisibleMeshes into extension method

ActionBar/TemperatureWidgetBase.cs, ActionBar/TemperatureWidgetBed.cs, ActionBar/TemperatureWidgetExtruder.cs, CustomWidgets/DisableablePanel.cs, MatterControl.csproj, SlicerConfiguration/SliceSettingsWidget.cs
- Issue MatterHackers/MCCentral#1672
Add disablable overlay panel to temp controls when not connected to printer
=> Add disabled overlay to temperature controls

PartPreviewWindow/View3D/InteractionLayer.cs, PartPreviewWindow/View3D/MeshViewerWidget.cs, PartPreviewWindow/View3D/View3DWidget.cs
Made a opaque and transparent RenderGL event
=> Fixed the gcode not visible looking up from under the bed

ApplicationView/ApplicationController.cs, ApplicationView/PrinterModels.cs, PartPreviewWindow/View3D/BedMeshGenerator.cs, PartPreviewWindow/View3D/MeshViewerWidget.cs, PartPreviewWindow/View3D/View3DWidget.cs, PrinterCommunication/PrinterConnection.cs, SlicerConfiguration/PresetSelectorWidget.cs, SlicerConfiguration/Settings/ProfileManager.cs, SlicerConfiguration/SliceSettingsWidget.cs, SlicerConfiguration/UIFields/ExtruderOffsetField.cs, Tests/MatterControl.AutomationTests/SliceSettingsTests.cs
- MatterHackers/MCCentral#1940
Bed not showing initial size
=> Restore correct bed settings on load

Library/Export/GCodeExport.cs
- Issue MatterHackers/MCCentral#1954
Investigate failing ExportAsGcode test
=> Use ActivePrinter reference to resolve active PrintItemWrapper

SlicerConfiguration/SliceSettingsWidget.cs, SlicerConfiguration/UIFields/ComPortField.cs, Tests/MatterControl.Tests/MatterControl.Tests.csproj, Tests/MatterControl.Tests/MatterControl/SliceSettingsFieldTests.cs
- Issue MatterHackers/MCCentral#1957
Serial port changes have no effect, can't connect to printer
=> Fix broken ComPortField, add basic field test

SlicerConfiguration/Settings/PrinterSettings.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, SlicerConfiguration/SlicerMapping/EngineMapingBase.cs, SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs, StaticData/SliceSettings/Layouts.txt, StaticData/SliceSettings/Properties.json, StaticData/Translations/Master.txt
=> Added in the ability to set the number of first layers

Library/ContentProviders/MeshContentProvider.cs, PartPreviewWindow/View3D/PrinterActionsBar.cs, PartPreviewWindow/View3D/View3DWidget.cs, Queue/PrintItemWrapper.cs
- Issue MatterHackers/MCCentral#1966
Investigate CancelingNormalPrintTurnsHeatAndFanOff test failure
- Issue MatterHackers/MCCentral#1962
Repair regressions caused by new DragDrop
=> Fix CancelingNormalPrintTurnsHeatAndFanOff

MatterControlApplication.cs, Utilities/InspectForm.Designer.cs, Utilities/InspectForm.cs
=> Add scene inspection

CustomWidgets/ExportPrintItemPage.cs, Library/ContentProviders/MeshContentProvider.cs, Library/Widgets/InsertionGroup.cs, Library/Widgets/ListView/ListView.cs, Library/Widgets/PrintLibraryWidget.cs, PartPreviewWindow/View3D/MeshViewerWidget.cs, PartPreviewWindow/View3D/SceneActions.cs, PartPreviewWindow/View3D/UndoCommands/DeleteUndoCommand.cs, PartPreviewWindow/View3D/UndoCommands/GroupCommand.cs, PartPreviewWindow/View3D/UndoCommands/InsertCommand.cs, PartPreviewWindow/View3D/UndoCommands/UngroupCommand.cs, PartPreviewWindow/View3D/View3DWidget.cs, Tests/MatterControl.Tests/SceneTests.cs, TextCreator/Braille/BrailleEditor.cs, TextCreator/Braille/BrailleGenerator.cs, TextCreator/CardHolderTool/BendOperation.cs, TextCreator/CardHolderTool/CardHolder.cs, TextCreator/Text/TextEditor.cs
- MatterHackers/MCCentral#1975
Multi-select DragDrop content now centered at origin rather than aligned in row
=> IObject3D.Children

ActionBar/TemperatureWidgetBase.cs, CustomWidgets/DisableablePanel.cs, Library/Widgets/ListView/ListView.cs, Library/Widgets/ListView/ListViewItem.cs, PartPreviewWindow/View3D/SceneActions.cs, PartPreviewWindow/View3D/View3DWidget.cs
- Issue MatterHackers/MCCentral#1994
Action bar should disable rather than disappear during long tasks
=> Disable rather than hide SelectionActionBar

CustomWidgets/DockingTabControl.cs
- Issue MatterHackers/MCCentral#1992
Unpin should collapse
=> Close after unpin

Library/ContentProviders/MeshContentProvider.cs, Library/Widgets/InsertionGroup.cs, Library/Widgets/ListView/ListView.cs, PartPreviewWindow/PlatingHelper.cs, PartPreviewWindow/View3D/SceneActions.cs, PartPreviewWindow/View3D/View3DWidget.cs
- Issue MatterHackers/MCCentral#1772
Plate items at bed center
=>  Plate at bed center, show progress during load

CustomWidgets/LibrarySelector/FolderBreadCrumbWidget.cs, MatterControlApplication.cs, VersionManagement/WebRequestHandler.cs
- Issue MatterHackers/MCCentral#2047
Invalid window position on test startup
=> Revise Winforms startup positioning

ApplicationView/ApplicationController.cs, CustomWidgets/DataViewGraph.cs, CustomWidgets/DropDownMenuWidget.cs, MatterControl.OpenGL/GCodeRenderer/RenderFeatures/RenderFeatureExtrusion.cs, MatterControl.OpenGL/GCodeRenderer/RenderFeatures/RenderFeatureTravel.cs, PartPreviewWindow/GCode2DWidget.cs, PartPreviewWindow/PlatingHelper.cs, PartPreviewWindow/View3D/InteractionVolume.cs, PartPreviewWindow/View3D/View3DWidget.cs, PrinterCommunication/PrinterConnection.cs, SlicerConfiguration/Slicing/SliceLayer.cs
=> Refactoring PathStorage -> VertexStorage

MatterControlApplication.cs
- Set in scope ClosingEventArg.Cancel as required rather than extra
call to .Close
=> Revise Closing, single MessageBox call, collapse delegate into scope

ApplicationView/ApplicationController.cs, Library/Widgets/InsertionGroup.cs, MatterControlApplication.cs, PartPreviewWindow/PlatingHelper.cs, PartPreviewWindow/View3D/ColorSwatchSelector.cs, PartPreviewWindow/View3D/GeneralObject3DEditor.cs, PartPreviewWindow/View3D/SceneActions.cs, PartPreviewWindow/View3D/UndoCommands/GroupCommand.cs, PartPreviewWindow/View3D/UndoCommands/UngroupCommand.cs, PartPreviewWindow/View3D/View3DWidget.cs, StaticData/Translations/Master.txt, TextCreator/Braille/BrailleGenerator.cs, TextCreator/Text/TextGenerator.cs, Utilities/InspectForm.cs
=> Making support be an object 3D wrapper

ApplicationView/ApplicationController.cs, MatterControl.csproj, PartPreviewWindow/View3D/DifferenceObject3D.cs, StaticData/Translations/Master.txt, Utilities/InspectForm.cs
Modify 3DView tree on UiThread
=> Working on new Difference action

PartPreviewWindow/View3D/DifferenceObject3D.cs, PartPreviewWindow/View3D/MeshViewerWidget.cs
set holes to invisible after applying to boolean
=> Filter visible objects

ActionBar/PrinterSelector.cs, ActionBar/TemperatureWidgetBed.cs, ActionBar/TemperatureWidgetExtruder.cs, ApplicationView/ApplicationController.cs, ControlElements/StyledMessageBoxWindow.cs, CustomWidgets/ExportPrintItemPage.cs, Library/Export/GCodeExport.cs, Library/Providers/MatterControl/SqliteLibraryContainer.cs, PartPreviewWindow/PlusTabPage.cs, PartPreviewWindow/View3D/PrinterActionsBar.cs, PartPreviewWindow/View3D/SlicePopupMenu.cs, PrinterControls/TerminalWindow/TerminalWidget.cs, SetupWizard/ImportSettingsPage.cs, SetupWizard/WizardPage.cs, SetupWizard/WizardWindow.cs, SlicerConfiguration/Settings/PrinterSettings.cs, SlicerConfiguration/Settings/SettingsHelpers.cs, Utilities/ProjectFileHandler.cs
- Issue MatterHackers/MCCentral#2096
StyledMessageBox uses non-standard styling
=> Convert StyledMessageBox over to WizardPage

PartPreviewWindow/SelectedObjectPanel.cs, PartPreviewWindow/View3D/Actions/DifferenceGroup.cs, PartPreviewWindow/View3D/ColorSwatchSelector.cs
=> Make the color selector working

TextCreator/Text/TextEditor.cs, TextCreator/Text/TextGenerator.cs, TextCreator/TextCreatorPlugin.cs
removed underline
made spacing correct
put back in spacing slider
=> Cleaned up text object

ApplicationView/ThemeConfig.cs, Library/Widgets/ExpandCheckboxButton.cs, Library/Widgets/PrintLibraryWidget.cs, MatterControl.OpenGL/GCodeRenderer/ExtrusionColors.cs, MatterControl.csproj, PartPreviewWindow/ColorGradientWidget.cs, PartPreviewWindow/GCodeDetailsView.cs, PartPreviewWindow/SectionWidget.cs, PartPreviewWindow/SpeedsLegend.cs, PartPreviewWindow/ViewGcodeBasic.cs, StaticData/Translations/Master.txt
=>  Combine GCode details/Speeds legend controls. Create Section widget

ApplicationView/ApplicationController.cs, MatterControl.csproj, PartPreviewWindow/View3D/Actions/DifferenceEditor.cs, PartPreviewWindow/View3D/Actions/IntersectGroup.cs, PartPreviewWindow/View3D/Actions/MeshWrapperOwner.cs, PartPreviewWindow/View3D/Actions/PaintMaterialGroup.cs
Refactoring all boolean type opperations
=> Improving subtract editor

PartPreviewWindow/View3D/Actions/PaintMaterialEditor.cs, PartPreviewWindow/View3D/View3DWidget.cs
=> Accelerated Intersect and Subtract

ApplicationView/PrinterModels.cs, Library/Widgets/InsertionGroup.cs, Library/Widgets/ListView/ListView.cs, Library/Widgets/PrintLibraryWidget.cs, PartPreviewWindow/View3D/DragDropLoadProgress.cs, PartPreviewWindow/View3D/InteractionLayer.cs, PartPreviewWindow/View3D/SceneActions.cs, PartPreviewWindow/View3D/SideBar/MirrorControls.cs, PartPreviewWindow/View3D/UndoCommands/DeleteUndoCommand.cs, PartPreviewWindow/View3D/UndoCommands/InsertCommand.cs, PartPreviewWindow/View3D/UndoCommands/UngroupCommand.cs, PartPreviewWindow/View3D/View3DWidget.cs, Tests/MatterControl.AutomationTests/PartPreviewTests.cs, Utilities/InspectForm.cs
Made insertion group center on bed if not dragging
Put names into mirror buttons
Working on new mirror test
Refactoring
=> Put invalidate on IObject3D

History/PrintHistoryListItem.cs, Library/Widgets/ListView/IListContentView.cs, Library/Widgets/ListView/IconListView.cs, Library/Widgets/ListView/ListView.cs, Library/Widgets/ListView/RowListView.cs, Library/Widgets/PrintLibraryWidget.cs
- MatterHackers/MCCentral#2130
ListView item counts change as reflow occurs
- MatterHackers/MCCentral#2128
Switching listview modes results in empty list
=> Restore ListView mode switching, fix missing list items

StaticData/SliceSettings/Properties.json
- Issue MatterHackers/MatterControl#2445
Validate Layer Height Description
=> Fix validate_layer_height help text

History/PrintHistoryData.cs, PartPreviewWindow/View3D/PrinterActionsBar.cs, PrinterCommunication/Io/PauseHandlingStream.cs, PrinterCommunication/Io/PrintRecoveryStream.cs, PrinterCommunication/PrinterConnection.cs, Tests/MatterControl.AutomationTests/PrintingTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
=> Made an automation test for print recovery (made it pass)

.yaspellerrc, CustomWidgets/EditableNumberDisplay.cs, PrinterCommunication/PrinterConnection.cs, PrinterControls/ControlWidgets/FanControls.cs, StaticData/SliceSettings/Properties.json, StaticData/Translations/Master.txt
Made all values round trip without changing
Made sure we can't get into an update fan loop
Made printer connection hold the speed as a double but send as an int
Made sure the starting display value of EditableNumberDisplay is correct
=> Made FanControls values go from 0-100

ApplicationView/ApplicationController.cs, PartPreviewWindow/View3D/Actions/IntersectionEditor.cs, PartPreviewWindow/View3D/Actions/SubtractEditor.cs, TextCreator/Text/TextGenerator.cs
Only showing working operations in release.
Improved intersection editor
=> Improved subtract editor

ApplicationView/ApplicationController.cs, ApplicationView/WidescreenPanel.cs
=> user 64 bit if available

ApplicationView/ApplicationController.cs, CustomWidgets/LibrarySelector/FolderBreadCrumbWidget.cs, Library/ContentProviders/MeshContentProvider.cs, Library/Widgets/PrintLibraryWidget.cs, MatterControl.csproj, SettingsManagement/ApplicationSettings.cs
Load 64 bit matter slice in debug
Build ray trace thumbnails in 64 bit always
=> Put in loading of OBJ files

ApplicationView/ThemeConfig.cs, ApplicationView/WidescreenPanel.cs, Library/Widgets/ListView/IconListView.cs, Library/Widgets/PrintLibraryWidget.cs, MatterControl.csproj, PartPreviewWindow/GCode2DWidget.cs, PartPreviewWindow/MainTab.cs, PartPreviewWindow/NewTabButton.cs, PartPreviewWindow/PartPreviewContent.cs, PartPreviewWindow/PartTabPage.cs, PartPreviewWindow/PlusTabPage.cs, PartPreviewWindow/PrinterTabPage.cs, PartPreviewWindow/Toolbar.cs, PartPreviewWindow/View3D/SlicePopupMenu.cs
- Add tab close
- Show new tab on + tab button click
- Revise Close icon - only show circle on hover
- Add micro-thumbnails for sidebar prototype
- Issue MatterHackers/MCCentral#2243
Revise main tabs
- Issue MatterHackers/MCCentral#2242
Can't switch back from GCode2D view as all controls are lost
=> Revised Tabs

ApplicationView/ApplicationController.cs, SlicerConfiguration/Slicer.cs, Tests/MatterControl.AutomationTests/LibraryContainerTests.cs
- Issue MatterHackers/MCCentral#2256
Investigate 32 failing tests
=> Use passed into file paths

Tests/MatterControl.AutomationTests/LibraryActionTests.cs, Tests/MatterControl.Tests/MatterControl/PrinterConfigurationTests.cs
- Issue MatterHackers/MCCentral#2257
Convert FixNeeded and WorkInProgress test categories into Ignore attributes
=> Covert disabled test filter categories to Ignore attributes

Library/Widgets/ListView/PrintItemAction.cs, Library/Widgets/PrintLibraryWidget.cs
- Issue MatterHackers/MCCentral#2265
Edit button doesn't appear to work in Root
=> Disable menu items in non-writable containers

CustomWidgets/SimpleButton.cs, PartPreviewWindow/SelectedObjectPanel.cs
- Issue MatterHackers/MCCentral#2264
Finish up Edit feature
=> Disabled Edit on IObject3D lacking children

ApplicationView/PrinterModels.cs, PartPreviewWindow/View3D/BedMeshGenerator.cs, PartPreviewWindow/View3D/MeshViewerWidget.cs
=> Made objects off bed show as transparent

PartPreviewWindow/View3D/MeshViewerWidget.cs
Issue: MatterHackers/MCCentral#2278
Ensure InsideBedVolume works on circular beds
=> Make sure we check for on bed in circular beds.

ApplicationView/PrinterModels.cs, PartPreviewWindow/GCode2DWidget.cs, PartPreviewWindow/PopupMenu.cs, PartPreviewWindow/PrinterTabPage.cs, PartPreviewWindow/View3D/View3DWidget.cs
- Issue MatterHackers/MCCentral#2272
3D layer view uses old menu format
=> Convert GCode menu to new format

SlicerConfiguration/SliceSettingsWidget.cs
addresses: MatterHackers/MCCentral#2311
Need a bit of right margin
=> Added a bit of right margin

ApplicationView/ThemeConfig.cs, PartPreviewWindow/GCode3DWidget.cs, PartPreviewWindow/View3D/View3DWidget.cs
- Issue MatterHackers/MCCentral#2308
Overlays have inconsistent readability due to transparency
=> Use more opaque background colors on scene overlays

PartPreviewWindow/MainTab.cs
- Issue MatterHackers/MCCentral#2331
Agg draws ghosted lines along paths resulting in unexpected tab edges
=> Fix tab rendering

PartPreviewWindow/PartTabPage.cs, PartPreviewWindow/View3D/View3DWidget.cs, PartPreviewWindow/ViewControls3D.cs
This will eventually be removed when the tumble control is done
=> Make sure we can switch to part select in touchscreen mode

PrinterCommunication/Io/ProcessWriteRegExStream.cs, PrinterCommunication/PrinterConnection.cs
Make regex stream connected to printer
=> Make sure we process every line through write filters

ApplicationView/ApplicationController.cs, ApplicationView/PrinterModels.cs, ApplicationView/ThemeConfig.cs, CustomWidgets/NamedAction.cs, Library/Providers/FileSystem/SceneReplacementFileItem.cs, Library/Providers/MatterControl/PlatingHistoryContainer.cs, Library/Widgets/PrintLibraryWidget.cs, MatterControl.csproj, PartPreviewWindow/GCode2DWidget.cs, PartPreviewWindow/PartPreviewContent.cs, PartPreviewWindow/PlusTab/PlusTabPage.cs, PartPreviewWindow/PrinterTabPage.cs, PartPreviewWindow/SelectedObjectPanel.cs, PartPreviewWindow/SliceLayerSelector.cs, PartPreviewWindow/View3D/InteractionLayer.cs, PartPreviewWindow/View3D/MeshViewerWidget.cs, PartPreviewWindow/View3D/PrinterActionsBar.cs, PartPreviewWindow/View3D/View3DWidget.cs, PartPreviewWindow/ViewControls3D.cs
- Issue MatterHackers/MCCentral#1776
Drag gcode to scene or Selection -> GCode -> Print
=> Drag gcode/plating history to scene

Library/Widgets/PrintLibraryWidget.cs
- Issue MatterHackers/MCCentral#2350
Investigate 12 failing tests
=> "Add to plate" should be bound to scene content not printer

PartPreviewWindow/View3D/BedMeshGenerator.cs, PartPreviewWindow/View3D/TumbleCubeControl.cs, SlicerConfiguration/UIFields/Vector2Field.cs
Made tumble cube invalidate while rotating
Vector2 slice edit type needs to be able to be negative (couldn't figure out how to make test)
issue: MatterHackers/MCCentral#2353
Draw the coordinate system on circular beds in the actual wold position
=> Made circular bed draw axis correctly

ConfigurationPage/PrintLeveling/LevelWizardMesh.cs
issue: MatterHackers/MatterControl#2448
3x3 mesh leveling issue
=> show the correct number of steps in 3x3 leveling wizard

PartPreviewWindow/View3D/SceneActions.cs
issue: MatterHackers/MCCentral#2364
Make Copy part maintain the height it was at
=> Make duplicate maintain object height and position

Community.CsharpSqlite/Community.CsharpSqlite.csproj, ConfigurationPage/PrintLeveling/LevelWizard7PointRadial.cs, ConfigurationPage/PrintLeveling/LevelWizardMesh.cs, PartPreviewWindow/View3D/TumbleCubeControl.cs, StaticData/Translations/Master.txt
=> Improving ray tracing so we can click tumble widget

ApplicationView/ApplicationController.cs, Library/Providers/FileSystem/FileSystemContainer.cs, Library/Widgets/InsertionGroup.cs, PartPreviewWindow/View3D/Actions/MeshWrapperOperation.cs, PartPreviewWindow/View3D/Actions/PaintMaterialEditor.cs, PartPreviewWindow/View3D/SceneActions.cs, PartPreviewWindow/ViewControls3D.cs, PrinterControls/PrinterConnections/SetupStepMakeModelName.cs, SlicerConfiguration/Settings/ProfileManager.cs, SlicerConfiguration/SlicePresetsWindow/SlicePresetsWindow.cs
Improve it to check for and replace numbers
add new calling method
Make sure Object3D Close does not end up modifying object in processes
Don't try to render meshes with no faces
=> Unify to single GetNonCollidingName

PartPreviewWindow/View3D/UndoCommands/ChangeColor.cs, PartPreviewWindow/View3D/UndoCommands/MakeSupport.cs
issue: MatterHackers/MCCentral#2386
Can't change the color on text object
=> Check for selection correctly.

PartPreviewWindow/PlusTab/ExploreItem.cs, PartPreviewWindow/PlusTab/ExplorePanel.cs, PartPreviewWindow/PlusTab/PlusTabPage.cs, PartPreviewWindow/View3D/Actions/PaintMaterialEditor.cs, PartPreviewWindow/View3D/Actions/SubtractEditor.cs
Respect OEM store setting
Fixed link on + tab
=> Make sure we update the view as we subtract

ApplicationView/MainApplicationWidget.cs, ApplicationView/ThemeConfig.cs, ConfigurationPage/PrintLeveling/InstructionsPage.cs, ControlElements/StyledMessageBoxWindow.cs, CustomWidgets/WizardControl.cs, MatterControlApplication.cs, PartPreviewWindow/SliceLayerSelector.cs, PrinterControls/ControlWidgets/AdjustmentControls.cs, SetupWizard/DialogPage.cs
- Issue MatterHackers/MCCentral#2334
Create folder is not open to right size
=> Remove extra scaling, special styling, for touchscreen

ApplicationView/MainApplicationWidget.cs, PartPreviewWindow/View3D/Actions/PaintMaterialEditor.cs, PartPreviewWindow/View3D/Actions/SubtractEditor.cs, PartPreviewWindow/View3D/SliceProgressReporter.cs, SettingsManagement/OemSettings.cs, SetupWizard/SyncingPrintersPage.cs
=> Adding some progress reporting to subtract

PartPreviewWindow/RunningTaskRow.cs, PartPreviewWindow/RunningTasksWidget.cs, PartPreviewWindow/View3D/PrinterBar/PrintPopupMenu.cs, Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs, Tests/MatterControl.AutomationTests/PrinterDropDownTests.cs, Tests/MatterControl.AutomationTests/PrintingTests.cs, Tests/MatterControl.AutomationTests/SliceSettingsTests.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
- Issue MatterHackers/MCCentral#2414
Investigate test failures
=> Fix failing tests

ControlElements/TextImageButtonFactory.cs, CustomWidgets/PrintingWindow/PrintingWindow.cs, PartPreviewWindow/View3D/SceneActions.cs
Deleting dead code around InverImageLocation
issue: MatterHackers/MCCentral#2432
Copy does not work if more than one item selected
=> Fixed copy to work with groups and multi select

PartPreviewWindow/View3D/UndoCommands/GroupCommand.cs, Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
issue: MatterHackers/MCCentral#2451
Investigate if ValidateDoUndoOnSceneOperations failure is related to recent selection changes
=> Fixed group test.

PartPreviewWindow/View3D/UndoCommands/InsertCommand.cs, PartPreviewWindow/View3D/View3DWidget.cs
=> Remove selection on delete on selected object

PartPreviewWindow/View3D/SliceProgressReporter.cs
- Issue MatterHackers/MCCentral#2442
Add current layer info back into progress label during slicing
=> Revise SliceProgressReporter

Library/Providers/FileSystem/FileSystemContainer.cs
- Issue MatterHackers/MCCentral#2455
Search not functioning in Downloads folder
=> FileSystemContainers need to .Load and fire .ContainerChanged on filter
