MatterHackers/MatterControl

PrinterControls/PrinterConnections/EditConnectionWidget.cs

Fixes [Suppress 'Auto Connect' checkbox on android](https://www.pivotaltracker.com/story/show/86664638)

Conditionally display AutoConnect on printer edit form - Fixes #86664638

---

ConfigurationPage/ApplicationSettings/ApplicationSettingsView.cs
LocalizedString.cs

An initial technique for enabling the "Restart" functionality on Android. The approach works by allowing callers to clear the current translation map, and on Android we clear the loaded translation map, remove all children from the MatterControlApplication object and then hard-code the init of a new CompactApplicationView. We discussed using ReloadAll but it's currently hard-coded for PC classes and the technique isn't the same as the approach below.
Next iteration might be to tackle ReloadAll approach?

Revise "Language Options" -> Restart implementation - Fixes #85629286

---

PrinterControls/PrinterConnections/PrinterListItems.cs

- Fixes [Crash due to stale state after active/connected printer is removed](https://www.pivotaltracker.com/story/show/87154858)

Ensure active connected printer is disabled if removed - Fixes #87154858

---

PrinterCommunication/PrinterConnectionAndCommunication.cs
PrinterControls/PrinterConnections/EditConnectionWidget.cs

- don't unnecessarily filter 002/002
Missed sending a pull for this yesterday

Account for FrostedSerialPort.GetPortNames() having zero items

---

Utilities/ProjectFileHandler.cs

Started to put in a call to Dispose on the FileStream but WriteAllText is really intended for this pattern and seemed like a better updated
Further, on Mac the .CreateFromDirectory call throws an exception if the file exists but strangely it does not bubble and is silently suppressed like the thread is aborted. Looking forward to another set of eyes on the problem.

Revise export to zip

---

PrinterControls/PrinterConnections/BaseConnectionWidget.cs
PrinterControls/PrinterConnections/EditConnectionWidget.cs
PrinterControls/PrinterConnections/SetupStepComPortManual.cs

- Add filtering on Linux builds; ignore ttyS*\d+ devices
- Move control creation and filtering logic to base class to share across Add/Edit forms
- Reduce calls to .GetPortNames()

Revise serial port filtering

---

PrintQueue/PrintItemWrapper.cs

Resetting the Id property ensures that the queuedata item persisted to default.mcp loses its association with the removed db row. This ensures that future operations that determine if insert or update queries will be executed, see a (x.Id == 0) condition and perform the needed insert operation

Reset PrintItem.Id after dropping db row - Fixes #95812886

---

AboutPage/AboutWidget.cs
History/PrintHistoryData.cs
Library/Provider/LibraryProvider.cs
Library/Provider/LibraryProviderHistory.cs
Library/Provider/LibraryProviderQueue.cs
Library/Provider/LibraryProviderSqlite.cs
PartPreviewWindow/View3D/View3DWidget.cs
PrinterControls/PrinterConnections/PrinterSetupStatus.cs
PrinterControls/PrinterConnections/SetupStepMakeModelName.cs
Utilities/ManifestFileHandler.cs
Utilities/ProjectFileHandler.cs

- Prevent accidental construction of ProviderSQLite objects inside of ProviderSQLite constructor
- Initialize .baseLibraryCollection during rootLibraryCollection construction to prevent null reference errors
caused by access before assignment
- Remove AddItem -> AddStlOrGcode -> AddItem recursion - Fixes crash due to concurrent writes to default.mcp
- Add sqlite async methods and supporting logic to ensure disk IO operations aren’t run in parallel
- Consolidate logic around sample part extraction from StaticData from various areas into a single method
- Rename that method from SyncCalibrationFilesToDisk to EnsureSamplePartsExist
- Break apart the large LINQ query into discrete and easier to understand steps
- Add shared base class for sqlite backed library providers and resuse common code …

Restore ability to attach VS to Android via debugger

---

CustomWidgets/LibrarySelector/LibrarySelectorWidget.cs
Library/LibraryDataView.cs
Library/Provider/LibraryProviderSelector.cs
StaticData/Translations/Master.txt

- Add LibraryRootNotice event
- Hook LibraryRootNotice into new Socketeer LibraryRootNotice DeviceEvent
- Listen for LibraryRootNotice in LibraryProviderSelector and call ReloadData to ping ProviderFactories for visibility
- Refactor LibraryProviderSharedPlugin for clarity
- Refactor LibraryProviderSharedPlugin to support refreshing visibility logic after ShouldBeShown() calls
- Revise AcquireCollectionData() to use 'internal' access modifier for reuse in LibraryProviderSharedPlugin
- Ensure the input field on CloudShareRedeemForm is focused by default, make buttons available to test automation
- Add new test for 'Shared with Me' folder visibility
- Update existing Purchased folder test to look for revised item name
- Replace magic 'ProviderSelectorKey' token with static member for …

Refresh root library view as needed

---

DataStorage/Datastore.cs
MatterControlApplication.cs
StaticData/SliceSettings/Properties.json
Tests/MatterControl.AutomationTests/OptionsTabTests.cs
Tests/MatterControl.AutomationTests/PrintQueueTests.cs
Tests/MatterControl.AutomationTests/SqLiteLibraryProvider.cs
Tests/MatterControl.Tests/MatterControl/LibraryProviderSqliteTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

- Revise skirt_distance label per support team
- Remove CreateInstance(showWindow) out variable
- Remove embedded tools requiring showWindow out variable
- Remove queueItemFolderToAdd variable/parameter
- Change AfterFirstDraw event to null conditional invoke
- Removed unused AutomationTest from MatterControlApplication
- Refactor for style consistency and document new methods
- Change queueItemFolderToAdd type to custom enum to ensure optional parameters are not mixed up
- Ensure TestExportZip file is deleted before attempting export

Automation updates

---

Library/LibraryRowItemPart.cs
Library/Provider/LibraryProviderFileSystem.cs
Library/Provider/LibraryProviderSelector.cs
PartPreviewWindow/View3D/View3DWidget.cs
Queue/PrintItemWrapper.cs

- Fixes #111237022 - Unable to save any changes to CloudLibrary items
- Add useIncrementedNameDuringTypeChange to PrintItemWrapper to control naming behavior
- Pass useIncrementedName value though from provider factory all the way to PrintItemWrapper
- Prevent duplicate calls to GetPrintItemWrapperAsync within the same callstack i.e. pass instance through
- Only rename files when switching to AMF and use different logic for different provider types
- Add path helper methods to PrintItemWrapper for clarity and conciseness in callers

Restore CloudLibrary save functionality, revise convert to AMF behavior

---

PartPreviewWindow/View3D/UndoCommands/GroupCommand.cs
PartPreviewWindow/View3D/UndoCommands/UngroupCommand.cs
PartPreviewWindow/View3D/View3DWidget.cs
Tests/MatterControl.AutomationTests/PartPreviewTests.cs

- Troubleshoot and fix broken GroupAndUngroup test
- Troubleshooting reveals Group command is adding items as a tree
- Group command should and now does flatten selection when applied
- Reuse new AddToSelection logic in view3DWidget mouse code
- Migrate CollapseObjectIntoScene to IObject3D CollapseInto ext. method

PartPreview tests working again

---

ApplicationView/MenuRow/MenuOptionSettings.cs
History/PrintHistoryDataView.cs
PartPreviewWindow/View3D/View3DWidget.cs
SlicerConfiguration/SlicePresetsWindow/SlicePresetDetailWidget.cs

- Observed exception on shutdown where PrintHistory was reloaded during
shutdown after the db had been closed. Skip load if Closing/closed
- Spelling, whitespace, use .Localize()

Guard LoadHistoryItems with WidgetHasBeenClosed

---

PartPreviewWindow/View3D/SideBar/View3DWidgetSidebar.cs
PartPreviewWindow/View3D/View3DWidget.cs
TextCreator/SidebarPlugins/TextCreatorsSidebar.cs

- Text creators need to return unflattened Object3Ds
- Sidebar.CreateAddButton should flatten for icons as needed
- Guard for null reference error on non-mesh items

Ensure text creators keep their derived type and hierarchy

---

PrinterCommunication/Io/WaitForTempStream.cs

This will continue the print if the bed temp is already above the target. This was preventing prints from finishing on the Mini, which has an M190 S0 in the end gcode.
We should also consider taking the R parameter for M190, which would make it work the other way.
http://reprap.org/wiki/G-code#M190:_Wait_for_bed_temperature_to_reach_target_temp

Make M190 work the same way as in Marlin

---

PartPreviewWindow/View3D/View3DWidget.cs

- Fix bug with saving where every instance became a new mesh on disk
- Save embedded assets into library/assets with <sha1>.stl file
- Ensure instanced files all point at the same asset
- Remove persistent item cache, only cache assets during file load
- Add ComputeSHA functionality to MeshFileIO
- Add custom hashing function to Mesh.cs, do not override GetHashCode
until additional validation and testing are completed

Fix file duplication with instanced copies, revise load caching

---

PartPreviewWindow/View3D/View3DWidget.cs
Queue/QueueDataView.cs
Queue/QueueDataWidget.cs

- Improves responsiveness & suppress unexpected dragdrop during scroll
- Only suppress queue scroll events during queue item dragdrop
- Prevent null reference error when unsubscribing progress draw hook

Prevent setting DragDropSource on scrollbar mouse events

---

ActionBar/PrinterSelector.cs
DataStorage/Classic/ClassicSqlitePrinterProfiles.cs
PrinterCommunication/PrinterConnectionAndCommunication.cs
PrinterControls/PrinterConnections/BaseConnectionWidget.cs
PrinterControls/PrinterConnections/SetupConnectionWidgetBase.cs
SlicerConfiguration/Settings/ActiveSliceSettings.cs
SlicerConfiguration/Settings/LayeredProfile.cs
SlicerConfiguration/Settings/SettingsProfile.cs
SlicerConfiguration/SettingsControlSelectors.cs
SlicerConfiguration/SlicePresetsWindow/SlicePresetsWindow.cs
SlicerConfiguration/SliceSettingsWidget.cs

- Fixes #720 - Changing preset names has no effect
- Fixes #767 - Presets editor contains user overrides
- Fixes #768 - Oem presets should be copied...
- Migrate from int to string based printer IDs
- Add json document migration capabilities

Add support for renaming and duplicating presets

---

SlicerConfiguration/SettingsControlSelectors.cs
SlicerConfiguration/SlicePresetsWindow/SlicePresetsWindow.cs

- Update Material preset array when preset changed from presets window
- Update PresetsContext.PersistenceLayer when presets are duplicated
- Rebuild SliceSettingsWidget on duplicate without leaving window
- Refactor GetTopRow to eliminate excess widgets & create a single row
- Update presets name after leaving input rather than on window close

Improve Duplicate preset

---

SlicerConfiguration/Settings/ActiveSliceSettings.cs

- Fixes #714 
- UrlEncode values

Pass make/model as querystring parameters on printer lookup requests

---

SlicerConfiguration/SliceSettingsWidget.cs

- Settings delimiter must be lowercase 'x'

Revert breaking changes in b78dadd25c89186ad7f (UI label updates)

---

ActionBar/PrinterActionRow.cs
ActionBar/PrinterSelector.cs
SlicerConfiguration/Settings/ActiveSliceSettings.cs

- Add Rebuild method to PrinterSelector
- Hook settings change in PrinterSelector and rebuild on name change
- Issues #880, #894
- Use initializer syntax

Rebuild PrinterSelector data on printer name changed

---

StaticData/SliceSettings/Properties.json

Help text for Air gap was the same for both air gaps. Fixed verbiage for support material.

Fixing incorrect help text.

---

SlicerConfiguration/Settings/LayeredProfile.cs
SlicerConfiguration/Settings/ProfileManager.cs
SlicerConfiguration/Settings/SettingsProfile.cs
SlicerConfiguration/SettingsControlSelectors.cs

- Ensure that only profiles known to ProfileManager can be loaded by ID
- Ensure ActiveProfileID is cleared on delete printer
- Remove ActiveMaterialKey duplication, use MaterialSettingsKeys[n]

Fix Profile selection issues

---

DataStorage/Classic/ClassicSqlitePrinterProfiles.cs
MatterControl.csproj
SlicerConfiguration/Settings/LayeredProfile.cs
SlicerConfiguration/Settings/PrinterSettingsLayer.cs
SlicerConfiguration/Settings/ProfileManager.cs
SlicerConfiguration/Settings/ProfileMigrations.cs
SlicerConfiguration/Settings/SettingsProfile.cs
Tests/MatterControl.Tests/MatterControl/ConfigIniTests.cs

- Extract PrinterSettingLayer to separate file
- Create profile migration for OemProfile -> OemLayer
- Rename confusing LayerCascade property in tests to PrinterSettings
- Issue #1023

Remove OemProfile property, promote OemLayer property to parent

---

SettingsManagement/OemSettings.cs
SlicerConfiguration/Settings/ProfileManager.cs

When creating a printer checks if profile is already on disk before downloading

Async download of profiles not in cache

---

ApplicationView/AdvancedControlsPanel.cs
ApplicationView/MainApplicationWidget.cs
MatterControlApplication.cs
SlicerConfiguration/Settings/ProfileManager.cs
SlicerConfiguration/Settings/ProfileMigrations.cs

Sync is now call on start up before deciding to launch create printer window
Fixed bug where upload printer dialog would launch when there were no printers to upload
Fixed bug where incorrect profile extensions were used

Sync on start up

---

SlicerConfiguration/Settings/PrinterSettings.cs

Serializing Printer setting now Ignores Helpers and PrinterSelected

Printer Settings defaults DocumentVersion to the lastest

---

Tests/MatterControl.Tests/MatterControl/SetupIniTests.cs

Note: These tests should probably be removed as the reason for these tests are now natively supported by our profile schema.

Setupini test now run against .printer files

---

SettingsManagement/OemSettings.cs
SlicerConfiguration/Settings/PrinterSettings.cs
SlicerConfiguration/Settings/ProfileManager.cs
Tests/MatterControl.AutomationTests/RetrievePublicProfileTest.cs
VersionManagement/RetrievePublicProfileRequest.cs

Updated to test to reflect the actions actually done by the request (not sure why they were not failing before)

converted oemprofiles to be .printer files and to be retrieved as such from various locations.

---

MatterControlApplication.cs
SettingsManagement/OemSettings.cs
SlicerConfiguration/Settings/ProfileManager.cs

This reduced loading time for public profiles from 5200-5300ms to 2ms
Loadcacheable can now fall back to Static data if passed a path for it

Load public profiles from Static Data before launching request to webserver in new task

---

PrinterControls/XYZJogControls.cs

Now we change them back to 1 when not printing.

Don't leave the movement controls on .02 when not printing.

---

SettingsManagement/OemSettings.cs

- Removed ReloadOemProfiles form on load (ReloadOemProfiles is called in sync and sync is called on start up so two calls were going out at once)
- DownloadMissingProfiles is no longer a separate task so that we don't resync and try to run a second download of missing profiles

Fixed bug where would try to write to a OemProfile Twice throwing an exception

---

ApplicationView/MainApplicationWidget.cs
SetupWizard/PrinterProfileHistoryPage.cs
SlicerConfiguration/Settings/ActiveSliceSettings.cs
SlicerConfiguration/Settings/PrinterSettings.cs

- Persistence of profile moves to caller
- Rename to GetPrinterProfileAsync
- Expose PrinterSettings.Save for use in external assemblies
- Issue MatterHackers/MCCentral#227,  MatterHackers/MCCentral#242

DownloadPrinterProfile should return an instance of PrinterSettings

---

SetupWizard/ImportSettingsPage.cs
SlicerConfiguration/Settings/PrinterSettings.cs
SlicerConfiguration/Settings/ProfileManager.cs
StaticData/Translations/Master.txt

- ImportFomEisting now returns a bool of whether or not it succeeded
- PrinterSettings now has a Contains method
- merging or importing quality/material settings check to make sure at least one setting was importable and notifies user if not

Importing a printer/settings from a file will now  notify the user if the file contains no valid user settings

---

ApplicationView/MenuRow/MenuOptionFile.cs
SetupWizard/ImportSettingsPage.cs
SlicerConfiguration/Settings/ProfileManager.cs

- Import preset no longer checks for slicer and will validate import on weather or not any settigns were valid
- calling Import from MenuOptionFIle will cause the same error message as importing a printer form the settings import page
- Import to new printer now attempts to load values and validates success on importing a valid setting

Fixed import to not rely on layer_height validation

---

ApplicationView/MainApplicationWidget.cs

This action gets set by code that is part of CloudServices and not part of the common code.

Don't call uninitialized action.

---

SlicerConfiguration/Settings/ProfileManager.cs

- Issue MatterHackers/MCCentral#283

Avoid null conditional result on awaited call to workaround Mono error

---

ApplicationView/MainApplicationWidget.cs
SettingsManagement/UserSettings.cs
VersionManagement/WebRequestHandler.cs

- Add UserSettingKeys for CredentialsInvalid, CredentialsInvalidReason
- Move CredentialsInvalid, CredentialsInvalidReason setters into ChangeCloudSyncStatus
- Update method to take string parameter for invalid reason
- Toggle state when Connected value changes
- Clear invalid flag if connected, set invalid flag and reason if not
- Issue MatterHackers/MCCentral#354

Revise ChangeCloudSyncStatus

---

PrinterCommunication/PrinterConnectionAndCommunication.cs
StaticData/SliceSettings/Properties.json

Recover setting shows blue override when used

Improved disconnect behavior

---

ApplicationView/MainApplicationWidget.cs
MatterControl.csproj
SettingsManagement/ApplicationSettings.cs
SetupWizard/AndroidSetupOptionsPage.cs
SlicerConfiguration/Settings/ProfileManager.cs
SlicerConfiguration/SliceSettingsDetailControl.cs
Utilities/AuthenticationData.cs

- Add public const EnvironmentName for Services environment
- Remove GetSessionUsername method
- Remove ClearCachedCredentials
- Pull in AuthData type
- Add system to store and use ClientTokens
- Add using statements for common namespaces
- Issue MatterHackers/MCCentral#488

Revise ClientToken use for multi-instanced MatterControl

---

Tests/MatterControl.AutomationTests/LibraryDownloadsTest.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

- Move all tests into one class
- Only apply RunInApplicationDomain to test
- Add descriptions on AddTestResult calls to improve troubleshooting

Clean up failing LibraryDownload tests

---

PrinterControls/PrinterConnections/SetupStepMakeModelName.cs
SlicerConfiguration/Settings/ProfileManager.cs

- Rename AcquireNewProfile to CreateProfileAsync
- Return status result of CreateProfileAsync
- Abort processing on profile creation failures
- Localize error messsages

Decouple validation logic from save invocation

---

ActionBar/PrinterConnectAndSelectControl.cs
ApplicationView/MainApplicationWidget.cs
ApplicationView/TouchscreenTabView.cs
ApplicationView/WidescreenPanel.cs
CustomWidgets/PopOutTextTab.cs
Library/Provider/LibraryProviderSqlite.cs
SlicerConfiguration/Settings/ProfileManager.cs

- Remove unset ApplicationControler.WidescreenMode variable
- Add local AddTab function to TouchScreenTabView for LazyTab creation
- Use common AddTab function for tab creation in TouchScreenTabView
- Refactor WidescreenPanel for clarity
- Use OnBoundsChanged instead of event
- obj.NumberOfVisiblePanels() becomes obj.VisiblePanelCount
- Fix thumbnail exception experienced by ensuring Directory exists
- Run ActiveSliceSettings.Instance assignment on UI thread if loading
- Prevents extra ReloadAll right at the completion of form Load
- Issue MatterHackers/MCCentral#536

Add LazyTabs for Touchscreen view

---

CustomWidgets/ThemeColorSelectorWidget.cs
MatterControlApplication.cs
SlicerConfiguration/Settings/ActiveSliceSettings.cs

- Setting color for a printer sets value in user settings
- use UserSetting color as default for loading theme color
- if Active slice settings dont have an active theme set it to default
- If user setting  theme is null attempt to load OemColor preference and set as user setting theme

Fix Regression in user color preservation

---

PartPreviewWindow/View3D/View3DWidget.cs

also matterslice fix.
MatterHackers/MatterSlice#133
Wipe tower not generated correctly when using second extruder for support

fixing colors

---

Tests/MatterControl.AutomationTests/MatterControl.AutomationTests.csproj
Tests/MatterControl.Tests/MatterControl/ReleaseBuildTests.cs

- Use the MatterControl output directory in all cases
- Only load assemblies for testing in Release builds
- Use conditional comp. for path resolution
- Issue MatterHackers/MCCentral#550

Prevent false positives when assemblies are missing

---

ApplicationView/MainApplicationWidget.cs
CustomWidgets/ThemeColorSelectorWidget.cs
SlicerConfiguration/Settings/ActiveSliceSettings.cs

-  When both the user and oem settings are unset we now both set the active theme color to be blue and set this as the user default
- Removed redundant null check/fallback.

Fixed color behavior for users with unset default

---

ApplicationView/MainApplicationWidget.cs
DataStorage/Classic/ClassicSqlitePrinterProfiles.cs
SetupWizard/CopyGuestProfilesToUser.cs
SlicerConfiguration/Settings/ActiveSliceSettings.cs
SlicerConfiguration/Settings/ProfileManager.cs
Utilities/AuthenticationData.cs

- Replace DB nomenclatures with ProfilesDoc/Profiles terms
- Convert SetLastProfile() to LastProfileID property
- Remove LoadLastProfileWithoutRecovery function
- Use LoadWithoutRecovery(LastProfileID)
- One caller, far more clear with only one LoadWithout function
- Move safe FileSystem UserName to AuthenticationData, like UserName
- Skip importing guest profiles that are missing PrinterSettings files
- Issue MatterHackers/MCCentral#597

Refactor ProfileManager to prefer isolated instances

---

ApplicationView/MainApplicationWidget.cs
PartPreviewWindow/ViewGcodeWidget.cs
Utilities/AuthenticationData.cs

Don't clear the LastSessionUserName
It should only be used in the name field of the login screen and nowhere else.

Always call UserChanged when ChangeCloudSyncStatus

---

Tests/MatterControl.AutomationTests/CheckBoxInLibraryIsClickable.cs
Tests/MatterControl.AutomationTests/CreateLibraryFolder.cs
Tests/MatterControl.AutomationTests/ExportItemWindowTests.cs
Tests/MatterControl.AutomationTests/FileMenuTest.cs
Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs
Tests/MatterControl.AutomationTests/LibraryDownloadsTest.cs
Tests/MatterControl.AutomationTests/LocalLibraryTests.cs
Tests/MatterControl.AutomationTests/MatterControl.AutomationTests.csproj
Tests/MatterControl.AutomationTests/OptionsTabTests.cs
Tests/MatterControl.AutomationTests/PartPreviewTests.cs
Tests/MatterControl.AutomationTests/PrintQueueTests.cs
Tests/MatterControl.AutomationTests/PrinterDropDownTests.cs
Tests/MatterControl.AutomationTests/SliceSetingsTests.cs
Tests/MatterControl.AutomationTests/SqLiteLibraryProvider.cs
Tests/MatterControl.AutomationTests/packages.config
Tests/MatterControl.Tests/MatterControl.Tests.csproj
Tests/MatterControl.Tests/MatterControl/LibraryProviderSqliteTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
Tests/MatterControl.Tests/MatterControl/ReleaseBuildTests.cs
Tests/MatterControl.Tests/packages.config

- Remove per test classes
- Migrate RunInApplicationDomain attributes to TextFixture
- Convert from Action<AutomationRunner> to AutomationTest delegate
- Convert testRunner.AddTestResult to Assert.IsTrue
- Remove testRunner.AllTestPassed(n) - use Asserts
- Add return Task.FromResult(0) for non-async test method bodies
- Upgrade NUnit.ApplicationDomain to v10

Revise Agg automation

---

Tests/MatterControl.AutomationTests/PartPreviewTests.cs

- Rename test
- Wait to enter edit mode
- Fix ordering of expected/actual on Assert.AreEqual
- Wait for expected condition rather than fixed duration
- Use .Count instead of .Count()
- Issue MatterHackers/MCCentral#719

Revise CopyButtonMakesCopyOfPart

---

Tests/MatterControl.AutomationTests/SliceSetingsTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

- Add Wait calls after clicks
- After slicing, wait for expected result, up to 10 seconds
- Use utility functions for parsing .ini files
- Refactor AddAdSelectPrinter - remove unused variables, add Waits

Revise failing RaftEnabledPassedToSliceEngine test

---

ApplicationView/TouchscreenTabView.cs

fixes: MatterHackers/MCCentral#748
T7 widget scaling does not match classic product and is no longer valid

Reduce the margin when on small touch screen

---

SlicerConfiguration/Settings/PrinterSettings.cs
SlicerConfiguration/SettingsControlSelectors.cs

- Issue MatterHackers/MCCentral#749

Ensure preset values initially take precedence over user overrides

---

ApplicationView/AdvancedControlsPanel.cs

MatterHackers/MatterControl#1591
Popped out windows close when settings are changed

Don't save close state on reload of settings

---

ActionBar/PrintActionRow.cs

fixes: MatterHackers/MCCentral#756
Touch can show "Add Printer" button when there are printers in the drop down list

Update action row on profile list changes

---

PrinterControls/TerminalWindow/TerminalWindow.cs
SetupWizard/WizardWindow.cs

fixes: MatterHackers/MCCentral#761
Android: printer name field not raising keyboard

Make sure we can raise keyboard on wizard windows

---

ApplicationView/MainApplicationWidget.cs
ConfigurationPage/ApplicationSettings/ApplicationSettingsView.cs

Fixes: MatterHackers/MCCentral#769
Make sure we pre-load the queue and initialize the library selector prior to navigating to it.

Made the queue always populate on touch

---

ApplicationView/MainApplicationWidget.cs

Fixes: MatterHackers/MCCentral#797
Print recovery not working on touch

Make sure we initialize PrintHistoryData for print recovery

---

SlicerConfiguration/Settings/PrinterSettings.cs
SlicerConfiguration/Settings/SettingsHelpers.cs
SlicerConfiguration/SlicerMapping/EngineMappingCura.cs
SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs
SlicerConfiguration/SlicerMapping/MappingClasses.cs
Tests/MatterControl.Tests/MatterControl/PrinterConfigurationTests.cs

- Migrate first_layer_speed to SettingsKey
- Use specialized Asserts to assist in troubleshooting
- Improve failure text to assist in troubleshooting
- Process all layers in .printer files
- Issue MatterHackers/MCCentral#879
Fix PrinterConfigurationTests.PrinterConfigTests

Rewrite PrinterConfigTests to use .printer/PrinterSettings files

---

Queue/QueueData.cs
Queue/QueueDataView.cs

MatterHackers/MCCentral#915
Queue not switching to new part if 'print' ed from the library

Fixed a bug when printing from library with new queue code

---

SlicerConfiguration/SettingsControlSelectors.cs

- Issue MatterHackers/MCCentral#919
Deactivated user overrides are only persisted to disk via manual user edits

Ensure changes are persisted to disk and synced to the cloud

---

Tests/MatterControl.AutomationTests/SqLiteLibraryProvider.cs

- MatterHackers/MCCentral#926
Revise LibraryQueueViewRefreshesOnAddItem to use popout rather than embedded editor

Adjust window width to ensure popout window -> Edit is targeted

---

ActionBar/PrinterSelector.cs
SlicerConfiguration/Settings/ActiveSliceSettings.cs

- Prevent selection changes on "Add New Printer..." menu item
- Prevent ActivePrinterChanged on differing EmptyProfile instances
- Prevent calling SwitchToProfile on PrinterSelector change if already
on instance
- Issue MatterHackers/MCCentral/#943
- Issue MatterHackers/MCCentral#908

Prevent unexpected ActivePrinter changes

---

ApplicationView/MainApplicationWidget.cs
DataStorage/Classic/ClassicSqlitePrinterProfiles.cs
SettingsManagement/UserSettings.cs
SlicerConfiguration/Settings/ActiveSliceSettings.cs
SlicerConfiguration/Settings/PrinterSettings.cs
SlicerConfiguration/Settings/ProfileManager.cs
SlicerConfiguration/Settings/SettingsHelpers.cs

- Use single instance for .EmptyProfile
- Remove ActiveSliceSettings static constructor, rely on ProfileManager
- Remove SettingsKey.active_theme_name and db usage
- Revise LoadUITheme to only load oem or default color theme
- Only assign ActiveSliceSettings.Instance during ProfileManager assign

Improve startup state initialization

---

Tests/MatterControl.AutomationTests/PrintQueueTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

- Use Assert.AreEqual
- Add failure messages
- Extend ClickByName and WaitForName durations
- Restore 500ms waits in NavigateToFolder
- Issue MatterHackers/MCCentral#988

Revise failing queue tests on slow VMs

---

Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

- Failure in ClearingCheckBoxClearsUserOverride due to slow env
- Advanced Menu Item not found
- Wait a few cycles for SettingsAndControls
- Default to new five second wait in ClickByName
- Issue MatterHackers/MCCentral#999
Investigate ClearingCheckBoxClearsUserOverride failure

Revise timings, extend wait before aborting ClickByName

---

ApplicationView/MainApplicationWidget.cs
ControlElements/RegisteredCreators.cs
CustomWidgets/PluginChooserWindow.cs
PartPreviewWindow/ViewGcodeWidget.cs
PrinterControls/EditMacrosWindow.cs
Tests/MatterControl.AutomationTests/SliceSetingsTests.cs
TextCreator/TextCreator.cs

- Use Action instead of EventHandler
- Convert FunctionToCallOnSave to instance member named RefreshMacros
- Remove empty private setter
- Rename functionToLaunchCreator to Show()
- Issue MatterHackers/MCCentral#1118
Add "event" keyword to all public EventHandler fields

Convert public EventHandler fields to events

---

AboutPage/AboutWidget.cs
Library/Provider/LibraryProviderSqlite.cs

- Use streams instead of file paths
- Copy directly from StaticData stream to Library
- Issue MatterHackers/MCCentral#993
IndexOutOfRange exception during initial run of MatterControl Touch

Change EnsureSamplePartsExist to call synchronous .AddItem() signature

---

ApplicationView/MenuRow/MenuOptionFile.cs
SlicerConfiguration/Settings/ProfileManager.cs

- Issue MatterHackers/MCCentral#1267
Null reference exception in LoadCacheable when running automation tests on vanilla MatterControl

Guard for null reference

---

PrinterControls/XYZJogControls.cs

- Fix typo
- Issue MatterHackers/MCCentral#1452
MatterControl Touch crash when Movement tab is clicked

Fix null reference crash on Android

---

Queue/QueueDataView.cs

Fixes: MatterHackers/MatterControl#2008
Clicking "Done" removes the part highlighted in the queue, not necessarily the one that was just printed.

Don't let the selection change while printing.

---

ApplicationView/AdvancedControlsPanel.cs
Library/Widgets/ListView/ListView.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

- Remove unused 'up folder' list view item code

Fix list item names, use DoubleClickByName to automate library items

---

PartPreviewWindow/ViewControls2D.cs
PartPreviewWindow/ViewGcodeBasic.cs
PartPreviewWindow/ViewGcodeWidget.cs

- Refactor ViewControlsToggle
- Remove public accessors to button controls
- Add event for changing modes
- Subscribe to new event
- Collapse named functions into single use callers for clarity
- Issue MatterHackers/MCCentral#1527
2D layer view not appearing after defaulting to 3D layer view

Fix empty Layer2D view

---

ActionBar/PrintActionRow.cs
PartPreviewWindow/View3D/View3DWidget.cs
PrinterCommunication/PrinterConnectionAndCommunication.cs
PrinterEmulator/Emulator.cs
Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs
Tests/MatterControl.AutomationTests/LocalLibraryTests.cs
Tests/MatterControl.AutomationTests/PrinterDropDownTests.cs
Tests/MatterControl.AutomationTests/PrintingTests.cs
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

- Issue MatterHackers/MCCentral#1556
Determine if false constant was accidentally checked in and revert
- Issue MatterHackers/MCCentral#1505
Tests assume 'Start Print' is available but that behavior was coupled with Queue Selection/ActivePrintItem

More tests updated and passing

---

Library/Providers/FileSystem/FileSystemContainer.cs
Library/Providers/FileSystem/FileSystemItem.cs
Library/Providers/MatterControl/SqliteLibraryContainer.cs
Library/Widgets/PrintLibraryWidget.cs
Tests/MatterControl.AutomationTests/LibraryDownloadsTest.cs
Tests/MatterControl.AutomationTests/LocalLibraryTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs
Tests/MatterControl.Tests/MatterControl/PerformanceTests.cs

- RenameButtonRenameLocalLibraryItem test passing
- Get LibrarySelection->Remove action to compile after refactoring
- Make LibraryRenameSelectedItem an extension method and update callers
- Issue MatterHackers/MCCentral#1559
Library Selection -> Rename does nothing
- Issue MatterHackers/MCCentral#1505

Fix LibrarySelection -> Rename

---

ApplicationView/AdvancedControlsPanel.cs
ApplicationView/ApplicationController.cs
ControlElements/SplitButtonFactory.cs
Library/Widgets/ListView/ListViewItemBase.cs
PartPreviewWindow/OverflowDropdown.cs
PartPreviewWindow/ViewControls3D.cs
SlicerConfiguration/Settings/SettingsHelpers.cs
Tests/MatterControl.AutomationTests/PrintingTests.cs
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

- Issue MatterHackers/MCCentral#1565
AdvancedControls tab should remember selected index after ReloadX events
- Issue MatterHackers/MCCentral#1505
Tests assume 'Start Print' is available but that behavior was coupled with Queue Selection/ActivePrintItem

Design tools

---

ApplicationView/ApplicationController.cs
SlicerConfiguration/Settings/ActiveSliceSettings.cs
SlicerConfiguration/Settings/PrinterSettings.cs

- Use event to signal MaterialChanged
- Register MaterialChanged listeners on MatterControl startup
- Issue MatterHackers/MCCentral#1603
Investigate LayerGCodeHasExpectedValue regression

Prevent SliceSettings changes from spinning up MatterControl

---

Library/Widgets/ListContainerBrowser.cs
Library/Widgets/ListView/ListView.cs
Library/Widgets/PrintLibraryWidget.cs
MatterControl.csproj
PartPreviewWindow/SaveAsWindow.cs

- Sidebar should focus on usable scene content
- Container browser should allow changing context of sidebar content
- Filter containers from library sidebar
- Replace breadcrumb bar with new container dropdown
- Add filtering to listview for containers/items
- Add container browser for container bar popup
- Filter library items from container browser
- Filter library items from SaveAs selector window
- Issue MatterHackers/MCCentral#1541
SaveAs window should only show writable locations and should not list container items
- Issue MatterHackers/MCCentral#1767
Content navigation and search

Refine library views for focused tasks

---

ApplicationView/ApplicationController.cs
ApplicationView/WidescreenPanel.cs
DataStorage/Datastore.cs
Library/ContentProviders/MeshContentProvider.cs
Library/Widgets/ListView/ListView.cs
Library/Widgets/ListView/ListViewItemBase.cs
PartPreviewWindow/PlusTabPage.cs
PartPreviewWindow/View3D/MeshViewerWidget.cs
PartPreviewWindow/View3D/View3DWidget.cs
Tests/MatterControl.Tests/SceneTests.cs

- Issue MatterHackers/MCCentral#1793
Restore non-colorized thumbnails per linked issue
- Related to MatterHackers/MCCentral#1775
UI for plating history

Restore the previous bedplate on load, revert to white icons

---

Library/Interfaces/ILibraryContainer.cs
Library/Providers/LibraryContainer.cs
Library/Providers/MatterControl/HistoryContainer.cs
Library/Providers/RootLibraryContainer.cs
Library/Widgets/ListView/ListView.cs

- Construct and switch to container requested view if not active
- MatterHackers/MCCentral#1814
'Already the child of another widget' exception when loading Print History

Specify type rather than instance for default container view widget

---

Queue/OptionsMenu/QueueOptionsMenu.cs
Queue/QueueDataWidget.cs

Fixes error where it is possible to export with invalid slice settings.
In "Layer View" clicking the "Generate" button will verify slice settings and complain if things are wrong. However, in the queue view if "Export", "Export to zip", or "Export to Folder or SD card" is selected, tool verification is not run and can cause the program to crash.
To recreate and crash MatterControl, set "Extruder Count" to 0 and click the "Export" button in the queue view.

Verify ActiveSliceSettings for all export methods

---

ApplicationView/ThemeConfig.cs
TextCreator/Text/TextEditor.cs

- Reduce accessibility of spacingScrollBar
- Ensure scrollbars resize with editor and start with correct bounds
- Issue MatterHackers/MCCentral#2110
TextBuilder Spacing settings do not round trip, are lost on close

Use TextObject.Spacing property

---

CustomWidgets/ExportPrintItemWindow.cs
PrinterCommunication/PrinterConnectionAndCommunication.cs
Queue/QueueDataWidget.cs

This is a fix to my pull request, #2566. The fix issued before would complain about invalid slice settings if a gcode file was opened and printed. AMF's and STL's can also now be exported while invalid slice settings are selected. Slice settings are validated only when generating and/or exporting gcode.

Only verify ActiveSliceSettings when exporting/generating gcode

---

PartPreviewWindow/PartTabPage.cs
PartPreviewWindow/ViewControls3D.cs

- Issue MatterHackers/MCCentral#2211
Scene operations (subtract, intersect) do not work in Part view

Scene actions should be bound to their context, not to ActivePrinter

---

SlicerConfiguration/SliceSettingsWidget.cs
SlicerConfiguration/UIFields/ExtruderOffsetField.cs

issue: MatterHackers/MCCentral#2292
Put wrapping text back in for settings lable

Turned settings name wrapping back on

---

PartPreviewWindow/PrinterTabPage.cs

- Issue MatterHackers/MCCentral#2289
Can't switch from 2D Gcode view to 3D Model view

Always hide GCode2D when switching to model view

---

StaticData/SliceSettings/Properties.json

issue: MatterHackers/MCCentral#2224
Make turning off raft disable related settings (like support)

Make raft settings disable when not enabled

---

SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs
SlicerConfiguration/SlicerMapping/MappingClasses.cs

issue: MatterHackers/MCCentral#2457
Infill overlap of 0 results in 100% nozzle diameter

Make infill overlap take a 0

---

CustomWidgets/PrintingWindow/ProgressDial.cs

issue: MatterHackers/MCCentral#2463
Lock max print progress to 99% until done

Don't let print progress report 100% until the print is done.

---

PartPreviewWindow/PrinterTabPage.cs
Tests/MatterControl.AutomationTests/MatterControlTests.cs

- Add test for expected overflow menus
- Issue MatterHackers/MCCentral#2489
GCode2D shows mesh/model overflow menu

Restore correct GCode2D overflow menu

---

ApplicationView/ApplicationController.cs
ApplicationView/PrinterModels.cs
CustomWidgets/ExportPrintItemPage.cs

issue: MatterHackers/MCCentral#1933
2.0: Exporting does not maintain model name

Update the default name we use to save the workspace

---

ActionBar/TemperatureWidgetExtruder.cs
ConfigurationPage/PrintLeveling/PrintLevelPages.cs
ConfigurationPage/RunningMacroPage.cs
PrinterEmulator/Emulator.cs
PrinterEmulator/EmulatorPortFactory.cs
PrinterEmulator/Heater.cs
PrinterEmulator/PrinterEmulator.csproj
SlicerConfiguration/PresetSelectorWidget.cs
SlicerConfiguration/PresetsToolbar.cs
SlicerConfiguration/Settings/PrinterSettings.cs
SlicerConfiguration/Settings/SettingsHelpers.cs
StaticData/SliceSettings/Properties.json
Tests/MatterControl.AutomationTests/PrintingTests.cs
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs
Tests/MatterControl.Tests/MatterControl/OemProfileTests.cs

Removed ability to set material for extruders other than the first
added settings for extruder 1-4 temp
Refactored emulator (move classes to new files)
Made the emulator support multiple extruders
More on: MatterHackers/MCCentral#2593
Temperature control widget doesn't pull changed values from settings

Extruders beyond 0 only have temperature

---

PartPreviewWindow/View3D/Gui3D/MoveInZControl.cs
PartPreviewWindow/View3D/SideBar/ScaleControl.cs

Better display of z height info (show extra decimal when required)
issue: MatterHackers/MCCentral#2592
Scale control not keeping part on bed

Hold bottom height on scale

---

PartPreviewWindow/SectionWidget.cs

issue: MatterHackers/MCCentral#2635
Initial opening of closed settings groups has wrong height

Put in a hack to make the size get recalculated.

---

PartPreviewWindow/AlignControls.cs

issue: MatterHackers/MCCentral#2631
Align should be disabled unless more than one object selected

Disable align buttons if less than 2 items selected.

---

ActionBar/TemperatureWidgetExtruder.cs
MatterControl.csproj
PrinterControls/ControlWidgets/MacroControls.cs
PrinterControls/MacroDetailPage.cs
SlicerConfiguration/Settings/GCodeMacro.cs
SlicerConfiguration/Settings/PrinterSettings.cs
SlicerConfiguration/SlicerMapping/MappingClasses.cs
SlicerConfiguration/SlicerMapping/SliceEngineMapping.cs
StaticData/SliceSettings/Layouts.txt
StaticData/SliceSettings/Properties.json
StaticData/SliceSettings/load_filament.txt
StaticData/SliceSettings/unload_filament.txt

Took out macro location option
Added load and unload macros to StaticData
issue: MatterHackers/MCCentral#2690
Make load and unload filament available on every extruder and create settings to allow printer specific config
MatterHackers/MCCentral#2679
Macros marked for Action menu have no home in design_tools

Made load and unload intrinsic to all printers and extruders

---

PrinterCommunication/Io/MacroProcessingStream.cs

issue: MatterHackers/MCCentral#2681
Load filament priming timeout not always honored

Make sure we always stop when the time out happens on macros

---

ConfigurationPage/PrintLeveling/LevelingStrings.cs
ConfigurationPage/PrintLeveling/PrintLevelPages.cs
PrinterCommunication/PrinterConnection.cs

issue: MatterHackers/MCCentral#2720
Heaters stay on until user interaction at the conclusion of automated probing

Turn off heat when on last page of leveling

---

PartPreviewWindow/Tabs.cs

issue: MatterHackers/MCCentral#2716
Clicking "X" on tab closes MC without prompting

Ask if printing on a printer tab before closing

---

ApplicationView/ApplicationController.cs
RootSystemWindow.cs
SlicerConfiguration/Slicer.cs

Have MS write in the gcode finished string rather than MC
issue: MatterHackers/MCCentral#2397
MatterSlice seems to leave gcode stream open after MatterControl has closed

Make sure we kill the slicing task when we exit

---

Library/Provider/LibraryProviderFileSystem.cs

When opening a subfolder in a custom library, the folder name had
a leading slash. Path.combine treats this as a root folder and the first
argument is discarded. This leads to an exception further down the line.
Removing the leading slash fixes that.

Fixed bug when opening subfolders in custom library.

---

MatterControl.Printing/GCode/GCodeFile.cs

issue: MatterHackers/MCCentral#2774
Increasing Jerk Velocity above 100 mm/s causes print time estimate to increase

Improved the math around gcode time and jerk setting

---

ConfigurationPage/PrintLeveling/LevelingStrings.cs
Library/ContentProviders/MeshContentProvider.cs
PrinterControls/EditLevelingSettingsPage.cs

issue: MatterHackers/MCCentral#2930
Generating 3D thumbnails for large meshes can allocate more RAM than the system has

Build orthographic thumbnails for large content

---

PartPreviewWindow/View3D/Actions/MeshWrapperObject3D.cs
PartPreviewWindow/View3D/Actions/SubtractAndReplace.cs

issue: MatterHackers/MCCentral#2921
If Object3D selection shares the same color, Paint Material appears to fail

Made subtract and replace ensure contrast with the inserted part

---

VersionManagement/WebRequestHandler.cs

- Issue MatterHackers/MCCentral#2956
Username/password data dumped to trace log if configured

Drop tracing unless specified at compile time

---

Community.CsharpSqlite/Community.CsharpSqlite.csproj
Launcher/Launcher.csproj
PluginSystem/MatterControlPluginSystem.csproj
PrinterDriverInstaller/InfInstaller.csproj

Whenever I open MatterControl in MonoDevelop, it edits all the .csproj files by removing the ReleaseVersion line. Is there any reason not to just let this happen? If you guys are ok with this then I will update the other repos as well.

Remove ReleaseVersion line from .csproj files

---

PrinterCommunication/Io/SendProgressStream.cs

The Taz does not like the colon for some reason. It causes the line checksum to fail.

Swap colon for dash in progress messages

---

PartPreviewWindow/PrinterTabPage.cs

- Issue MatterHackers/MCCentral#3005
Disabling sync-to-print should reset progressbar positions

Evaluate slider visibility on sync-to-print change

---

StaticData/SliceSettings/Properties.json

issue: MatterHackers/MCCentral#3042
Change offset to include the word Probe

adding in probe to z and xy probe offsets

---

PartPreviewWindow/View3D/SceneActions.cs

issue: MatterHackers/MCCentral#3018
Before we do an ungroup on a mesh we need to clean and merge it

Make sure we only split sorted meshes

---

ApplicationView/PrinterModels.cs
PartPreviewWindow/PrinterTabPage.cs
PartPreviewWindow/View3D/TumbleCubeControl.cs
PartPreviewWindow/View3D/View3DWidget.cs
SettingsManagement/UserSettings.cs

Made the gcode panel and the model panel match sizes
The vanishing point can be moved in x
issue: MatterHackers/MCCentral#3130
change the rotation center of the 3d view to be the center of the visible window (non-inclusive of selection bar)
issue: MatterHackers/MCCentral#3156
Add minimum size to modelViewSidePanel

Got the view to be off center

---

DesignTools/Operations/Object3DExtensions.cs
PrinterCommunication/Io/PauseHandlingStream.cs
Tests/MatterControl.Tests/MatterControl/GCodeStreamTests.cs

Make sure we don't release the printers motors while paused
also issue: MatterHackers/MCCentral#625
Print does not resume in an acceptable way after a Pause has been issued

Fix fast moves on resume

---

ApplicationView/ApplicationController.cs
SlicerConfiguration/Settings/SettingsHelpers.cs
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs

- Issue MatterHackers/MCCentral#3197
QualitySettingsStayAsOverrides test failing due to failure to switch
to selected printer

Clear ActivePrinters list before Add, remove 16 minute delay

---

Library/Widgets/PrintLibraryWidget.cs

issue: MatterHackers/MatterControl#3239
Remove from cloud library does not confirm and cannot be undone

Confirm before removing

---

ConfigurationPage/PrintLeveling/LevelingFunctions.cs
PartPreviewWindow/SelectedObjectPanel.cs
PrinterCommunication/Io/PrintLevelingStream.cs

issue: MatterHackers/MatterControl#3258
Make bed grid have a cache to improve performance of position lookups

Getting leveling triangle lookup to have a cache

---

DesignTools/Operations/Align3D.cs
DesignTools/Operations/ArrayAdvanced3D.cs
DesignTools/Operations/ArrayLinear3D.cs
DesignTools/Operations/ArrayRadial3D.cs
DesignTools/Operations/FitToBounds3D.cs
DesignTools/Primitives/TextObject3D.cs
Library/Widgets/InsertionGroup.cs
PartPreviewWindow/MaterialControls.cs
PartPreviewWindow/SelectedObjectPanel.cs
PartPreviewWindow/View3D/Actions/MeshWrapperObject3D.cs

issues:
MatterHackers/MCCentral#3273
Selection object should not have delete and make permanent
MatterHackers/MCCentral#3277
check on text makes group of meshes
MatterHackers/MCCentral#3276
disable delete on text
MatterHackers/MCCentral#3263
Need a material none button (unset)

Change make permanent to apply (consistent with solidworks)

---

PartPreviewWindow/PlusTab/PlusTabPage.cs

issue: MatterHackers/MCCentral#3191
Scrolling not functioning as expected in PrinterSelector

Make sure we check if there is wheel data before using it.

---

ConfigurationPage/PrintLeveling/ProbeCalibrationWizard.cs

This was wrong. The process actually takes 4 minutes on the Pulse XE because you have to wait for the nozzle and bed to heat up.

Change time estimate in probe calibration wizard.

---

DesignTools/Operations/Image/LinearExtrude.cs
PartPreviewWindow/SelectedObjectPanel.cs
PartPreviewWindow/View3D/Actions/CombineObject3D.cs
PartPreviewWindow/View3D/Actions/IntersectionObject3D.cs
PartPreviewWindow/View3D/Actions/MeshWrapperObject3D.cs
PartPreviewWindow/View3D/Actions/SubtractAndReplaceObject3D.cs
PartPreviewWindow/View3D/Actions/SubtractObject3D.cs

Fixed object properties panel collapse regression
Making copy mesh an extension method
issue: MatterHackers/MCCentral#3561
Editor panel fails to maintain size when collapsed via SectionWidget controls

Made linear extrude do an apply correctly

---

DesignTools/Operations/OperationSource.cs

issue: MatterHackers/MCCentral#3544
Apply array needs to return a collection of the children (rather than a bunch of children)

Make Operation Source apply create a group if more than 1 item

---

DesignTools/Primitives/ConeObject3D.cs
DesignTools/Primitives/CylinderObject3D.cs
DesignTools/Primitives/HalfCylinderObject3D.cs
DesignTools/Primitives/HalfSphereObject3D.cs
DesignTools/Primitives/RingObject3D.cs
DesignTools/Primitives/SphereObject3D.cs
DesignTools/Primitives/TorusObject3D.cs

issue: MatterHackers/MCCentral#3618
Change primitive sides to 40 by default. This makes size same as radius.

Changing default sides to 40 from 30 so that aabb matches diameter

---

PartPreviewWindow/View3D/Actions/SubtractAndReplaceObject3D.cs

issue: MatterHackers/MCCentral#3603
Changing the inner objects material does not cause subtract and replace to update

Make SubtractAndReplace rebuild on color and material child change

---

EeProm/EePromMarlinWindow.cs

issue: MatterHackers/MCCentral#3625
PID settings in EEPROM pulling incorrectly

bad bed pid writing

---

DesignTools/Operations/FitToBounds3D.cs

issue: MatterHackers/MCCentral#3661
align not applying correctly when text changes inside a fit

Make aabb useable for align

---

DesignTools/Operations/CurveObject3D.cs
DesignTools/Operations/Image/ImageToPath.cs
DesignTools/PublicPropertyEditor.cs

In the curve tool we change the diameter of the curve and the editor was
not updating to show the new value. Now it is.

Put in the ability for double edit fields to respond to value changes

---

Library/Widgets/ListView/IconListView.cs

- Issue MatterHackers/MCCentral#3630
Tooltips no longer appear on truncated item labels

Fix ToolTips on library IconListView items

---

PrinterCommunication/PrinterConnection.cs

issue: MatterHackers/MCCentral#3760
Cancel G-Code commands are sent in wrong order

Changes to print queue mean we don't reverse commands while printing

---

PartPreviewWindow/View3D/Actions/CombineObject3D.cs
PartPreviewWindow/View3D/Actions/IntersectionObject3D.cs
PartPreviewWindow/View3D/Actions/SubtractAndReplaceObject3D.cs
Tests/MatterControl.AutomationTests/PrintingTests.cs

issue: MatterHackers/MCCentral#3763
Subtracting and replacing a sphere causes a "loop" in some scenarios

Fixing boolean operations to not recurs as they set meshes

---

PartPreviewWindow/View3D/MeshViewerWidget.cs

- Issue MatterHackers/MCCentral#3820
GL lighting on part bed is confusing/unhelpful

Disable GL lighting for grid lines, use opaque colors

---

PartPreviewWindow/StartPage/ExplorePanel.cs
Utilities/MarkdigAgg/AggHeadingRenderer.cs
Utilities/MarkdigAgg/AggParagraphRenderer.cs
Utilities/MarkdigAgg/Inlines/AggLinkInlineRenderer.cs

Making wrapping work with new responsive widget
issue: MatterHackers/MCCentral#3806
Make images and sequences in Markdown shrink to fit within the bounds when bounds smaller than image

Creating a ImageSequenceWidgetResponsive

---

ConfigurationPage/ApplicationSettings/ApplicationSettingsView.cs

issue: MatterHackers/MCCentral#3902
Rebuild after switching to 3d icons does not cause a rebuild.

Delete the actual thumbnail cache when requested

---

README.md

The old link was dead since mattercontrol.com was taken down. I took a new screenshot for MatterControl 2.0.

Fixed screenshot in README

---

SlicerConfiguration/SliceSettingsWidget.cs

issue: MatterHackers/MCCentral#3916
Slice settings text fields should get undo data set to cleared after initial setting

set good starting undo point for slice settings

---

ApplicationView/ApplicationController.cs
PartPreviewWindow/SelectedObjectPanel.cs

issue: MatterHackers/MCCentral#3952
If you click the Details overflow menu before you have an object selected it no longer works

Making selection panel overflow menu track if has selection

---

ApplicationView/ApplicationController.cs
ApplicationView/ThemeConfig.cs
CustomWidgets/NamedAction.cs
CustomWidgets/TreeView/TreeNode.cs
CustomWidgets/TreeView/TreeView.cs
Library/Widgets/ListView/ListView.cs
Library/Widgets/ListView/ListViewItemBase.cs
Library/Widgets/PrintLibraryWidget.cs
MatterControl.csproj
PartPreviewWindow/PartTabPage.cs
PartPreviewWindow/SelectedObjectPanel.cs
PartPreviewWindow/SystemWindowExtension.cs
PartPreviewWindow/View3D/Actions/ImageEditor.cs
PartPreviewWindow/View3D/PrinterBar/PrinterActionsBar.cs
PartPreviewWindow/View3D/View3DWidget.cs
PartPreviewWindow/ViewControls3D.cs
Tests/MatterControl.Tests/MatterControl.Tests.csproj
Tests/MatterControl.Tests/MatterControl/PopupAnchorTests.cs

Issues remaining:
OnMouseUp fires on Widget but MouseUp event does not
Example: wrapping operation aren't visible till losefocus/refocus, item renames aren't visible till lose/refocus

Alt popups, new context menus

---

ConfigurationPage/PrintLeveling/LevelWizardCustom.cs
ConfigurationPage/PrintLeveling/LevelingWizard.cs
ConfigurationPage/PrintLeveling/PrintLevelingData.cs
MatterControl.csproj
SlicerConfiguration/Settings/PrinterSettings.cs
SlicerConfiguration/Settings/SettingsHelpers.cs
SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs
StaticData/SliceSettings/Layouts.txt
StaticData/SliceSettings/Properties.json
Tests/MatterControl.Tests/MatterControl/SettingsParseTests.cs

issue: MatterHackers/MCCentral#4048
Allow custom probing positions for bed leveling

Adding in the ability to specify custom leveling probe positions

---

SetupWizard/HelpPage.cs

- Issue MatterHackers/MCCentral#4090
Help fails to open due to null value in dictionary lookup

Guard for null

---

MatterControl.csproj
MatterControlLib/CustomWidgets/ExportPrintItemPage.cs
MatterControlLib/Library/Export/GCodeExport.cs
MatterControlLib/Library/Widgets/PrintLibraryWidget.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
MatterControlLib/PartPreviewWindow/ViewControls3D.cs

fixed a bug with MatterSlice dependancy
issue: MatterHackers/MCCentral#4032
Slicing error when slicing for Pulse

Only center on bed during gcode export when exporting from library

---

MatterControlLib/PartPreviewWindow/SelectedObjectPanel.cs

This was working the entire time I prototyped the feature - I wasn't sure how, but someone was setting the state on lose focus. Of course, once deployed the behavior is now missing.
Adding explicit setting of Enabled property on scene selection change

Set button enabled state on selection change

---

MatterControlLib/SlicerConfiguration/UIFields/EnumField.cs
Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs
Tests/MatterControl.AutomationTests/OptionsTabTests.cs
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

issue: MatterHackers/MCCentral#4108
Many test failures related to Controls/Terminal tabs being hidden by default

Getting automation tests to pass with new ui changes

---

MatterControlLib/DesignTools/Attributes/EnumRenameAttribute.cs
MatterControlLib/DesignTools/Operations/Image/ImageToPathObject3D.cs
MatterControlLib/SlicerConfiguration/UIFields/EnumField.cs

Allow renaming of enum values in public property editor

Change 'alpha' to 'transparency' in feature detector

---

MatterControlLib/SetupWizard/HelpPage.cs
MatterControlLib/Utilities/MarkdigAgg/MarkdownWidget.cs

- Issue MatterHackers/MCCentral#4126
Missing path on tree node results in visible json in Markdown view

Improve error handling on help requests, skip invalid page paths

---

MatterControlLib/PartPreviewWindow/GCodeDetails/GCodeDetailsView.cs

issue: MatterHackers/MCCentral#4214
If gcode time is < 30 seconds put up a warning message

put up a waring message if the loaded gcode file is very small

---

MatterControlLib/PartPreviewWindow/View3D/MeshViewerWidget.cs

issue: MatterHackers/MCCentral#4285
Selection highlight overwritten by Polygons rendering

Making the selection outline a bit bigger

---

MatterControlLib/ConfigurationPage/PrintLeveling/ProbeCalibrationWizard.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PauseResumeButton.cs

issue: MatterHackers/MCCentral#4351
Probe calibration is required even when software print leveling is turned off

Only require probe calibration if doing leveling

---

MatterControlLib/PrinterCommunication/PrinterConnection.cs

This is the error the printer throws when bed leveling fails. The printer has to be rebooted after this.

Catch hardware error from Prusa Mk3

---

MatterControlLib/SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs
StaticData/SliceSettings/Layouts.txt
StaticData/SliceSettings/Properties.json

issue: MatterHackers/MCCentral#4432
Show date of creation of printer profile.

added created date to oem settings area

---

MatterControlLib/CustomWidgets/TreeView/TreeNode.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs

cleans up errors with right clicking on an object different than the one selected in the scene
cleans up errors with multiple selected objects not being shown in tree view
update treenode outside of draw recursion

set selection on design history right click

---

MatterControlLib/Library/Export/GCodeExport.cs
MatterControlLib/SlicerConfiguration/Settings/PrinterSettings.cs
Tests/MatterControl.Tests/MatterControl/ImportSettingsTests.cs

- Issue MatterHackers/MCCentral#4627
PrinterSettings merge pushes every imported value into target layer

Skip fields during merge that already equal target value

---

MatterControlLib/SlicerConfiguration/Slicer.cs
Program.cs

issue: MatterHackers/MCCentral#4655
Clicking print in an empty design space results in a locked in print printer space

Return that SliceItem failed if we have nothing on the bed

---

MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PrintPopupMenu.cs

issue: MatterHackers/MCCentral#4670
Print pop-up should close after clicking print (same for after clicking setup if available)

make menu close on button click

---

MatterControlLib/ConfigurationPage/PrintLeveling/PrintLevelingWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/ProbeCalibrationWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/AutoProbeFeedback.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/FindBedHeight.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/LastPageInstructions.cs
MatterControlLib/PrinterCommunication/Io/PrintLevelingStream.cs
MatterControlLib/PrinterCommunication/Io/PrintRecoveryStream.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs

issue: MatterHackers/MCCentral#4722
Running Pulse Bed leveling while using multiple printers in Single-Windows causes the prints to fail

Make disable leveling per printer rather than static

---

MatterControlLib/PartPreviewWindow/SystemWindowExtension.cs
MatterControlLib/SlicerConfiguration/SliceSettingsRow.cs

issue: MatterHackers/MCCentral#4759
Popovers orphaned when parent PopupWidgets close
MatterHackers/MCCentral#4760
Popovers should autoclose like ToolTips
MatterHackers/MCCentral#4770
Text field loosing focus when moving to new setting

New popover fixes: timeout and closing

---

MatterControlLib/ConfigurationPage/PrintLeveling/LevelingFunctions.cs
MatterControlLib/Library/Export/GCodeExport.cs
MatterControlLib/PrinterCommunication/Io/PrintLevelingStream.cs
Tests/MatterControl.Tests/MatterControl/GCodeStreamTests.cs

Adding tests for export with and without leveling
issue: MatterHackers/MCCentral#4840
Move chopping significantly increases size of exported .gcode files

Make export without leveling not do line splitting.

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/CalibrateProbeLastPagelInstructions.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PrintPopupMenu.cs
MatterControlLib/PartPreviewWindow/ViewControls3D.cs
MatterControlLib/SlicerConfiguration/UIFields/ExtruderOffsetField.cs

- Issue MatterHackers/MatterControl#4202
GCode export not working and warning message can't be turned back on

Add case for suppressed GCode warnings

---

MatterControlLib/PartPreviewWindow/PrinterTabPage.cs

- Issue MatterHackers/MCCentral#5015
MeshViewer draws models in GCode3D view, lacks layer scrollbars

Set sceneContext.ModelView when changing view modes

---

MatterControlLib/ApplicationView/BedConfig.cs
MatterControlLib/ApplicationView/ISceneContext.cs
MatterControlLib/PartPreviewWindow/PrinterTabPage.cs

- Issue MatterHackers/MCCentral#5065
Occasionally Exported Gcode is of a previous slice not the current slice.

Improve loading up to previously active GCode file

---

MatterControl.Printing/Settings/SettingsHelpers.cs
MatterControlLib/SlicerConfiguration/UIFields/Vector2Field.cs
MatterControlLib/SlicerConfiguration/UIFields/Vector3Field.cs

issue: MatterHackers/MCCentral#5301
XY calibration wizard should truncate to two or three decimals

Show a max of 3 decimals

---

MatterControlLib/PartPreviewWindow/SceneViewer/FloorDrawable.cs

- Issue MatterHackers/MCCentral#5328
bed in design view has different colors on the two triangles of the
upper face

Fix invalid TriangleStrip definition

---

MatterControlLib/CustomWidgets/SingleWindowProvider.cs

- Issue MatterHackers/MCCentral#5287
Unable to access wizard window when parent window resized/unmaximized
Not great, possibly better. Gravitates toward keeping the titlebar on screen

Improve modal window positioning on parent resize

---

MatterControlLib/ApplicationView/SettingsValidation.cs
MatterControlLib/CustomWidgets/ExportPrintItemPage.cs
MatterControlLib/Library/Export/GCodeExport.cs
Tests/MatterControl.AutomationTests/ExportItemWindowTests.cs

- Issue MatterHackers/MCCentral#5397
export as gcode test failing due to empty bed requirement

Add conditional logic for bed validation

---

MatterControlLib/DesignTools/Operations/FitToBoundsObject3D_2.cs

issue: MatterHackers/MCCentral#5431
Changing Text to just a space " " crashes MatterControl

Don't fit objects that have no size

---

MatterControlLib/DesignTools/Operations/OperationSourceObject3D.cs

also make sure we can flatten the inner content of a subtract and replace
issue: MatterHackers/MCCentral#5436
Shark hex tile crashes on ungroup

make sure we can flatten a just flattened subtract and replace child

---

MatterControlLib/PartPreviewWindow/SceneViewer/FloorDrawable.cs

- Issue MatterHackers/MCCentral#5450
Looking up in design view has no bed transparency

Enable transparency on design workspace bed

---

MatterControlLib/DesignTools/Operations/CurveObject3D_2.cs

issue: MatterHackers/MCCentral#5430
Subtracting a Bend-modified object doesn't do anything.

making bend do a merge vertices after to fix non-manifold edges

---

MatterControlLib/DesignTools/Primitives/XyCalibrationFaceObject3D.cs
MatterControlLib/DesignTools/Primitives/XyCalibrationTabObject3D.cs
MatterControlLib/Library/Providers/MatterControl/PrimitivesContainer.cs

issue: MatterHackers/MCCentral#5407
xy calibration does not produce a valid test for nozzle size of 2mm

Improve xy calibration objects for large nozzles

---

MatterControlLib/ApplicationView/Themes/ThemeConfig.cs
MatterControlLib/ApplicationView/WorkspacesChangedEventArgs.cs
MatterControlLib/Library/ContentProviders/MeshContentProvider.cs
MatterControlLib/Library/Providers/FileSystem/FileSystemContainer.cs
MatterControlLib/Library/Widgets/ListView/ListViewItemBase.cs

- Ensure icon is loaded after .InvertIcons property is deserialized 
- Ensure MeshProvider default icon is theme aware
- Prevent loss of state and flicker during icon generation
- Code cleanup, remove unused event

Revise icon loading

---

MatterControlLib/CustomWidgets/ConfigurePrinterWidget.cs
MatterControlLib/PartPreviewWindow/MainViewWidget.cs
MatterControlLib/SlicerConfiguration/Settings/ProfileManager.cs
MatterControlLib/Utilities/WebUtilities/WebCache.cs
Tests/MatterControl.AutomationTests/PrinterDropDownTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

issue: MatterHackers/MCCentral#6102
Renaming printer when 2 are open, renames both

Created test and addressed printer name bug

---

MatterControlLib/PartPreviewWindow/View3D/CameraFittingUtil.cs
MatterControlLib/PartPreviewWindow/View3D/TrackballTumbleWidgetExtended.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs

Better orthographic zoom limits, replace raw trig calls with WorldView util functions, and handle the case where viewspace Z is too close to zero during a switch to orthographic.

Changes for orthographic view mode

---

MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs

Avoid going through integers. And make translation snapping consistent when crossing over the zero point on an axis, rather than rounding towards zero.

Use Math.Round for snap rounding.

---

.gitignore
MatterControlLib/PartPreviewWindow/MainViewWidget.cs
MatterControlLib/SlicerConfiguration/SliceSettingsWidget.cs
Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

The draw handler in the old code used the `tab` local variable, which got changed to a different tab.
*The "Fix slice settings tests." commit is part of the coming .NET 6 upgrade PR. But it seems the checks have passed anyway.

Fix the position of the blue dot on the upgrade tab.

---

MatterControlLib/SlicerConfiguration/SliceSettingsRow.cs
StaticData/Translations/Master.txt
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs

This is my proposal to resolve #5190.
The name of the setting to be saved is now included in the label of the 'Save to' menu items.
The title of the issue also mentions a 'Remove From' menu, but I couldn't find it. Is that part still relevant?

Add the name of the slice setting to the 'Save to' menu

---

MatterControlLib/Library/Export/AmfExport.cs

Exporting an AMF file throws a NullReferenceException.
It seems the `progress` parameter of `MeshExport.ExportMesh` must not be `null` and should be forwarded from `AmfExport.Generate` in this case.

Fixed NullReferenceException being thrown when exporting AMF file

---

MatterControlLib/PartPreviewWindow/ViewToolBarControls.cs
MatterControlLib/Utilities/MarkdigAgg/AggRenderer.cs
MatterControlLib/Utilities/MarkdigAgg/AggTableRenderer.cs
MatterControlLib/Utilities/MarkdigAgg/AggTableRow.cs
MatterControlLib/Utilities/MarkdigAgg/TableHeadingRow.cs

I came across an open ticket (#5191) and thought it would be interesting to revisit how the Markdig renderers worked and how to map to anything in Agg that might be a start for a table implementation. I'm certain you can quickly revise the layout issues 
I ran into, and pick more appropriate types for table row/cells. If nothing else, hopefully, this might demystify the Markdig steps needed to plug in something for table support in Agg. 
I'm not sure if you'd want to merge as is, but you might consider it and simply disable the `ObjectRenderers.Add(new AggTableRenderer());` in release builds.
Next steps would be to eliminate the fixed width values I put in place to demo a quick prototype, and wire up to configuration-based widths from the Markdig parser, and track and use cell content …

Markdig table renderer prototype
