CustomWidgets/LibrarySelector/FolderBreadCrumbWidget.cs
Library/Providers/FileSystem/FileSystemContainer.cs
Library/Widgets/ListView/ListView.cs
Library/Widgets/PrintLibraryWidget.cs
PartPreviewWindow/LibraryBrowserPage.cs

- Issue MatterHackers/MCCentral#2479
Up Folder buttons should be disabled in root container

Disable Up Folder button in RootContainer

---

ApplicationView/WidescreenPanel.cs
MatterControl.csproj
PartPreviewWindow/PartPreviewContent.cs
PartPreviewWindow/PartTabPage.cs
PartPreviewWindow/PrinterTabPage.cs
PartPreviewWindow/Toolbar.cs
PartPreviewWindow/View3D/PrinterBar/OverflowBar.cs
PartPreviewWindow/View3D/PrinterBar/PrinterActionsBar.cs
PartPreviewWindow/ViewControls3D.cs

- Issue MatterHackers/MCCentral#2504
Overflow menus should be floating, always on screen, right aligned

Update overflow menus

---

PartPreviewWindow/View3D/MeshViewerWidget.cs

- Issue MatterHackers/MCCentral#2249
Discuss options for editing IObject3D elements

Remove rendering workaround

---

PartPreviewWindow/View3D/Actions/IntersectionEditor.cs

- Issue MatterHackers/MCCentral#2506
Fix Intersect operation

Only process Intersect if mesh is null

---

CustomWidgets/EditableNumberDisplay.cs
MatterControl.csproj
PartPreviewWindow/View3D/SideBar/MirrorControls.cs
PartPreviewWindow/View3D/SideBar/ScaleControl.cs
PartPreviewWindow/View3D/View3DWidget.cs

issue: MatterHackers/MCCentral#2468
Restore Scale controls

Put back in the scale control

---

PartPreviewWindow/PartPreviewContent.cs

- Issue MatterHackers/MCCentral#2505
Always open into Start Page

Revert breaking change

---

CustomWidgets/InlineEditControl.cs

- Issue MatterHackers/MCCentral#2200
Phantom text drawn for first few seconds

Ensure control is invisible at startup

---

ApplicationView/PrinterModels.cs
PartPreviewWindow/View3D/PrinterBar/PrinterActionsBar.cs
PrinterCommunication/PrinterConnection.cs
PrinterControls/TerminalWindow/TerminalLog.cs
PrinterEmulator/Emulator.cs

- Issue MatterHackers/MCCentral#2541
Revised connect logic, removed from ReadFromPrinter

Consolidate Printer -> Connect behavior

---

PrinterCommunication/PrinterConnection.cs

- Issue MatterHackers/MCCentral#2543
StackOverflowException during tests brings down NUnit

Possible workaround for stackoverflow exception

---

ApplicationView/ApplicationController.cs
Library/Widgets/PrintLibraryWidget.cs
PartPreviewWindow/OverflowMenu.cs
PartPreviewWindow/View3D/PrinterBar/OverflowBar.cs
PartPreviewWindow/View3D/View3DWidget.cs
Program.cs

- Issue MatterHackers/MCCentral#2538
Can't run with no MatterControl directory (new install)

Move DataStore.Initialize before db dependent GetStartupBounds call

---

PartPreviewWindow/View3D/SceneActions.cs
PartPreviewWindow/View3D/View3DWidget.cs
Tests/MatterControl.AutomationTests/PrintingTests.cs
TextCreator/Braille/BrailleEditor.cs
TextCreator/Text/TextEditor.cs

issue: MatterHackers/MCCentral#2464
Canceled print, controls did not re-enable

Removed Lock and Unlock edit controls

---

PartPreviewWindow/OverflowMenu.cs
PartPreviewWindow/PopupButton.cs
SlicerConfiguration/SliceSettingsOverflowMenu.cs
SlicerConfiguration/SliceSettingsWidget.cs

- Issue MatterHackers/MCCentral#2553
Draw transparent to opaque background on overflow menu

Add gradient background

---

ApplicationView/PrinterModels.cs
ApplicationView/ThemeConfig.cs
CustomWidgets/ConfigurePrinterWidget.cs
CustomWidgets/DockingTabControl.cs
CustomWidgets/NamedAction.cs
PartPreviewWindow/PrinterTabPage.cs
PartPreviewWindow/View3D/PrinterBar/PrinterActionsBar.cs

- Issue MatterHackers/MCCentral#2561
Configure -> Printer should survive ReloadAll

Maintain state across ReloadAll

---

PartPreviewWindow/PartPreviewContent.cs
StaticData/SliceSettings/Layouts.txt

- Issue MatterHackers/MCCentral#2569
Remove external slice settings from layouts.txt

Remove unmapped settings and empty sections

---

ConfigurationPage/PrintLeveling/LevelWizardBase.cs
ConfigurationPage/PrintLeveling/PrintLevelPages.cs
EeProm/EePromMarlinSettings.cs
EeProm/EePromRepetierParameter.cs
EeProm/EePromRepetierStorage.cs
Library/Providers/SDCard/SDCardContainer.cs
PartPreviewWindow/View3D/PrinterBar/PrinterActionsBar.cs
PrinterCommunication/Io/GCodeFileStream.cs
PrinterCommunication/Io/PauseHandlingStream.cs
PrinterCommunication/Io/PrintRecoveryStream.cs
PrinterCommunication/PrinterConnection.cs
PrinterControls/TerminalWindow/TerminalWidget.cs
Queue/QueueData.cs
SlicerConfiguration/Settings/GCodeMacro.cs

- Issue MatterHackers/MCCentral#2576
Send something other than M110 during connect?

Improve Connect

---

ApplicationView/ApplicationController.cs
PartPreviewWindow/View3D/PrinterBar/PrinterConnectButton.cs
PrinterCommunication/PrinterConnection.cs
SetupWizard/AndroidConnectDevicePage.cs

- Remove showHelpIfNoPort param

Remove Connect failed/troubleshoot UI from PrinterConnection

---

ApplicationView/PrinterModels.cs
PrinterCommunication/PrinterConnection.cs

- Add properties to PrinterConnection for dependencies in SliceSettings
- Set properties on construction
- Sync properties on change

Remove SliceSettings coupling from PrinterConnection

---

CustomWidgets/ResizeContainer.cs
PartPreviewWindow/SelectedObjectPanel.cs
PartPreviewWindow/View3D/View3DWidget.cs
TextCreator/CardHolderTool/CardHolder.cs

Working on new subtract test
issue: MatterHackers/MCCentral#2586
No longer possible to size IObject3D -> Selection panel

Fixed resize container

---

ApplicationView/PrinterModels.cs
Library/Widgets/ExpandCheckboxButton.cs
Library/Widgets/PrintLibraryWidget.cs
PartPreviewWindow/PartTabPage.cs
PartPreviewWindow/SectionWidget.cs
PartPreviewWindow/SelectedObjectPanel.cs
PartPreviewWindow/View3D/MeshViewerWidget.cs
PartPreviewWindow/View3D/SceneActions.cs
PartPreviewWindow/View3D/SideBar/ScaleControl.cs
PartPreviewWindow/View3D/View3DWidget.cs
PartPreviewWindow/ViewControls3D.cs
SettingsManagement/UserSettings.cs
Tests/MatterControl.AutomationTests/PartPreviewTests.cs
Tests/MatterControl.AutomationTests/SqLiteLibraryProvider.cs

- Issue MatterHackers/MCCentral#2613
IObject3D -> Selection panel should remember its size across ReloadAll and app restarts

 Consolidate header and footer bars into SelectedObjectPanel

---

ApplicationView/ApplicationController.cs
CustomWidgets/NamedAction.cs
PartPreviewWindow/SectionWidget.cs
PartPreviewWindow/SelectedObjectPanel.cs
PartPreviewWindow/ViewControls3D.cs

- Issue MatterHackers/MCCentral#2618
Inconsistent padding in sidebar section widgets

Enforce sidebar panel padding

---

ActionBar/TemperatureWidgetExtruder.cs
ApplicationView/ApplicationController.cs
PartPreviewWindow/SelectedObjectPanel.cs
SlicerConfiguration/Settings/PrinterSettings.cs
SlicerConfiguration/Settings/SettingsHelpers.cs

Fixed extruder 3 and 4
issue: MatterHackers/MCCentral#2619
Layout skipped on CloseAllChildren?

Made switching to no editor layout correctly.

---

SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs

issue: MatterHackers/MCCentral#1979
Exception due to unsafe processing of ExtruderOffset

Fixing possible error while parsing extruder offsets

---

Library/Export/GCodeExport.cs

issue: MatterHackers/MCCentral#2558
Export GCode needs to collect/respect leveling option

Make sure we default to adding leveling to exported g-code.

---

MatterControl.Printing/Communication/FoundStringCallBacks.cs
PrinterCommunication/Io/ProcessWriteRegExStream.cs
PrinterCommunication/PrinterConnection.cs

Added "WRITE_RAW" comment parser that turns off checksum
Made readline rewrite work with multiple lines

Made smoothie printer work with run out sensor

---

StaticData/SliceSettings/Layouts.txt
StaticData/SliceSettings/Properties.json

removed more unused settings
issue: MatterHackers/MCCentral#2574
Extract to discrete section, always leave common support options enabled

Made more support slice settings stay enabled

---

ApplicationView/ApplicationController.cs
PartPreviewWindow/View3D/Actions/SubtractAndReplace.cs
PartPreviewWindow/View3D/Actions/SubtractEditor.cs

issue: MatterHackers/MCCentral#2621
Auto select a radio option after Subtract/Paint operation

Made update button work better on subtract

---

PartPreviewWindow/OverflowMenu.cs
PartPreviewWindow/ViewControls3D.cs

- Issue MatterHackers/MCCentral#2641
Bed/part button inconsistent

Fix bed menu spacing, background color, add support for non-gradient bg

---

PartPreviewWindow/View3D/Actions/SubtractAndReplace.cs
PartPreviewWindow/View3D/Actions/SubtractEditor.cs

Fixed selection logic in Subtrackt and Replace
Refactoring

Added DescendantsAndSelf

---

AboutPage/CheckForUpdatesPage.cs
AboutPage/UpdateControlData.cs
AboutPage/UpdateControlView.cs
ConfigurationPage/ApplicationSettings/ApplicationSettingsView.cs
PartPreviewWindow/PartPreviewContent.cs

issue: MatterHackers/MCCentral#2134
Update startup logic to check for latest version and recheck if 24 hours has elapsed

Check for update every day

---

ActionBar/TemperatureWidgetBed.cs
ActionBar/TemperatureWidgetExtruder.cs
ApplicationView/ApplicationController.cs
ApplicationView/PrinterModels.cs
ApplicationView/ThemeConfig.cs
ConfigurationPage/ApplicationSettings/SettingsItem.cs
CustomWidgets/ConfigurePrinterWidget.cs
CustomWidgets/LibrarySelector/FolderBreadCrumbWidget.cs
Library/Widgets/PrintLibraryWidget.cs
MatterControl.csproj
PartPreviewWindow/PrinterTabPage.cs
PartPreviewWindow/SelectedObjectPanel.cs
PartPreviewWindow/Toolbar.cs
PartPreviewWindow/View3D/PrinterBar/PrintPopupMenu.cs
PrinterControls/ManualPrinterControls.cs
SettingsManagement/UserSettings.cs
SetupWizard/LicenseAgreementPage.cs
SlicerConfiguration/Settings/PrinterSettings.cs
SlicerConfiguration/SettingsOrganizer.cs
SlicerConfiguration/SliceSettingsOrganizer.cs
SlicerConfiguration/SliceSettingsOverflowMenu.cs
SlicerConfiguration/SliceSettingsRow.cs
SlicerConfiguration/SliceSettingsWidget.cs
SlicerConfiguration/UIFields/ExtruderOffsetField.cs
StaticData/SliceSettings/Layouts.txt
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

Lots of hacks needed for layout and ScrollableWidget to be close to what's desired. Hopefully going forward we can remove the hacks and fix the quirks.

Unified and enhanced SliceSettings views

---

PartPreviewWindow/View3D/View3DWidget.cs

Just like John's TODO that was sitting there
Also fixed a bug with material index

Made the render state get set when constructing

---

PartPreviewWindow/View3D/View3DWidget.cs

Recomputes when needed
Caches values
issue: MatterHackers/MCCentral#2287
New objects dragged into scene do not get Overhang rendering mode

Wrote an overhang renderer class

---

ControlElements/MHTextEditWidget.cs

issue: MatterHackers/MCCentral#2589
Unable to select text when drag start to the right of existing characters

Fixe text tests

---

CustomWidgets/InlineTitleEdit.cs

- Issue MatterHackers/MCCentral#2698
IObject3D names change unexpectedly

Only fire TitleChanged on user driven actions

---

MatterControl.Printing/GCode/GCodeMemoryFile.cs
PartPreviewWindow/GCode2DWidget.cs
PartPreviewWindow/PrinterTabPage.cs

issue: MatterHackers/MCCentral#2602
GCode2D transform should only be computed on first load

GCode2D transform should only be computed on first load

---

ApplicationView/ApplicationController.cs
DesignTools/BendOperation.cs
DesignTools/MeshObjects.cs
DesignTools/PubicPropertyEditor.cs
MatterControl.csproj
PartPreviewWindow/View3D/Actions/ProportionalEditor.cs
Tests/MatterControl.Tests/MatterControl/BrailleGrade2Tests.cs
TextCreator/TextCreator.csproj

Refactored MatterCad editor to PublicProperties editor

Working on creating a proportional scale tool

---

PartPreviewWindow/View3D/MeshViewerWidget.cs

issue: MatterHackers/MCCentral#2702
Make persistable render effect update when there is a change to the state

Added automatic persist able render effect

---

DesignTools/PubicPropertyEditor.cs
PartPreviewWindow/View3D/View3DWidget.cs

issue: MatterHackers/MCCentral#2472
Bad world position - mouse, drag target out of sync, get worse

Fixed problem dragging onto bed when plane can't be found initially

---

ApplicationView/WindowsPlatformsFeatures.cs
Library/Export/GCodeExport.cs
Library/Providers/MatterControl/SqliteLibraryContainer.cs
PartPreviewWindow/ViewControls3D.cs
Queue/OptionsMenu/ExportToFolderProcess.cs
RootSystemWindow.cs
SettingsManagement/ApplicationSettings.cs
Utilities/ProjectFileHandler.cs

- Issue MatterHackers/MCCentral#2527
Too many authorities on valid files types

Consolidate file extension definitions

---

PartPreviewWindow/View3D/PrinterBar/PrintPopupMenu.cs
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

Added scroll into view
Made popup widget get the right scroll
Made automation runner able to find widgets that aren't visible

Fixing tests

---

PartPreviewWindow/View3D/GridOptionsPanel.cs

- Issue MatterHackers/MCCentral#2642
Minuscule snap grid popup

Revert accidental MaxHeight = 11

---

ApplicationView/ApplicationController.cs
DesignTools/Operations/Translate.cs
PrinterCommunication/PrinterConnection.cs

issue: MatterHackers/MCCentral#2721
Make automattic heat shutoff have a two minute delay

Made a 1 minute delay

---

ApplicationView/PrinterModels.cs
Library/Export/MeshExport.cs
Library/Providers/MatterControl/SqliteLibraryContainer.cs
SlicerConfiguration/Slicer.cs

issue: MatterHackers/MCCentral#2636
Canceling slice process doesn't stop print until after it's finished slicing and begun printing

Started work on getting slicing to respect cancel

---

SlicerConfiguration/SliceSettingsWidget.cs

initially start with only top section open
search opens all sectcions
issue: MatterHackers/MCCentral#2734
Empty settings sections should not be visible

hide empty sections

---

SlicerConfiguration/SliceSettingsWidget.cs

issue: MatterHackers/MCCentral#2725
Seems like we are showing settings that are not in 'My Settings'

Filter out my settings that are same as oem + base

---

Library/Providers/FileSystem/FileSystemContainer.cs
Library/Providers/LibraryContainer.cs
Library/Providers/MatterControl/PrintQueueContainer.cs
Library/Providers/MatterControl/SqliteLibraryContainer.cs
Library/Providers/SDCard/SDCardContainer.cs
Tests/MatterControl.AutomationTests/LibraryActionTests.cs
Tests/MatterControl.AutomationTests/PrintQueueTests.cs
Tests/MatterControl.AutomationTests/PrintQueueUncertain.cs

- Issue MatterHackers/MCCentral#2748
Investigate ~30 failing tests due to OnContentChanged revision

Restore automatic Load in OnContentChanged, rename to ReloadContent 

---

Library/Providers/GeneratorItem.cs

- Issue MatterHackers/MCCentral#2733
Reconsider primitive colors

Turn off rainbow coloring and review

---

PrinterCommunication/Io/WaitForTempStream.cs

issue: MatterHackers/MCCentral#2751
Adjust MatterControl M190 hysteresis to 3 degrees

Set bed temp range to 3

---

ApplicationView/PrinterModels.cs
Library/Export/GCodeExport.cs
MatterControl.Printing/GCode/GCodeFile.cs
MatterControl.Printing/GCode/GCodeMemoryFile.cs
PrinterCommunication/PrinterConnection.cs
Queue/OptionsMenu/ExportToFolderProcess.cs
SlicerConfiguration/Settings/SettingsHelpers.cs
SlicerConfiguration/SlicerMapping/SliceEngineMapping.cs
StaticData/SliceSettings/Layouts.txt
StaticData/SliceSettings/Properties.json

issue: MatterHackers/MCCentral#2484
Peopoly Moai Time estimates off

Added in ability to manually adjust the gcode time multiplier

---

DesignTools/Primitives/TextObject3D.cs
PartPreviewWindow/View3D/MeshViewerWidget.cs

Made text widget have individual characters

---

ApplicationView/PrinterModels.cs
PartPreviewWindow/PopupMenu.cs
PartPreviewWindow/PrinterTabPage.cs
PartPreviewWindow/View3D/MeshViewerWidget.cs
PartPreviewWindow/View3D/View3DWidget.cs

Add user control of model rendering in GCode view

---

ApplicationView/ApplicationController.cs
ApplicationView/ThemeConfig.cs
CustomWidgets/NamedAction.cs
PartPreviewWindow/PopupMenu.cs
PartPreviewWindow/View3D/SceneActions.cs
PartPreviewWindow/View3D/View3DWidget.cs
PartPreviewWindow/ViewControls3D.cs

- Issue MatterHackers/MCCentral#2775
Make CTRL-C function as expected in View3DWidget
- Issue MatterHackers/MCCentral#2776
Make CTRL-S function as expected in View3DWidget

Add cut/copy/paste/save support to scene views

---

PrinterCommunication/Io/MacroProcessingStream.cs
StaticData/SliceSettings/load_filament.txt
StaticData/SliceSettings/unload_filament.txt

issue: MatterHackers/MCCentral#2786
After loading filament after a runout on Pulse, heaters turned off.

Made load / unload filament not turn off heater when done while printing

---

PrinterControls/ControlWidgets/MacroControls.cs
PrinterControls/MacroDetailPage.cs
PrinterControls/MacroListPage.cs

Make macros save when changed
issue: MatterHackers/MCCentral#2783
Recently created macros not appearing in Macros panel without ReloadAll

Make the macro controls rebuild when macros change

---

PartPreviewWindow/CreateDiscreteMeshes.cs
PartPreviewWindow/View3D/MeshViewerWidget.cs

Took out MeshGroup
issue: MatterHackers/MCCentral#2760
Cannot export these as STL files

Fixed STL export

---

PartPreviewWindow/View3D/PrinterBar/OverflowBar.cs
PartPreviewWindow/View3D/PrinterBar/PrinterActionsBar.cs

- Issue MatterHackers/MCCentral#2796
Missing bed temp control

Revise overflow behavior

---

PartPreviewWindow/BranchEditContainer.cs
Tests/MatterControl.AutomationTests/LibraryContainerTests.cs

- Issue MatterHackers/MCCentral#2789
Write fixes for BranchEditContainerTest

Workarounds for failing tests

---

DesignTools/Primitives/RoundRoofObject3D.cs
DesignTools/Primitives/SphereAdvancedObject3D.cs
DesignTools/Primitives/TorusObject3D.cs
MatterControl.csproj

Fixed a bug with putting trace data on a mesh with no faces

---

ApplicationView/PrinterModels.cs
SlicerConfiguration/Settings/ProfileManager.cs

- Issue MatterHackers/MCCentral#2552
Startup hangs at "ProfileManager" when complex items are on bed

Use unwaited async load for new LoadPlateFromHistory method

---

Library/Providers/MatterControl/PrintQueueContainer.cs
Library/Providers/MessageItem.cs
Library/Widgets/ListView/IconListView.cs
Library/Widgets/ListView/ListView.cs
Library/Widgets/ListView/ListViewItemBase.cs

- Issue MatterHackers/MCCentral#1446
More consistent mechanism needed to construct new FileSytemFileItem or MissingFileItem if not found

Use specialized type for missing files in Queue

---

ApplicationView/PrinterModels.cs
PartPreviewWindow/GCode3DWidget.cs
PartPreviewWindow/GCodeDetailsView.cs
PartPreviewWindow/PartTabPage.cs
PartPreviewWindow/PrinterTabPage.cs
PartPreviewWindow/SelectedObjectPanel.cs
PartPreviewWindow/View3D/View3DWidget.cs
SettingsManagement/UserSettings.cs

- Issue MatterHackers/MCCentral#2731
Speed legend and details don't show on 2D G-Code view

Add persistent GCode sidebar, add db settings to track width

---

PartPreviewWindow/View3D/Actions/MeshWrapperOperation.cs

issue: MatterHackers/MCCentral#2840
Add bake and remove to built-in operations

Getting remove and bake working for mesh wrapper opperations

---

CustomWidgets/PrintingWindow/ProgressDial.cs
DesignTools/Operations/ArrayRadialObject3D.cs
Library/ContentProviders/MeshContentProvider.cs
PartPreviewWindow/PrinterTabPage.cs
PrinterCommunication/Io/PauseHandlingStream.cs
PrinterCommunication/PrinterConnection.cs
SlicerConfiguration/Settings/SettingsHelpers.cs
SlicerConfiguration/SlicerMapping/SliceEngineMapping.cs
StaticData/SliceSettings/Layouts.txt
StaticData/SliceSettings/Properties.json
Tests/MatterControl.AutomationTests/PrintingTests.cs

removed the gcode buffer size variable (it didn't work)

Fixed print recovery test

---

DesignTools/Operations/Object3DExtensions.cs
DesignTools/Primitives/CubeObject3D.cs
DesignTools/Primitives/CylinderObject3D.cs
Library/Export/StlExport.cs
PartPreviewWindow/SelectedObjectPanel.cs
PartPreviewWindow/View3D/Actions/CombineEditor.cs

Getting more MatterCad scripting working

Improving STL export

---

PartPreviewWindow/View3D/Actions/MeshWrapperOperation.cs
PartPreviewWindow/View3D/Actions/SubtractAndReplace.cs
PartPreviewWindow/View3D/Actions/SubtractEditor.cs

issue: MatterHackers/MCCentral#2764
Not showing transparency correctly on subtract objct (name)

Fixed rendering problem with holes.

---

PartPreviewWindow/View3D/PrinterBar/PrinterActionsBar.cs
SetupWizard/ImportSettingsPage.cs

issue: MatterHackers/MCCentral#2868
Feature request: Import/Export Material Profile

Make it possible to import to current profile or new preset

---

PartPreviewWindow/View3D/MeshViewerWidget.cs

issue: MatterHackers/MCCentral#2878
Textures should check for transparency

Check for transparent textures on render

---

PartPreviewWindow/PlatingHelper.cs
PartPreviewWindow/View3D/Actions/CombineEditor.cs
PartPreviewWindow/View3D/Actions/IntersectionEditor.cs
PartPreviewWindow/View3D/MeshViewerWidget.cs
TextCreator/app.config

Made drawing selection optional

Cleaned up bug with union and intersection editor re-doing work

---

PartPreviewWindow/Tabs.cs

- Issue MatterHackers/MCCentral#2853
Revise Tab logic to prevent this anomaly

Update tab pointers on removal

---

PartPreviewWindow/PlusTab/ExplorePanel.cs

issue: MatterHackers/MCCentral#2888
Restore + page banner

putting back in banner

---

ConfigurationPage/PrintLeveling/LevelingStrings.cs

issue: MatterHackers/MCCentral#2937
Calibration location needs updated

Improving leveling done message

---

ApplicationView/ApplicationController.cs
DesignTools/Operations/ArrangeObject3D.cs
DesignTools/Operations/ArrayAdvancedObject3D.cs
DesignTools/Operations/ArrayLinearObject3D.cs
DesignTools/Operations/ArrayRadialObject3D.cs
DesignTools/Primitives/BaseObject3D.cs
DesignTools/Primitives/ConeObject3D.cs
DesignTools/Primitives/CubeObject3D.cs
DesignTools/Primitives/CylinderAdvancedObject3D.cs
DesignTools/Primitives/CylinderObject3D.cs
DesignTools/Primitives/HalfSphereObject3D.cs
DesignTools/Primitives/PyramidObject3D.cs
DesignTools/Primitives/RingObject3D.cs
DesignTools/Primitives/RoofObject3D.cs
DesignTools/Primitives/RoundRoofObject3D.cs
DesignTools/Primitives/SphereAdvancedObject3D.cs
DesignTools/Primitives/SphereObject3D.cs
DesignTools/Primitives/TextObject3D.cs
DesignTools/Primitives/TorusObject3D.cs
DesignTools/Primitives/WedgeObject3D.cs
MatterControl.csproj
PartPreviewWindow/SelectedObjectPanel.cs
PartPreviewWindow/View3D/Actions/CombineEditor.cs
PartPreviewWindow/View3D/Actions/IntersectionEditor.cs
PartPreviewWindow/View3D/Actions/MeshWrapperObject3D.cs
PartPreviewWindow/View3D/Actions/SubtractAndReplace.cs
PartPreviewWindow/View3D/Actions/SubtractEditor.cs
TextCreator/Braille/BrailleCardObject3D.cs
TextCreator/Braille/BrailleObject3D.cs

issue: MatterHackers/MCCentral#2927
Remove IObject3D.ActiveEditor

Took out ActiveEditor property

---

ConfigurationPage/PrintLeveling/PrintLevelPages.cs
ConfigurationPage/PrintLeveling/ProbeCalibrationWizard.cs
PartPreviewWindow/PlusTab/ExplorePanel.cs
PartPreviewWindow/View3D/PrinterBar/PrinterActionsBar.cs
SetupWizard/ImportSettingsPage.cs

issue: MatterHackers/MCCentral#2877
Only use this dialog while importing

Improved printer import experience (mad simpler)

---

ApplicationView/ApplicationController.cs
StaticData/OEMSettings/Settings.json

issue: MatterHackers/MCCentral#2862
Get MatterHackers links to be on Affiliately

Getting in new affiliate codes for matterhackers.com

---

PartPreviewWindow/ViewControls3D.cs

- Issue MatterHackers/MCCentral#2857
Export to STL fails

Fix STL export

---

ApplicationView/ApplicationController.cs
DesignTools/Interfaces/IEditorDraw.cs
DesignTools/Operations/ArrayLinearObject3D.cs
DesignTools/Operations/FitToBounds.cs
DesignTools/Primitives/CubeObject3D.cs
DesignTools/PublicPropertyEditor.cs
MatterControl.csproj
PartPreviewWindow/View3D/MeshViewerWidget.cs

This should allow use objects like card holder alignment
made aabb rendering more generic
Added editor draw to objects

Added new fit to bounds

---

ApplicationView/ApplicationController.cs
History/PrintHistoryData.cs

issue: MatterHackers/MCCentral#2891
Print recovery not showing print progress / pause / cancel panel

Make sure we always show the printing window

---

ControlElements/TextImageButtonFactory.cs
PartPreviewWindow/View3D/ColorSwatchSelector.cs
PartPreviewWindow/View3D/TumbleCubeControl.cs
RootSystemWindow.cs

Made more controls able to scale down
- color swatch
- tumble control
- default button height
issue: MatterHackers/MatterControl#3096
add support for 800x480 resolution

Make the minimum window height 480

---

ActionBar/TemperatureWidgetBed.cs
ActionBar/TemperatureWidgetExtruder.cs
ApplicationView/ApplicationController.cs
ApplicationView/LogoSpinner.cs
ConfigurationPage/PrintLeveling/PrintLevelPages.cs
ConfigurationPage/RunningMacroPage.cs
ControlElements/AttentionGetter.cs
CustomWidgets/InlineEditControl.cs
PartPreviewWindow/PrinterTabPage.cs
PartPreviewWindow/View3D/TumbleCubeControl.cs
PartPreviewWindow/View3D/View3DWidget.cs
PrinterCommunication/PrinterConnection.cs

Make sure we don't show time to turn of temps if already off
Make sure tumble cube is build before putting textures on it
issue: MatterHackers/MCCentral#2961
Add SetInterval type method to UiThread

Added SetInterval to uithread

---

ApplicationView/LogoSpinner.cs
ConfigurationPage/ApplicationSettings/ApplicationSettingsView.cs
DesignTools/Primitives/ImageObject3D.cs
Library/Providers/MatterControl/CalibrationPartsContainer.cs

MatterHackers/MCCentral#2946
StaticData.MapPath should be deprecated and removed

Remove MapPath

---

ApplicationView/ApplicationController.cs
ConfigurationPage/PrintLeveling/PrintLevelPages.cs
PrinterCommunication/PrinterConnection.cs

issue: MatterHackers/MCCentral#2917
Extruder temperature drops after completing print

Turn temps off immediately on print complete

---

PartPreviewWindow/SelectedObjectPanel.cs

- Issue MatterHackers/MCCentral#2852
Wrapping operation buttons should be hidden if not in scene root

Revise rules for showing operation buttons

---

DesignTools/Primitives/BaseObject3D.cs

- Issue MatterHackers/MCCentral#2977

Restore ImageConverter base functionality

---

ApplicationView/ApplicationController.cs
DesignTools/Lithophane.cs
DesignTools/LithophaneObject3D.cs
DesignTools/PublicPropertyEditor.cs
MatterControl.csproj
PartPreviewWindow/SelectedObjectPanel.cs
PartPreviewWindow/View3D/Actions/ImageEditor.cs

- Issue MatterHackers/MCCentral#2985
Public properties editor should use existing editor system

Use existing editor system

---

PartPreviewWindow/SelectedObjectPanel.cs
PartPreviewWindow/View3D/PrinterBar/PrintPopupMenu.cs

- Workaround introduces flicker. Evaluate and select lesser evil
- Issue MatterHackers/MCCentral#2991
Print popup -> Advanced pushes primary action offscreen

Start visible and toggle off to work around layout quirk

---

PartPreviewWindow/ViewControls3D.cs

- Issue MatterHackers/MCCentral#2973
Bed -> Insert should work for all known content types

Include all known extension types in single field FileDialog filter

---

PartPreviewWindow/View3D/Actions/SubtractAndReplace.cs
PartPreviewWindow/View3D/Actions/SubtractEditor.cs
PrinterCommunication/PrinterConnection.cs
Tests/MatterControl.Tests/MatterControl.Tests.csproj
Tests/MatterControl.Tests/MatterControl/MeshCsgTests.cs

issue: MatterHackers/MCCentral#2975
Temperatures can turn off after starting print

Improving the csg tests

---

ApplicationView/PrinterModels.cs
PartPreviewWindow/PrinterTabPage.cs
PartPreviewWindow/SliceLayerSelector.cs

- Issue MatterHackers/MCCentral#3016
Switching colors leaks GuiWidgets

Release event listeners on close

---

ApplicationView/ApplicationController.cs
ConfigurationPage/PrintLeveling/PrintLevelingData.cs
PartPreviewWindow/View3D/PrinterBar/PauseResumeButton.cs
PrinterCommunication/PrinterConnection.cs

Made the print setup button have much better state logic
Move all turn off heat logic to printer connection
issue: MatterHackers/MCCentral#3029
change cancel delay turn off heat to be the setting of any temp above 0 (in addition to whatever other rules)

Fixed bug with delayed heat turning off even after it has been set to on

---

MatterControl.csproj
SlicerConfiguration/SettingsRow.cs
SlicerConfiguration/SliceSettingsRow.cs
SlicerConfiguration/SliceSettingsWidget.cs
SlicerConfiguration/UIFields/ExtruderOffsetField.cs

- Issue MatterHackers/MCCentral#3036
Native borders appear inconsistently in SliceSettingsRows
- Issue MatterHackers/MCCentral#3035
SettingsRows should use native border implementation

Use native borders

---

ApplicationView/ApplicationController.cs
ConfigurationPage/CalibrationSettings/CalibrationControls.cs
ConfigurationPage/PrintLeveling/LevelWizard13PointRadial.cs
ConfigurationPage/PrintLeveling/LevelWizard3Point.cs
ConfigurationPage/PrintLeveling/LevelWizard3x3Mesh.cs
ConfigurationPage/PrintLeveling/LevelWizard5x5Mesh.cs
ConfigurationPage/PrintLeveling/LevelWizard7PointRadial.cs
ConfigurationPage/PrintLeveling/LevelWizardBase.cs
ConfigurationPage/PrintLeveling/PrintLevelPages.cs
ConfigurationPage/PrintLeveling/ProbeCalibrationWizard.cs
SlicerConfiguration/Settings/SettingsHelpers.cs
SlicerConfiguration/SlicerMapping/SliceEngineMapping.cs
StaticData/SliceSettings/Properties.json
Tests/MatterControl.Tests/MatterControl/SettingsParseTests.cs

issue: MatterHackers/MCCentral#2981
Make probe calibration required for pulse with probe

Made probe calibration happen automatically if required

---

ApplicationView/ApplicationController.cs
ConfigurationPage/ApplicationSettings/ApplicationSettingsView.cs
ConfigurationPage/ApplicationSettings/SettingsItem.cs
PartPreviewWindow/GCode3DWidget.cs
PartPreviewWindow/GCodeDetailsView.cs
PartPreviewWindow/ModelOptionsPanel.cs
PartPreviewWindow/View3D/PrinterBar/OverflowBar.cs
SlicerConfiguration/SettingsRow.cs
SlicerConfiguration/SliceSettingsRow.cs
SlicerConfiguration/SliceSettingsWidget.cs

Consolidate row style helpers
- Issue MatterHackers/MCCentral#3034

Consolidate row style helpers

---

ConfigurationPage/PrintLeveling/PrintLevelPages.cs

issue: MatterHackers/MCCentral#3045
Add HelpText for suggesting navigation keys in calibration wizard

Add tool tip text to leveling wizard

---

ApplicationView/ApplicationController.cs
ConfigurationPage/CalibrationSettings/CalibrationControls.cs
ConfigurationPage/PrintLeveling/InstructionsPage.cs
ConfigurationPage/PrintLeveling/LevelWizard13PointRadial.cs
ConfigurationPage/PrintLeveling/LevelWizard3Point.cs
ConfigurationPage/PrintLeveling/LevelWizard3x3Mesh.cs
ConfigurationPage/PrintLeveling/LevelWizard5x5Mesh.cs
ConfigurationPage/PrintLeveling/LevelWizard7PointRadial.cs
ConfigurationPage/PrintLeveling/LevelWizardBase.cs
ConfigurationPage/PrintLeveling/PrintLevelPages.cs
ConfigurationPage/PrintLeveling/ProbeCalibrationWizard.cs
Tests/MatterControl.Tests/MatterControl/SettingsParseTests.cs

issue: MatterHackers/MCCentral#3049
Wizard text in wrong theme colors

Fixing leveling theme colors

---

ApplicationView/ApplicationController.cs
ConfigurationPage/PrintLeveling/PrintLevelPages.cs
PrinterCommunication/PrinterConnection.cs

issue: MatterHackers/MCCentral#3078
Add long running task feedback for heating bed and extruder (109 and 190)

Reporting heating bed and extruder in long running tasks

---

ConfigurationPage/PrintLeveling/LevelWizardBase.cs
ConfigurationPage/PrintLeveling/ProbeCalibrationWizard.cs
ConfigurationPage/PrintLeveling/WizardPages/AutoProbeFeedback.cs
ConfigurationPage/PrintLeveling/WizardPages/CalibrateProbeLastPagelInstructions.cs
ConfigurationPage/PrintLeveling/WizardPages/FindBedHeight.cs
ConfigurationPage/PrintLeveling/WizardPages/GetCoarseBedHeight.cs
ConfigurationPage/PrintLeveling/WizardPages/GettingThirdPointFor2PointCalibration.cs
ConfigurationPage/PrintLeveling/WizardPages/HomePrinterPage.cs
ConfigurationPage/PrintLeveling/WizardPages/LastPagelInstructions.cs
ConfigurationPage/PrintLeveling/WizardPages/WaitForTempPage.cs
CustomWidgets/WizardControl.cs

Pages can take dependencies on the previous page data

Leveling is way better and more dynamic

---

ApplicationView/LogoSpinner.cs
ConfigurationPage/CalibrationSettings/CalibrationControls.cs
ConfigurationPage/PrintLeveling/InstructionsPage.cs
ConfigurationPage/PrintLeveling/LevelWizard13PointRadial.cs
ConfigurationPage/PrintLeveling/LevelWizard3x3Mesh.cs
ConfigurationPage/PrintLeveling/LevelWizardBase.cs
ConfigurationPage/PrintLeveling/ProbeCalibrationWizard.cs
ConfigurationPage/PrintLeveling/WizardPages/AutoProbeFeedback.cs
ConfigurationPage/PrintLeveling/WizardPages/FindBedHeight.cs
ConfigurationPage/PrintLeveling/WizardPages/FirstPageInstructions.cs
ConfigurationPage/PrintLeveling/WizardPages/GetCoarseBedHeight.cs
ConfigurationPage/PrintLeveling/WizardPages/GetUltraFineBedHeight.cs
CustomWidgets/DockingTabControl.cs
CustomWidgets/WizardControl.cs
PartPreviewWindow/Tabs.cs
PartPreviewWindow/View3D/DragDropLoadProgress.cs
PartPreviewWindow/View3D/Gui3D/MoveInZControl.cs
PartPreviewWindow/View3D/Gui3D/SnapingIndicator.cs
PartPreviewWindow/View3D/InteractionLayer.cs
PartPreviewWindow/View3D/MeshViewerWidget.cs
PartPreviewWindow/View3D/View3DWidget.cs

got the spinner to use it
refactored graphics2D -> Graphics2D in DrawEventArgs
updated (c)

Created a new animation object

---

ApplicationView/ApplicationController.cs
ConfigurationPage/PrintLeveling/LevelWizardBase.cs
ConfigurationPage/PrintLeveling/LevelingStrings.cs
ConfigurationPage/PrintLeveling/ProbeCalibrationWizard.cs

changed extruder to nozzle
issue: MatterHackers/MCCentral#3100
Heating extruder showing bed temps rather than extruder temps

Fixed bug with showing bed rather than extruder temp

---

ActionBar/TemperatureWidgetBed.cs
ActionBar/TemperatureWidgetExtruder.cs
ApplicationView/ApplicationController.cs
ConfigurationPage/PrintLeveling/LevelWizardBase.cs
ConfigurationPage/PrintLeveling/LevelingStrings.cs
ConfigurationPage/PrintLeveling/ProbeCalibrationWizard.cs
ConfigurationPage/PrintLeveling/WizardPages/FindBedHeight.cs
ConfigurationPage/PrintLeveling/WizardPages/WaitForTempPage.cs
ConfigurationPage/RunningMacroPage.cs
ControlElements/AttentionGetter.cs
CustomWidgets/InlineEditControl.cs
PartPreviewWindow/PrinterTabPage.cs
PartPreviewWindow/RoundedToggleSwitch.cs
PartPreviewWindow/View3D/MeshViewerWidget.cs

Made UiThread SetInterval return a RunningInterval
Added EaseIn EaseOut and EaseInOut to agg_basics

Made RoundedToggleSwitch play mouse down animation

---

PrinterControls/XYZJogControls.cs

issue: MatterHackers/MCCentral#3102
Don't honor movement speeds

Make move buttons update speeds when changed

---

CustomWidgets/ExportPrintItemPage.cs
Library/Export/GCodeExport.cs

- Issue MatterHackers/MCCentral#3109
Can't export from library if no printer selected

Remove printer selected guard in export page, use plugin model

---

ApplicationView/PrinterModels.cs
PartPreviewWindow/View3D/MeshViewerWidget.cs
PrinterControls/JogControls.cs

- Issue MatterHackers/MCCentral#3171
Something got messed up with baby stepping on this print

Invoke Click rather than changing Checked to ensure event fires

---

ApplicationView/PrinterModels.cs
PartPreviewWindow/GCode2DWidget.cs
PartPreviewWindow/PrinterTabPage.cs
PartPreviewWindow/View3D/BedMeshGenerator.cs

making bed re-calculate on 2d view
issue: MatterHackers/MCCentral#3117
Invalid rendering of GCode2D bed grid

using the bed image on 2d view

---

PartPreviewWindow/NewTabButton.cs
PartPreviewWindow/PartPreviewContent.cs
PartPreviewWindow/PlusTab/ExplorerBar.cs
PartPreviewWindow/Tabs.cs
Tests/MatterControl.AutomationTests/PrintingTests.cs
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

issue: MatterHackers/MCCentral#3196
Fix tests

Getting tests to pass

---

PrinterCommunication/Io/MacroProcessingStream.cs

issue: MatterHackers/MCCentral#3189
Heater shutoff timer for Load/Unload filament

turn of load unload temp with delay

---

ApplicationView/ApplicationController.cs
PartPreviewWindow/View3D/View3DWidget.cs

issue: MatterHackers/MCCentral#3209
Proposal: Rout appropriate unhandled keyboard events in Main System window to 3D view
issue: MatterHackers/MCCentral#1588
implement keyboard commands in 3d view

Made the view 3d keys happen when no other control has taken them

---

MatterControl.csproj
PartPreviewWindow/ViewControls3D.cs
SetupWizard/DesignSpaceHelp.cs

issue: MatterHackers/MCCentral#3217
Show 3D view keyboard help

Put in a quick pass at some help text.

---

ApplicationView/ThemeConfig.cs
ApplicationView/WidescreenPanel.cs
CustomWidgets/LibrarySelector/FolderBreadCrumbWidget.cs
Library/Widgets/PrintLibraryWidget.cs
PartPreviewWindow/Toolbar.cs

- Issue MatterHackers/MCCentral#3230

Improve scaling behavior

---

PartPreviewWindow/PlusTab/ExplorerBar.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

Fixing tests
issue: MatterHackers/MatterControl#3245
Add create printer message if no printers
issue: New library remove confirmation dialogs break existing tests #3229

Added 'Create printer' message

---

ApplicationView/ThemeConfig.cs
ApplicationView/WidescreenPanel.cs
Library/Widgets/PrintLibraryWidget.cs
PartPreviewWindow/PopupMenu.cs
PartPreviewWindow/View3D/PrinterBar/OverflowBar.cs

- Issue MatterHackers/MCCentral#3236
Incorrect menu size when scaled to minimum size (0.7)
- Issue MatterHackers/MCCentral#3231
Expected Folder toggle controls missing
- Issue MatterHackers/MCCentral#3230
Improve scaling behavior

Improve scaling

---

ApplicationView/ApplicationController.cs
DesignTools/Primitives/ConeObject3D.cs
DesignTools/Primitives/CubeObject3D.cs
DesignTools/Primitives/CylinderObject3D.cs
DesignTools/Primitives/HalfCylinderObject3D.cs
DesignTools/Primitives/HalfSphereObject3D.cs
DesignTools/Primitives/HalfWedgeObject3D.cs
DesignTools/Primitives/PyramidObject3D.cs
DesignTools/Primitives/RingObject3D.cs
DesignTools/Primitives/SphereObject3D.cs
DesignTools/Primitives/TextObject3D.cs
DesignTools/Primitives/TorusObject3D.cs
DesignTools/Primitives/WedgeObject3D.cs
MatterControl.csproj

grouping
colors
update button
consistency

Improving primitives

---

AboutPage/AboutPage.cs
AboutPage/ContactForm.cs
AboutPage/ContactFormPage.cs
AboutPage/HTMLParser/HtmlWidget.cs
MatterControl.csproj
SetupWizard/DialogPage.cs
SlicerConfiguration/Settings/PrinterSettings.cs

- Issue MatterHackers/MCCentral#732
Left aligned Cancel buttons?

Conversion of ContactFormWidget to DialogPage

---

Tests/MatterControl.AutomationTests/LocalLibraryTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

- Issue MatterHackers/MCCentral#3300
Many tests failing due to moved library containers

Account for new Library container b4 calibrate/library/queue tests

---

ConfigurationPage/ApplicationSettings/ApplicationSettingsView.cs
DesignTools/Operations/Align3D.cs
DesignTools/Primitives/CubeObject3D.cs
PartPreviewWindow/RoundedToggleSwitch.cs

Updated animation callback

---

ApplicationView/ApplicationController.cs
SetupWizard/DesignSpaceHelp.cs

Added a loading / progress animation that has alpha
issue: MatterHackers/MCCentral#3296
Loading animation for help gifs freezes after load and before final show

Made async load sequence do all its work on a backgroud thread

---

ApplicationView/ApplicationController.cs
DesignTools/Operations/CurveObject3D.cs

improved curve tool
issue: MatterHackers/MCCentral#3310
copy past not working in 3d view
issue: MatterHackers/MCCentral#3309
Make bend do a wrapped rotation rather than a direct rotation

Fixed copy paste (and others) in 3D view

---

DesignTools/Operations/CurveObject3D.cs

issue: MatterHackers/MCCentral#3311
Finish bend / curve tool

Made bend up and down work

---

MatterControl.OpenGL/GCodeRenderer/GCodeRenderer.cs
MatterControl.Printing/GCode/GCodeFile.cs
MatterControl.Printing/GCode/GCodeFileStreamed.cs
MatterControl.Printing/GCode/GCodeMemoryFile.cs
MatterControl.csproj
PartPreviewWindow/GCode3DWidget.cs
PartPreviewWindow/GCodeDetails/BoolOption.cs
PartPreviewWindow/GCodeDetails/GCodeDetails.cs
PartPreviewWindow/GCodeDetails/GCodeDetailsView.cs
PartPreviewWindow/GCodeDetails/GCodeLayerDetailsView.cs
PartPreviewWindow/GCodeDetails/GCodeOptionsPanel.cs
PartPreviewWindow/GCodeDetails/IToggleOption.cs

Fixed bugs with gcode parsing
Moved classes into separate files
issue: MatterHackers/MCCentral#3132
Show layer details in layer view

Got the per layer info to show up in gcode view

---

DesignTools/Operations/CurveObject3D.cs
DesignTools/Operations/PinchEditor.cs

issue: MatterHackers/MCCentral#3017
Make pinch tool use original AABB for starting bounds

Make sure we rest the meshes in pinch tool

---

DesignTools/Operations/FitToBounds3D.cs
DesignTools/PublicPropertyEditor.cs
TextCreator/Braille/BrailleObject3D.cs

still need to get lists working
issue: MatterHackers/MCCentral#3204
Need to finish implementing description tool tips on IRebuildable properties

Made tool tips show for most Public Properties

---

DesignTools/Operations/ArrayAdvanced3D.cs
DesignTools/Operations/Object3DExtensions.cs
PartPreviewWindow/View3D/MeshViewerWidget.cs
PartPreviewWindow/View3D/SceneActions.cs
PartPreviewWindow/View3D/SideBar/MirrorControls.cs
PartPreviewWindow/View3D/SideBar/ScaleControl.cs

refactoring changing signatures

Refactoring selection bounds to be in world space

---

PartPreviewWindow/GCodeDetails/GCodeDetails.cs
PartPreviewWindow/GCodeDetails/GCodeLayerDetailsView.cs

issue: MatterHackers/MCCentral#3331
Index out of range exception when loading mostly empty GCode file
issue: MatterHackers/MCCentral#3332
more layer info

improve gcode layer display:

---

PartPreviewWindow/GCode3DWidget.cs
PartPreviewWindow/GCodeDetails/GCodeDetails.cs
PartPreviewWindow/GCodeDetails/GCodeDetailsView.cs
PartPreviewWindow/GCodeDetails/GCodeLayerDetailsView.cs
PartPreviewWindow/SpeedsLegend.cs
SlicerConfiguration/SettingsRow.cs

- Issue MatterHackers/MCCentral#3375
Consider more consistent display style

Use common row style layout for GCode details

---

DesignTools/Operations/Object3DExtensions.cs
DesignTools/Primitives/TextObject3D.cs
PartPreviewWindow/SelectedObjectPanel.cs

Text object apply mantains data better (and now untility function)

Better logic around showing tree view

---

PartPreviewWindow/PartPreviewContent.cs
PartPreviewWindow/SelectedObjectPanel.cs

Highlight update button
issue: MatterHackers/MCCentral#3385
Lost Blue circles on x and y axis rotate controls
issue: MatterHackers/MCCentral#3386
lost snapping triangles on rotate z control

More work on tree view

---

PartPreviewWindow/View3D/View3DWidget.cs

Writing some test code for Gl BufferObject

Fixed a bug with selection becoming null during an operation

---

ApplicationView/ApplicationController.cs
CustomWidgets/NamedAction.cs
PartPreviewWindow/Object3DTreeBuilder.cs
PartPreviewWindow/PartTabPage.cs
PartPreviewWindow/PrinterTabPage.cs

- Issue MatterHackers/MCCentral#3416
Get operation icons on selected part tree view.

Show operation icons in treeview

---

ApplicationView/ApplicationController.cs
History/PrintHistoryData.cs
PrinterCommunication/PrinterConnection.cs

- Issue MatterHackers/MCCentral#3401
When starting print on bigger model and cancelling slice, MC freezes in "Printing" state

Handle cancelled slicing during Print operations

---

PartPreviewWindow/PrinterTabPage.cs
PartPreviewWindow/View3D/SceneActions.cs

Made the convex hull be a mesh so it is more flexible
removing dead code
issue: MatterHackers/MCCentral#3436
Make lay flat use convex hull rather than actual geometry

Made lay flat use the convex hull

---

ApplicationView/ApplicationController.cs
DesignTools/Operations/CurveObject3D.cs
DesignTools/Operations/PinchObject3D.cs
PartPreviewWindow/View3D/Actions/MeshWrapperObject3D.cs
PartPreviewWindow/View3D/SceneActions.cs
PartPreviewWindow/ViewControls3D.cs

Default pinch to have an effect immediately
Refactoring
Issues: MatterHackers/MCCentral#3446
aabb cache not updating correctly.
MatterHackers/MCCentral#3448
Curved text cannot be used as subtract source

Improvements in mesh wrapper

---

ApplicationView/ApplicationController.cs
DesignTools/Operations/Group3D.cs
MatterControl.csproj
PartPreviewWindow/Object3DTreeBuilder.cs

Made the names in the tree view better (hopefully)
issue: MatterHackers/MCCentral#3462
Make new class for group so Icon shows in tree view

Added group object

---

PartPreviewWindow/View3D/PrinterBar/PrinterActionsBar.cs
SlicerConfiguration/SliceSettingsWidget.cs

Made the names in the tree view better (hopefully)
issue: MatterHackers/MCCentral#3462
Make new class for group so Icon shows in tree view

Move import settings to settings section

---

DesignTools/Operations/CurveObject3D.cs
DesignTools/Operations/PinchObject3D.cs
PartPreviewWindow/View3D/Actions/MeshWrapperObject3D.cs
PartPreviewWindow/View3D/Actions/SubtractEditor.cs
PartPreviewWindow/View3D/Actions/SubtractObject3D.cs
PartPreviewWindow/ViewControls3D.cs

Improving curve and pinch to have more base class code sharing

---

ApplicationView/ApplicationController.cs
PartPreviewWindow/PlusTab/ExplorePanel.cs

- Issue MatterHackers/MCCentral#3473
Investigate failing LoadPublicProfileListFromCache
/ LoadProfileFromStaticData tests

Fix regression in LoadCacheable

---

DesignTools/Operations/ArrayAdvanced3D.cs
DesignTools/Operations/ArrayLinear3D.cs
DesignTools/Operations/ArrayRadial3D.cs
DesignTools/Operations/OperationSource.cs

issue: MatterHackers/MCCentral#3432
Make radial and linear array rebuild correctly

array tools are rebuilding correctly

---

DesignTools/PublicPropertyEditor.cs
PartPreviewWindow/View3D/Actions/SubtractAndReplaceObject3D.cs
PartPreviewWindow/View3D/Actions/SubtractObject3D.cs

Fixed problem with objects moving during subtract

Have transparency working on subtract again

---

ApplicationView/ApplicationController.cs
PartPreviewWindow/GCode2DWidget.cs
SetupWizard/DesignSpaceHelp.cs

issue: MatterHackers/MCCentral#3505
Mirror generating bad back faces

Fixing reverse meshes

---

CustomWidgets/TreeView/TreeNode.cs
CustomWidgets/TreeView/TreeView.cs
SetupWizard/DesignSpaceHelp.cs

- Issue MatterHackers/MCCentral#3520

Add support for text only TreeNodes

---

ApplicationView/ApplicationController.cs
DesignTools/Operations/Image/ImageToPath.cs
DesignTools/Operations/Image/LinearExtrude.cs
DesignTools/Operations/Object3DExtensions.cs
DesignTools/Operations/OperationSource.cs
DesignTools/Operations/Path/SmoothPath.cs
DesignTools/Primitives/BaseObject3D.cs
DesignTools/Primitives/ConeObject3D.cs
DesignTools/Primitives/CubeObject3D.cs
DesignTools/Primitives/CylinderObject3D.cs
DesignTools/Primitives/HalfCylinderObject3D.cs
DesignTools/Primitives/HalfSphereObject3D.cs
DesignTools/Primitives/HalfWedgeObject3D.cs
DesignTools/Primitives/PyramidObject3D.cs
DesignTools/Primitives/RingObject3D.cs
DesignTools/Primitives/SphereObject3D.cs
DesignTools/Primitives/TextObject3D.cs
DesignTools/Primitives/TorusObject3D.cs
DesignTools/Primitives/WedgeObject3D.cs

Took out object list attribute
Refactoring

Improving base object

---

Library/Widgets/ListView/ListView.cs

issue: MatterHackers/MCCentral#3550
Double Clicking on Part is unresponsive

Made double click work again

---

EeProm/EePromMarlinSettings.cs
EeProm/EePromMarlinWindow.cs

did not implement lcd brightness
issue: MatterHackers/MCCentral#3526
Reading and saving wrong values to EEPROM

Improved marlin eeprom settings

---

MatterControl.OpenGL/GCodeRenderer/RenderFeatures/RenderFeatureExtrusion.cs
PartPreviewWindow/StartPage/ExploreSection.cs
StaticData/SliceSettings/Properties.json

issue: MatterHackers/MCCentral#3591
Change 'more' button to a link to web site
issue: MatterHackers/MCCentral#3580
Extrusion width rendering error

Make the more button open the site

---

ApplicationView/ApplicationController.cs
PartPreviewWindow/View3D/Gui3D/MoveInZControl.cs
PartPreviewWindow/View3D/InteractionVolume.cs
StaticData/Translations/ar/Translation.txt
StaticData/Translations/cs/Translation.txt
StaticData/Translations/da/Translation.txt
StaticData/Translations/de/Translation.txt
StaticData/Translations/el/Translation.txt
StaticData/Translations/es/Translation.txt
StaticData/Translations/fa/Translation.txt
StaticData/Translations/fr/Translation.txt
StaticData/Translations/he/Translation.txt
StaticData/Translations/hi/Translation.txt
StaticData/Translations/it/Translation.txt
StaticData/Translations/ja/Translation.txt
StaticData/Translations/ko/Translation.txt
StaticData/Translations/nl/Translation.txt
StaticData/Translations/no/Translation.txt
StaticData/Translations/pl/Translation.txt
StaticData/Translations/ro/Translation.txt
StaticData/Translations/ru/Translation.txt
StaticData/Translations/tr/Translation.txt
StaticData/Translations/zh/Translation.txt

issue: MatterHackers/MCCentral#3590
Make 'esc' work to cancel rotation.
issue: MatterHackers/MCCentral#3570
Compute and put in new localizations

made cancel (escape key) work on more scene operations

---

PartPreviewWindow/View3D/SceneActions.cs
PrinterControls/JogControls.cs

issue: MatterHackers/MCCentral#3599
Arrow keys move printer and 3D view window

Make movement keys not move bed

---

Library/Widgets/PrintLibraryWidget.cs

- Issue MatterHackers/MCCentral#3583
'Edit' should be disabled for mesh (or do the code in the other bug
for editing meshes)

Limit Edit to mcx only

---

ApplicationView/ApplicationController.cs
DesignTools/Operations/Image/ImageToPath.cs
DesignTools/Operations/Image/LinearExtrude.cs
DesignTools/Primitives/BaseObject3D.cs

issue: MatterHackers/MCCentral#3617
Remove operation on base fails to remove

Got base able to apply and remove

---

DesignTools/Operations/Image/ImageToPath.cs
DesignTools/Operations/Path/SmoothPath.cs

issue: MatterHackers/MCCentral#3537
Write serialize path

Got path storage to serialize and de-serialize as svg d paths

---

ApplicationView/ApplicationController.cs
SetupWizard/DialogPage.cs
SlicerConfiguration/PresetSelectorWidget.cs
SlicerConfiguration/SlicePresetsWindow/SlicePresetsWindow.cs

- Issue MatterHackers/MCCentral#3639
Use DialogPage for consistent styling and behavior

Migrate SlicePresetsWindow to DialogPage

---

CustomWidgets/FlowSpacers.cs
EeProm/EePromMarlinWindow.cs
EeProm/EePromRepetierStorage.cs
EeProm/EePromRepetierWindow.cs
PartPreviewWindow/PopupMenu.cs
PartPreviewWindow/View3D/PrinterBar/OverflowBar.cs
PartPreviewWindow/View3D/PrinterBar/PrinterActionsBar.cs
SetupWizard/DialogPage.cs
SetupWizard/DialogWindow.cs

- Issue MatterHackers/MCCentral#3658
Text fields clipped by default
- Issue MatterHackers/MCCentral#3663
EEProm exports should include printer name
- Issue MatterHackers/MCCentral#3639
Use DialogPage for consistent styling and behavior

Migrate EEProm windows to DialogPage

---

ApplicationView/ApplicationController.cs
ApplicationView/PrinterModels.cs
Library/ContentProviders/MeshContentProvider.cs
Library/Widgets/ListView/ListView.cs
Library/Widgets/ListView/ListViewItemBase.cs
PartPreviewWindow/Object3DTreeBuilder.cs

Estimated memory size for mesh
Mesh Render Id
Get long hash for color
default constructor for face and vertex
issue: MatterHackers/MCCentral#3519
Improve thumbnail generation for complicated models

Created the data to allow thumbnails to be cached by mesh id

---

DesignTools/Operations/CurveObject3D.cs
DesignTools/Operations/Image/ImageToPath.cs

Made image to path adjust values to not overlap
issue: MatterHackers/MCCentral#3421
Curve tool should have a % or ratio to apply the curve at

Made curve have center ratio

---

Utilities/MarkdigAgg/AggCodeBlockRenderer.cs
Utilities/MarkdigAgg/AggHeadingRenderer.cs
Utilities/MarkdigAgg/AggListRenderer.cs
Utilities/MarkdigAgg/AggParagraphRenderer.cs
Utilities/MarkdigAgg/AggRenderer.cs

issue: MatterHackers/MCCentral#3680
Make line breaks work

Getting mark down to look more like sample site

---

CustomWidgets/SolidSlider.cs
DesignTools/Operations/Image/ImageToPathObject3D.cs

Make the histogram update when the function is changed

---

ApplicationView/ApplicationController.cs
ApplicationView/WidescreenPanel.cs
ControlElements/MHNumberEdit.cs
DesignTools/Operations/Image/ImageToPathObject3D.cs
DesignTools/Operations/Path/SmoothPathObject3D.cs
PrinterCommunication/Io/PrintRecoveryStream.cs
PrinterControls/JogControls.cs
SlicerConfiguration/SettingsRow.cs
SlicerConfiguration/SliceSettingsRow.cs
SlicerConfiguration/SliceSettingsWidget.cs

Putting in more code to track layouts
// changes to reload all with settings up
// start (Layout Calls)
19182
// making more code do LayoutLock()
19016
19014
17988
// LayoutEngineSimpleAlign line 202
// only layout parent and child once
17911
17195

Reducing number of layouts

---

DesignTools/Operations/CurveObject3D.cs
DesignTools/Operations/PinchObject3D.cs
PartPreviewWindow/View3D/SceneActions.cs

issue: MatterHackers/MCCentral#3766
pinch leaves mesh in a bed state

Making Pinch and Curve sort vertices after changing them

---

Library/Widgets/ListView/ListViewItemBase.cs

issue: MatterHackers/MCCentral#3723
Null reference exception in recently revised statement

making sure we don't try to access a null

---

ApplicationView/ApplicationController.cs
Library/Providers/LibraryConfig.cs
Tests/MatterControl.AutomationTests/PrintingTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

This makes sure we show and hide the sd card folder
issue: MatterHackers/MCCentral#3769
fix sd card print test
took out dead code

Made sure that when we change printers we update the home library

---

ApplicationView/ApplicationController.cs
DesignTools/Operations/ArrayAdvancedObject3D.cs
DesignTools/Operations/ArrayLinearObject3D.cs
DesignTools/Operations/ArrayRadialObject3D.cs
DesignTools/Operations/FitToBoundsObject3D.cs
DesignTools/Operations/Object3DExtensions.cs
DesignTools/Operations/OperationSourceObject3D.cs
DesignTools/Operations/RotateObject3D.cs

Advance array has better defaults
All Arrays set color better
Fit to Bounds has name
Selection set better on adding to internal tree view items
Operation source visible set corectly

Added rotate object to overflow menu on IObject3Ds

---

DesignTools/Primitives/ImageObject3D.cs
PartPreviewWindow/StartPage/ExplorePanel.cs
SlicerConfiguration/UIFields/IconEnumField.cs

Adjusted margin on explore page
Made enum field have consistent styling

Making less rebuilds when loading

---

Library/Widgets/InsertionGroupObject3D.cs
PartPreviewWindow/SelectedObjectPanel.cs
PartPreviewWindow/View3D/Actions/ImageEditor.cs
PartPreviewWindow/View3D/View3DWidget.cs

Got the items to be in the order of the SurfaceEditors description
Got image to send the right invalidate on image changed

Got the component object panel updating correctly

---

ApplicationView/ApplicationController.cs
MatterControl.csproj
SetupWizard/DesignSpaceHelp.cs
StaticData/OEMSettings/HelpGuides.json
Utilities/MarkdigAgg/AggRenderer.cs
Utilities/MarkdigAgg/Inlines/AggLinkInlineRenderer.cs
Utilities/MarkdigAgg/MarkdownDocument.cs
Utilities/MarkdigAgg/MarkdownPage.cs
Utilities/MarkdigAgg/MarkdownWidget.cs

- Issue MatterHackers/MCCentral#3547
Expand Help Guides to include information from top 100 Wiki pages

Remove unused fields

---

SetupWizard/DesignSpaceHelp.cs

issue: MatterHackers/MCCentral#3790
Make 'What's New' link navigate to correct tab

Set Whats New when asked

---

ApplicationView/ApplicationController.cs
PartPreviewWindow/RunningTaskRow.cs
PartPreviewWindow/View3D/SceneActions.cs

Make sure we are ready to report before starting a long running task
issue: MatterHackers/MCCentral#3827
Make ungroup a long running task
issue: MatterHackers/MCCentral#3826
ungroup mesh needs to do a clean and merge first to make sure the parts can be found

Make Ungroup a long running task

---

DesignTools/Primitives/ConeObject3D.cs
DesignTools/Primitives/CylinderObject3D.cs
DesignTools/Primitives/HalfCylinderObject3D.cs
DesignTools/Primitives/HalfSphereObject3D.cs
DesignTools/Primitives/RingObject3D.cs
DesignTools/Primitives/SphereObject3D.cs
DesignTools/Primitives/TorusObject3D.cs
DesignTools/PublicPropertyEditor.cs
SlicerConfiguration/Slicer.cs
SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs
StaticData/SliceSettings/Properties.json

Moved merge rules into  config file

Made sides of round things camp before building

---

SlicerConfiguration/Slicer.cs
SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs
StaticData/SliceSettings/Properties.json

issue: MatterHackers/MCCentral#3828
ungrouping and slicing shipwrecked benchy results in too long command string

allows extra args to be passed to slicer in config file

---

SetupWizard/HelpPage.cs
Utilities/MarkdigAgg/Inlines/AggLineBreakInlineRenderer.cs
Utilities/MarkdigAgg/MarkdownWidget.cs

Remove warning on Load redefine

Make sure markdown line breaks do a line break

---

ApplicationView/ApplicationController.cs
PartPreviewWindow/RunningTaskRow.cs
SlicerConfiguration/Slicer.cs

Removing unused code

---

DesignTools/Obsolete/FitToBoundsObject3D.cs
DesignTools/Operations/FitToBoundsObject3D_2.cs

issue: MatterHackers/MCCentral#3831
Fit to bounds has bad rotation axis' after being moved

Making fit to bounds recalculate aabb when matrix changes

---

DesignTools/Operations/FitToBoundsObject3D_2.cs

issue: MatterHackers/MCCentral#3796
Marker holder does not layout correctly

Get fit to recalculate bounds correctly

---

ApplicationView/ApplicationController.cs
PartPreviewWindow/MaterialControls.cs
PartPreviewWindow/View3D/Gui3D/SnapingIndicator.cs
PartPreviewWindow/View3D/InteractionLayer.cs
PartPreviewWindow/View3D/SceneActions.cs
PartPreviewWindow/View3D/View3DWidget.cs
Tests/MatterControl.AutomationTests/SqLiteLibraryProvider.cs

issue: MatterHackers/MCCentral#3556
Remove deprecated Scene.HasSelection property

Removed HasSelection

---

PrinterCommunication/PrinterConnection.cs

issue: MatterHackers/MCCentral#3409
Start print time after done heating

Only timing when the print is printing (not heating)

---

SetupWizard/DialogPage.cs
SlicerConfiguration/SlicerMapping/MappingClasses.cs
StaticData/SliceSettings/Properties.json
StaticData/SliceSettings/load_filament.txt
StaticData/SliceSettings/unload_filament.txt

increase loading filament grab time to 5 mins
make text wrap on dialog page if too long
issue: MatterHackers/MCCentral#3868
Filament loading timed out (90 seconds)
issue: MatterHackers/MCCentral#3644
Load Filament Wizard: Loading time remaining is not accurate
issue: MatterHackers/MCCentral#3867
wizard Text Wrapping

Show the accurate time for load and unload filament

---

ConfigurationPage/RunningMacroPage.cs
PrinterCommunication/Io/MacroProcessingStream.cs
SlicerConfiguration/SettingsOrganizer.cs
SlicerConfiguration/SliceSettingsWidget.cs
SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs
SlicerConfiguration/SlicerMapping/MappingClasses.cs
StaticData/SliceSettings/Layouts.txt
StaticData/SliceSettings/Properties.json
StaticData/SliceSettings/load_filament.txt
Utilities/MarkdigAgg/MarkdownWidget.cs

issue: MatterHackers/MCCentral#3878
Clarify what 'grabbing filament' really means during initial filament load

making the loading filament wizard use markdown rather than images

---

SetupWizard/DialogPage.cs
SlicerConfiguration/SettingsOrganizer.cs
SlicerConfiguration/SliceSettingsWidget.cs
SlicerConfiguration/UIFields/TextField.cs
StaticData/SliceSettings/Layouts.txt
StaticData/SliceSettings/Properties.json
Tests/MatterControl.Tests/MatterControl/SliceSettingsFieldTests.cs
Utilities/MarkdigAgg/AggMarkdownDocument.cs
Utilities/MarkdigAgg/AggRenderer.cs
Utilities/MarkdigAgg/MarkdownPage.cs

issue: MatterHackers/MCCentral#3881
Markdown not doing correct layout on initial layout event

added make and model and more

---

StaticData/SliceSettings/Properties.json

https://github.com/MatterHackers/MCCentral/issues/3880

Set default brim size to 8mm

---

PartPreviewWindow/View3D/TumbleCubeControl.cs
PartPreviewWindow/View3D/View3DWidget.cs

It also shows where the hit area is

Tumble cube now has edge and corner spots

---

ApplicationView/ApplicationController.cs
PartPreviewWindow/RunningTaskRow.cs

- Issue MatterHackers/MCCentral#3874
Add 'Cancel' ToolTip to long running tasks Stop button

Add Tooltip support for long running tasks

---

EeProm/EePromMarlinWindow.cs

issue: MatterHackers/MCCentral#3653
Firmware dialog clips content, needs scrollable

adding scroll to marlin eeprom window

---

PrinterControls/JogControls.cs

issue: MatterHackers/MatterControl#3571
retraction issue

Making sure initial e controls have - in retract

---

DesignTools/Operations/PinchObject3D.cs
DesignTools/Operations/TranslateObject3D.cs
PartPreviewWindow/View3D/Actions/MeshWrapperObject3D.cs
Tests/MatterControl.Tests/MatterControl/InteractiveSceneTests.cs

issue: MatterHackers/MCCentral#3859
Invalid bounding box for pattern rollers

Fixing problems with aabb on mesh modifying objects

---

SlicerConfiguration/Slicer.cs
SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs
StaticData/SliceSettings/Layouts.txt
StaticData/SliceSettings/Properties.json

issue: MatterHackers/MatterSlice#331
Try printing lowest solid top infill layer with bridging settings

Got first top layer in and working and passing tests

---

DesignTools/Operations/ScaleObject3D.cs
SlicerConfiguration/Slicer.cs

issue: MatterHackers/MCCentral#3927
Depth in scale tool is changing width

make scale depth work

---

ApplicationView/ApplicationController.cs
ApplicationView/LogoSpinner.cs
ApplicationView/PrinterModels.cs
DataStorage/ApplicationDataStorage.cs
Library/Export/MeshExport.cs
PartPreviewWindow/View3D/Gui3D/MoveInZControl.cs
Queue/OptionsMenu/PartsSheetCreator.cs
Queue/QueueData.cs
SlicerConfiguration/Slicer.cs
Tests/MatterControl.AutomationTests/PrintingTests.cs
Tests/MatterControl.Tests/MatterControl.Tests.csproj
Tests/MatterControl.Tests/MatterControl/PathTests.cs
Utilities/ProjectFileHandler.cs

MatterHackers/MCCentral#3906
Restore Object3D cache

Revise Load apis and caching 

---

StaticData/Profiles/Qidi/Tech 1.printer

Moving center point of original Qidi Tech printer.

Update Tech 1.printer

---

ApplicationView/ApplicationController.cs

- Issue MatterHackers/MCCentral#3911

Drop support for plugins within exe files

---

Library/Widgets/ListView/ListViewItemBase.cs

- Issue MatterHackers/MCCentral#3960
ListView selection behavior inconsistent with expectations

Preserve selection on selected items, require control key to unselect

---

Library/Widgets/PrintLibraryWidget.cs

- Issue MatterHackers/MCCentral#3961
Add to Plate enabled when no printer/part available

Disable Add to Plate until View3DWidget target available

---

Library/Widgets/ListView/IconListView.cs
MatterControlApplication.cs
PartPreviewWindow/View3D/MeshViewerWidget.cs
PartPreviewWindow/View3D/SceneActions.cs

- Issue MatterHackers/MCCentral#3965

Add Clipboard -> Image -> Paste support

---

DesignTools/Operations/ArrayAdvancedObject3D.cs
DesignTools/Operations/ArrayLinearObject3D.cs
DesignTools/Operations/ArrayRadialObject3D.cs
DesignTools/Operations/RotateObject3D_2.cs
DesignTools/Operations/ScaleObject3D.cs
DesignTools/Operations/TranslateObject3D.cs

issue: MatterHackers/MCCentral#3985
Changing color on a Scale node makes it go away

make set color work on types with source object

---

ApplicationView/WindowsPlatformsFeatures.cs
MatterControl.OpenGL/GCodeRenderer/GCodeRenderer.cs
PartPreviewWindow/View3D/View3DWidget.cs
RootSystemWindow.cs

Moved GL enums to files and directory

Changing GL to be a runtime connection to the output device

---

ActionBar/TemperatureWidgetExtruder.cs
ConfigurationPage/RunningMacroPage.cs
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs

issue: MatterHackers/MCCentral#4029
During load filament window X (close) does not turn off heat like cancel does

Wrote a new test to validate that system os close reports to macro page

---

PartPreviewWindow/MaterialControls.cs

issue: MatterHackers/MatterControl#3653
MC2.0 beta Material/Extruder assignment display issue with AMF

fixing material index display on radio buttons

---

MatterControl.csproj
PluginSystem/MatterControlPluginSystem.csproj
Tests/MatterControl.AutomationTests/MatterControl.AutomationTests.csproj
Tests/MatterControl.Tests/MatterControl.Tests.csproj

- Issue MatterHackers/MCCentral#4082
Errors appear in VS after successful builds due to IntelliSense problems

Convert project references to lowercase

---

StaticData/SliceSettings/load_filament.txt

The stuttering the Pulse does when loading filament was really bothering me. It makes the experience seem much less professional compared to other printers, like the Ultimaker. I did some experimenting and found a combination of distance and feed rate that make the motor run smoothly.

Fixed stuttering when loading filament

---

MatterControlLib/ApplicationView/PrinterModels.cs
MatterControlLib/CustomWidgets/ConfigurePrinterWidget.cs
MatterControlLib/CustomWidgets/DockingTabControl.cs
MatterControlLib/PartPreviewWindow/MarkdownEditPage.cs
MatterControlLib/PartPreviewWindow/PartPreviewContent.cs
MatterControlLib/PartPreviewWindow/PrinterTabPage.cs
MatterControlLib/PartPreviewWindow/Tabs.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PrinterActionsBar.cs
MatterControlLib/PrinterControls/ManualPrinterControls.cs
MatterControlLib/PrinterControls/TerminalWindow/TerminalWidget.cs
MatterControlLib/SettingsManagement/UserSettings.cs
MatterControlLib/SetupWizard/HelpPage.cs
MatterControlLib/SlicerConfiguration/SliceSettingsWidget.cs
MatterControlLib/SlicerConfiguration/UIFields/SurfacedEditorPage.cs

added ICloseableTab
changed to selected tab key
added keys to tool tabs

added close to terminal and settings (default to close)

---

MatterControl.csproj

- Issue MatterHackers/MCCentral#4104
lost our app icon

Restore application icon

---

MatterControlLib/PartPreviewWindow/PopupMenu.cs

- Issue MatterHackers/MCCentral#4110
Cut/Copy/Paste missing text

Add to, rather than overwrite flags

---

MatterControlLib/ApplicationView/PrinterModels.cs
MatterControlLib/PrinterCommunication/Drivers/Emulator/Heater.cs
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs

issue: MatterHackers/MCCentral#4112
Make Controls page visible by default

Default the controls tab to visible

---

MatterControlLib/ApplicationView/PrinterModels.cs
MatterControlLib/PartPreviewWindow/SelectedObjectPanel.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
MatterControlLib/SettingsManagement/UserSettings.cs

fixed history / properties splitter to have a ratio

Splitter can have a ration and min sizes

---

MatterControlLib/PartPreviewWindow/View3D/GridOptionsPanel.cs
MatterControlLib/PartPreviewWindow/View3D/InteractionLayer.cs
MatterControlLib/PartPreviewWindow/View3D/InteractionVolume.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
MatterControlLib/SettingsManagement/UserSettings.cs

Save and load grid options from user settings

Get grid options menu to be an icon

---

MatterControlLib/PartPreviewWindow/DropButton.cs

issue: MatterHackers/MCCentral#4150
Popup menu buttons should toggle on/off when clicked

close popup button correctly

---

MatterControlLib/PrinterCommunication/Drivers/Emulator/EmulatorPortFactory.cs
Tests/MatterControl.AutomationTests/PrintingTests.cs
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs

issue: MatterHackers/MCCentral#4173
fixing new test failurs

Fixed the test to account for changes in control names and behavior

---

MatterControl.Printing/GCode/GCodeMemoryFile.cs
MatterControlLib/PartPreviewWindow/PrinterTabPage.cs
MatterControlLib/PrinterCommunication/Io/GCodeSwitcher.cs
MatterControlLib/PrinterCommunication/Io/PrintRecoveryStream.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs

Wrote Re-Slice for dynamically replacing current gcode

---

MatterControlLib/ApplicationView/PrinterModels.cs
MatterControlLib/Library/Widgets/InsertionGroupObject3D.cs
MatterControlLib/PartPreviewWindow/PlatingHelper.cs
MatterControlLib/PartPreviewWindow/View3D/UndoCommands/InsertCommand.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs

Made insert command able to take an ienumerable
Refactoring

Made insertion group able to layout inserted objects (have a callback)

---

MatterControl.sln
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs

Building with new typography update

---

MatterControlLib/PartPreviewWindow/GCodeDetails/GCodeDetails.cs
MatterControlLib/PartPreviewWindow/GCodeDetails/GCodeDetailsView.cs

issue: MatterHackers/MCCentral#4214
If gcode time is < 30 seconds put up a warning message

put up a warning message if the loaded gcode file is very small

---

MatterControlLib/PartPreviewWindow/GCodeDetails/GCodeOptionsPanel.cs

- Issue MatterHackers / MCCentral#4211
show wireframe in gcode view not showing any results

Simplify GCode model view options to toggle switch

---

MatterControlLib/ApplicationView/PrinterModels.cs

- Issue MatterHackers/MCCentral#4250
Clear bed is no longer working

Add missing scene clear on LoadEmptyContent

---

MatterControlLib/PrinterControls/ControlWidgets/CalibrationControls.cs
MatterControlLib/PrinterControls/ControlWidgets/MacroControls.cs
MatterControlLib/SlicerConfiguration/PresetSelectorWidget.cs
MatterControlLib/SlicerConfiguration/Settings/PrinterSettings.cs
MatterControlLib/SlicerConfiguration/Settings/SettingsHelpers.cs
Tests/MatterControl.AutomationTests/ReSliceTests.cs

Refactoring MaterialPresetChanged to event
issue: MatterHackers/MCCentral#4251
Change MacrosChanged to a normal event rather than a static rooted event handler

Refactoring MacrosChanged to event

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/PrinterCommunication/Io/GCodeSwitcher.cs
MatterControlLib/PrinterCommunication/Io/MaxLengthStream.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs
MatterControlLib/SlicerConfiguration/Settings/SettingsHelpers.cs
MatterControlLib/SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs
StaticData/SliceSettings/Properties.json
Tests/MatterControl.AutomationTests/ReSliceTests.cs

Ensure we can ungroup mcx files

---

MatterControlLib/ApplicationView/PrinterModels.cs

issue: MatterHackers/MCCentral#4260
MC stops slicing/printing after 1 or 2 prints

Fixed printer clear bed bug

---

MatterControlLib/Library/Widgets/InventoryTabPage.cs
MatterControlLib/PartPreviewWindow/PartPreviewContent.cs
Tests/MatterControl.AutomationTests/PartPreviewTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

- Issue MatterHackers/MCCentral#4268
Reconsider EnsureFolderVisible as the hook for opening the 'Add Content Menu'

Fix SaveAsToQueue test

---

MatterControlLib/Library/Providers/MatterControl/LibraryCollectionContainer.cs
MatterControlLib/Library/Providers/MatterControl/PrimitivesContainer.cs
MatterControlLib/PartPreviewWindow/PartPreviewContent.cs

Experimenting with calling the 'Library' tab 'Designs'

Added primitives to the main MatterControl project

---

MatterControlLib/Library/Widgets/HardwarePage/PrinterDetails.cs
MatterControlLib/PartPreviewWindow/PartPreviewContent.cs
MatterControlLib/SettingsManagement/ApplicationSettingsPage.cs

Add missing namespace, add conditional compilation to for missing Markdig support

Fix Android

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/Library/Widgets/LibraryWidget.cs
MatterControlLib/PartPreviewWindow/PartPreviewContent.cs
MatterControlLib/PartPreviewWindow/Tabs.cs

**New landing page on first run or no printer**

Revise tabs and startup

---

MatterControlLib/CustomWidgets/ResizeContainer/VerticalResizeContainer.cs
MatterControlLib/PartPreviewWindow/PopupButton.cs
MatterControlLib/PartPreviewWindow/ViewControls3D.cs
MatterControlLib/SettingsManagement/UserSettings.cs

issue: MatterHackers/MCCentral#4296
Make library popup resizable

Getting the library popup to be vertically scale-able

---

MatterControl.OpenGL/GCodeRenderer/RenderFeatures/RenderFeatureTravel.cs
MatterControl.Printing/GCode/GCodeFile.cs
MatterControlLib/SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs
StaticData/SliceSettings/Layouts.txt
StaticData/SliceSettings/Properties.json

mad travel render transparent
fixed layer identification in ms gcode

Adding coast at end

---

MatterControlLib/Library/Widgets/HardwarePage/PrinterDetails.cs
MatterControlLib/SlicerConfiguration/Settings/SettingsHelpers.cs
MatterControlLib/SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs
StaticData/SliceSettings/Layouts.txt
StaticData/SliceSettings/Properties.json

issue: MatterHackers/MCCentral#4302
Remove SID from printer settings

removing the SID

---

MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
MatterControlLib/PartPreviewWindow/ViewControls3D.cs
Tests/MatterControl.AutomationTests/LibraryContainerTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

Added the bed menu back and called it 'File'
Made cut copy past enable correctly in bed menu

Getting more tests to pass

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ConfigurationPage/PrintLeveling/PrintLevelingData.cs
MatterControlLib/ConfigurationPage/PrintLeveling/PrintLevelingWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/ProbeCalibrationWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/LastPageInstructions.cs
MatterControlLib/SlicerConfiguration/SlicerMapping/EngineMappingMatterSlice.cs

issue: MatterHackers/MCCentral#4336
If setup needs to calibrate both the probe and the bed, heat both
issue: MatterHackers/MCCentral#4337
If temp changes too much from leveling temp, warn rather than require leveling

Improving initial setup process.

---

MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
MatterControlLib/PartPreviewWindow/ViewControls3D.cs

issue: MatterHackers/MCCentral#4342
Save as not working from toolbar
issue: MatterHackers/MCCentral#4343
No right click bed menu

Fixing 'File' removal regressions

---

MatterControlLib/PrinterCommunication/Io/GCodeSwitcher.cs

Marlin firmware explicitly does not run out the command queue when switching e
this means we potentially have queue instructions with the wrong e position

Ensure we exhaust the command buffer before we switch E positions

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ControlElements/MHDropDownList.cs
MatterControlLib/Library/ContentProviders/MeshContentProvider.cs
MatterControlLib/Library/Widgets/ListView/ListViewItemBase.cs

- Issue MatterHackers/MCCentral#4347
Fix thumbnail centering for missing item

Resize meshContentProvider result if required, fix SetUnsized bug

---

MatterControlLib/PrinterCommunication/Io/PrintLevelingStream.cs

issue: MatterHackers/MCCentral#2179
Mark exported gcode files that have leveling as such and don't apply again

Make leveling read and write a status to gcode files

---

MatterControlLib/PartPreviewWindow/View3D/SceneActions.cs
MatterControlLib/PartPreviewWindow/ViewControls3D.cs

issue: MatterHackers/MCCentral#4354
Center parts when plating if needed

Make sure we arrange parts on print if they will not fit

---

MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs

- Issue MatterHackers/MCCentral#4312
Finish Part -> Print Implementation

Show select printer page if no active printer but some exist

---

MatterControlLib/ApplicationView/ThumbnailsConfig.cs
MatterControlLib/Library/Widgets/ListView/IconListView.cs

Set the bender the same for all thumbnails

Fixing the flow layout of the library

---

StaticData/Themes/System/Modern/Modern-Dark.json
StaticData/Themes/System/Solarized/Solarized-Dark.json
StaticData/Themes/System/Solarized/Solarized-Light.json

- Issue MatterHackers/MCCentral#4386
Default color on theme should be blue

Adjust theme default accent colors

---

MatterControlLib/Library/Widgets/ExpandCheckboxButton.cs
MatterControlLib/PartPreviewWindow/RunningTaskRow.cs
MatterControlLib/SettingsManagement/ApplicationSettingsPage.cs

- Issue MatterHackers/MCCentral#4411

Disable RunningTaskRow expansion if lacking RichProgressWidget

---

MatterControlLib/PartPreviewWindow/ItemColorButton.cs
MatterControlLib/PartPreviewWindow/ItemMaterialButton.cs
MatterControlLib/PartPreviewWindow/MaterialControls.cs

issue: MatterHackers/MCCentral#4402
Material button not synced to current

Fixing material selector

---

MatterControlLib/ConfigurationPage/PrintLeveling/PrintLevelingWizard.cs
MatterControlLib/Library/Widgets/HardwarePage/PrinterDetails.cs
StaticData/SliceSettings/load_filament.txt
StaticData/SliceSettings/unload_filament.txt

Took out the filament selection in leveling
Made our load and unload scripts work correctly with repetier firmware
issue: MatterHackers/MCCentral#4315
Need Loading overlay when adding or switching to a printer

Made a Loading... overlay when changing printers

---

MatterControlLib/PartPreviewWindow/PopupMenu.cs

issue: MatterHackers/MCCentral#4427
Draw border around popup content of anchor widget open color

Made a border on PopupMenu

---

MatterControlLib/Library/Widgets/HardwarePage/PrinterDetails.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
MatterControlLib/PrinterControls/PrinterConnections/SelectPrinterPage.cs

- Issue MatterHackers/MCCentral#4478
When we open a printer from the select menu after clicking print
on a design tab, we don't get the part on the bed

Wait for async printer load before copying part bed plate

---

MatterControlLib/PartPreviewWindow/ItemColorButton.cs
MatterControlLib/PartPreviewWindow/ItemMaterialButton.cs
MatterControlLib/SlicerConfiguration/UIFields/ColorField.cs

- Issue MatterHackers/MCCentral#4507

Use theme border colors

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/PartPreviewWindow/MainViewWidget.cs

- Issue MatterHackers/MCCentral#4526
Sign out switches to Store page

Add mechanism to track and restore to printer tab after sign in/out

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/RootSystemWindow.cs
Program.cs

issue: MatterHackers/MCCentral#4318
Part tab fails to persist on close

Made it so we save all work spaces before exit

---

MatterControlLib/ActionBar/TemperatureWidgetExtruder.cs
MatterControlLib/ConfigurationPage/PrintLeveling/LevelingStrings.cs
MatterControlLib/ConfigurationPage/PrintLeveling/ProbeCalibrationWizard.cs
MatterControlLib/CustomWidgets/PrintingWindow/ExtruderStatusWidget.cs

Add new page to probe calibration

issue: MatterHackers/MCCentral#3458

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ApplicationView/PrinterModels.cs
MatterControlLib/CustomWidgets/NamedAction.cs
MatterControlLib/PartPreviewWindow/View3D/SceneActions.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
MatterControlLib/PartPreviewWindow/ViewControls3D.cs

 Remove InsertNewItem coupling to ActivePrinter

---

MatterControlLib/ConfigurationPage/LanguageSelector.cs
MatterControlLib/Library/Export/GCodeExport.cs
MatterControlLib/PrinterCommunication/Io/BabyStepsStream.cs
MatterControlLib/PrinterCommunication/Io/ExtrusionMultiplyerStream.cs
MatterControlLib/PrinterCommunication/Io/FeedRateMultiplyerStream.cs
MatterControlLib/PrinterCommunication/Io/GCodeFileStream.cs
MatterControlLib/PrinterCommunication/Io/GCodeStream.cs
MatterControlLib/PrinterCommunication/Io/GCodeStreamProxy.cs
MatterControlLib/PrinterCommunication/Io/GCodeSwitcher.cs
MatterControlLib/PrinterCommunication/Io/MaxLengthStream.cs
MatterControlLib/PrinterCommunication/Io/NotPrintingStream.cs
MatterControlLib/PrinterCommunication/Io/OffsetStream.cs
MatterControlLib/PrinterCommunication/Io/PauseHandlingStream.cs
MatterControlLib/PrinterCommunication/Io/PrintLevelingStream.cs
MatterControlLib/PrinterCommunication/Io/PrintRecoveryStream.cs
MatterControlLib/PrinterCommunication/Io/ProcessWriteRegExStream.cs
MatterControlLib/PrinterCommunication/Io/QueuedCommandsStream.cs
MatterControlLib/PrinterCommunication/Io/RelativeToAbsoluteStream.cs
MatterControlLib/PrinterCommunication/Io/RequestTemperaturesStream.cs
MatterControlLib/PrinterCommunication/Io/SendProgressStream.cs
MatterControlLib/PrinterCommunication/Io/WaitForTempStream.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs
StaticData/Translations/cr/Translation.txt
Tests/MatterControl.Tests/MatterControl/GCodeStreamTests.cs

issue: MatterHackers/MCCentral#4562
GCodeStream

Removed active printer static

---

MatterControlLib/AboutPage/CacheDirectory.cs
MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ApplicationView/BedConfig.cs
MatterControlLib/ApplicationView/EditContext.cs
MatterControlLib/ApplicationView/PrinterConfig.cs
MatterControlLib/Library/Export/GCodeExport.cs
MatterControlLib/PartPreviewWindow/PrinterTabPage.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/SliceButton.cs
MatterControlLib/Queue/PrintItemWrapper.cs

issue: MatterHackers/MCCentral#4574

remove active printer from PrintItemWrapper

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs

issue: MatterHackers/MCCentral#4582

Remove PrintingItemName from application controller

---

MatterControlLib/Library/Export/GCodeExport.cs
MatterControlLib/PrinterCommunication/Io/GCodeSwitcher.cs
MatterControlLib/PrinterCommunication/Io/OffsetStream.cs
MatterControlLib/PrinterCommunication/Io/ProcessWriteRegExStream.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs

issue: MatterHackers/MCCentral#4596
Retracting filament at end of print

Making sure that export does the right thing on G92

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs

Make Connection OnIdle work for multiple printers

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/PrinterControls/ControlWidgets/MacroControls.cs
MatterControlLib/SlicerConfiguration/Settings/PrinterSettings.cs

- Issue MatterHackers/MCCentral#4549
Remove ActivePrinter from ApplicationController

Remove ActivePrinter references

---

MatterControlLib/ApplicationView/PrinterConfig.cs
MatterControlLib/Library/Export/GCodeExport.cs

issue: MatterHackers/MCCentral#4625
Changing the scene objects (position) not causing slice to re-calculate

Make sure we use the sha1 of the MCX so we rebuild correctly

---

MatterControlLib/SlicerConfiguration/Settings/PrinterSettings.cs

issue: MatterHackers/MCCentral#4631
Remove PrinterConnection dependency in PrinterSettings.SetMaterialPreset

Removing PrinterCommunication from ActiveMaterialKey

---

MatterControlLib/ApplicationView/BedConfig.cs

- Issue MatterHackers/MCCentral#4626
When add item on double click - switch to model view (like drag)

Always switch to Model view when items are added to bed

---

MatterControl.csproj
MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/PartPreviewWindow/MainViewWidget.cs
Program.cs

- Issue MatterHackers/MCCentral#4591
Make MC run single instance
- Issue MatterHackers/MCCentral#4638
Open passed in stl files to a new design tab

Add experimental shell support

---

MatterControlLib/ApplicationView/SettingsValidation.cs
MatterControlLib/SetupWizard/TourOverlay.cs

issue: MatterHackers/MCCentral#4641
Consider adding constraints to line lengths in gcode fields

ensuring good slice settings

---

MatterControlLib/SetupWizard/DialogPage.cs
MatterControlLib/SetupWizard/WelcomePage.cs

issue: MatterHackers/MCCentral#4647
Consider showing welcome screen until the user opts-out

making welcome page more persistent

---

MatterControlLib/PrinterCommunication/PrinterConnection.cs
Tests/MatterControl.Tests/MatterControl/GCodeProcessingTests.cs

- Issue MatterHackers/MCCentral#4648
Not showing T1 actual temp on Smoothie Dual Pulse

Add test for Smoothie dual extruder response format

---

MatterControlLib/PrinterCommunication/Io/BabyStepsStream.cs
MatterControlLib/PrinterCommunication/Io/ExtrusionMultiplyerStream.cs
MatterControlLib/PrinterCommunication/Io/FeedRateMultiplyerStream.cs
MatterControlLib/PrinterCommunication/Io/MaxLengthStream.cs
MatterControlLib/PrinterCommunication/Io/OffsetStream.cs
MatterControlLib/PrinterCommunication/Io/PauseHandlingStream.cs
MatterControlLib/PrinterCommunication/Io/PrintLevelingStream.cs
MatterControlLib/PrinterCommunication/Io/ProcessWriteRegExStream.cs
MatterControlLib/PrinterCommunication/Io/RelativeToAbsoluteStream.cs
MatterControlLib/PrinterCommunication/Io/WaitForTempStream.cs
MatterControlLib/SlicerConfiguration/UIFields/ExtruderOffsetField.cs
StaticData/SliceSettings/Properties.json

issue: MatterHackers/MCCentral#4663
set position Z Tower and no Level

put in the ability to specify "; NO_PROCESSING" on a gcode line

---

MatterControlLib/ActionBar/TemperatureWidgetExtruder.cs
MatterControlLib/ApplicationView/ApplicationController.cs

Make it possible to export gcode without selecting material.

Make it possible to set material when not connected

---

StaticData/License/libigl.txt
StaticData/License/license.json

issue: MatterHackers/MCCentral#4633
add libigl to about page

adding libigl to about

---

MatterControlLib/PrinterCommunication/PrinterConnection.cs
MatterControlLib/SlicerConfiguration/Slicer.cs

issue: MatterHackers/MCCentral#4668
Send T0 on manual extrude on dual extruder machines

Make sure we are always on the right extruder before extruding

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/Library/Export/GCodeExport.cs
MatterControlLib/PrinterCommunication/Drivers/X3G/X3GExport.cs

issue: MatterHackers/MCCentral#4643
Export dumps users to empty Select Printer page

improving export dialog and options

---

MatterControlLib/Library/Export/GCodeExport.cs

issue: MatterHackers/MCCentral#4675
Massive extrudes ramping up to z-max
issue: MatterHackers/MCCentral#4674
Over retract on last layer

Make sure we track positions correctly over relative moves

---

MatterControlLib/PartPreviewWindow/Tabs.cs
MatterControlLib/PrinterControls/ControlWidgets/MovementControls.cs

issue: MatterHackers/MCCentral#4685
Can middle click hardware library and store tabs

Don't middle click close tabs that don't have close buttons

---

MatterControlLib/ActionBar/TemperatureWidgetBed.cs
MatterControlLib/ActionBar/TemperatureWidgetExtruder.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PrinterActionsBar.cs
MatterControlLib/PrinterControls/ControlWidgets/MovementControls.cs
MatterControlLib/PrinterControls/ControlWidgets/TemperatureControls.cs
MatterControlLib/PrinterControls/ManualPrinterControls.cs

issue: MatterHackers/MCCentral#4687
consider adding hotend and bed controls back onto settings page

moved temp to controls panel as imbedded popup menus

---

MatterControl.Winforms/InspectForm.cs
MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ApplicationView/PrinterConfig.cs
MatterControlLib/CustomWidgets/SingleWindowProvider.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PrinterActionsBar.cs
MatterControlLib/RootSystemWindow.cs
MatterControlLib/SettingsManagement/ApplicationSettingsPage.cs

- Make ReloadAll async
- Issue MatterHackers/MCCentral#4698
Open tabs should track users after sign in/out

Extract opentabs loading to method, invoke on sign out/in

---

MatterControlLib/PartPreviewWindow/MainViewWidget.cs
MatterControlLib/RootSystemWindow.cs

- Accidently restored during merges before pull request
- Issue MatterHackers/MCCentral#4702
Switching theme results duplicated and invalid tabs

Remove invalid tab creation logic

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ApplicationView/PartWorkspace.cs
MatterControlLib/ApplicationView/WrappedLibraryContainer.cs
MatterControlLib/Library/Providers/SDCard/OpenPrintersContainer.cs
MatterControlLib/Library/Providers/SDCard/PrinterContainer.cs
MatterControlLib/Library/Providers/SDCard/SDCardContainer.cs
MatterControlLib/Library/Widgets/LibraryWidget.cs
MatterControlLib/Library/Widgets/PrintLibraryWidget.cs
MatterControlLib/PartPreviewWindow/MainViewWidget.cs
MatterControlLib/PartPreviewWindow/PartTabPage.cs
MatterControlLib/PartPreviewWindow/PrinterTabPage.cs
MatterControlLib/PartPreviewWindow/ViewControls3D.cs
MatterControlLib/SetupWizard/TourOverlay.cs

- Issue MatterHackers/MCCentral#4586
remove activeprinter from SDCardContainer

Add per workspace library context 

---

MatterControlLib/PrinterControls/TerminalWindow/TextScrollWidget.cs

https://github.com/MatterHackers/MCCentral/issues/1392

Made Page Up & Page Down keys work in terminal

---

MatterControlLib/PrinterControls/PrinterConnections/SetupStepMakeModelName.cs

- Delete empty LoadCalibrationPrints()

Remove dead code

---

MatterControlLib/Library/Export/GCodeExport.cs
MatterControlLib/PrinterCommunication/Io/GCodeStream.cs
MatterControlLib/PrinterCommunication/Io/OffsetStream.cs
MatterControlLib/PrinterCommunication/Io/PrinterMove.cs
MatterControlLib/PrinterCommunication/Io/RemoveCommentsStream.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs
Tests/MatterControl.Tests/MatterControl/GCodeStreamTests.cs

More GCode export tests
issue: MatterHackers/MCCentral#4736
Start G-Code corrupted when exporting .gcode file

More GCode export fixes

---

MatterControlLib/PartPreviewWindow/View3D/Actions/SubtractAndReplaceObject3D.cs
MatterControlLib/PartPreviewWindow/View3D/MeshViewerWidget.cs

also improved subtract and replace

Fixing render issues with subtract

---

MatterControlLib/PartPreviewWindow/View3D/Actions/MeshWrapperObject3D.cs
Tests/MatterControl.Tests/MatterControl/InteractiveSceneTests.cs

issue: atterHackers/MCCentral#4766
undo after subtract and replace leaves extra copy of item

Fixing remove for MeshWrapperObjects

---

MatterControlLib/Library/Widgets/ListView/LibraryListView.cs

issue: MatterHackers/MCCentral#4785
fresh install starts with favorites scrolled down

Make the list view start out with correct scrolling

---

MatterControlLib/PrinterCommunication/PrinterConnection.cs
Tests/MatterControl.Tests/MatterControl/GCodeStreamTests.cs

issue: MatterHackers/MCCentral#4799
Doesn't print with Smoothie Pulse

fixing issue with adding line to terminal modifying line to printer

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/DesignTools/Attributes/HideFromTreeViewAttribute.cs
MatterControlLib/DesignTools/Attributes/ImmutableAttribute.cs
MatterControlLib/DesignTools/Operations/FitToBoundsObject3D_2.cs
MatterControlLib/DesignTools/Operations/PinchObject3D.cs
MatterControlLib/DesignTools/Operations/TransformWrapperObject3D.cs
MatterControlLib/PartPreviewWindow/GenerateSupportPanel.cs
MatterControlLib/PartPreviewWindow/View3D/Actions/MeshWrapperObject3D.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
Tests/MatterControl.Tests/MatterControl/InteractiveSceneTests.cs

added Immutable Attribute
added Hide From Tree View Attribute
issue: MatterHackers/MCCentral#4806
support remove does not update tree view

Made Object3D listen for and update on Children modified

---

MatterControl.csproj
MatterControlLib/Library/BufferLibraryItem.cs
MatterControlLib/Library/Interfaces/ILibraryItem.cs
MatterControlLib/Library/Interfaces/LibraryExtensionMethods.cs
MatterControlLib/Library/OnDemandLibraryItem.cs
MatterControlLib/Library/RemoteLibraryItem.cs
MatterControlLib/Library/Widgets/LibraryWidget.cs
MatterControlLib/Library/Widgets/PrintLibraryWidget.cs
MatterControlLib/MatterControlLib.csproj
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
Program.cs

- Issue MatterHackers/MCCentral#4798
Add support for drag drop image url

Initial support for drag from Chrome

---

MatterControlLib/DesignTools/Operations/CurveObject3D.cs
MatterControlLib/DesignTools/Operations/ScaleObject3D.cs
MatterControlLib/PartPreviewWindow/GenerateSupportPanel.cs

Made a face struct and made face list use it

---

MatterControlLib/DesignTools/Operations/RotateObject3D_2.cs
MatterControlLib/DesignTools/Operations/ScaleObject3D.cs
MatterControlLib/DesignTools/Operations/TransformWrapperObject3D.cs
Tests/MatterControl.Tests/MatterControl/InteractiveSceneTests.cs

Fixing translation error in scale

---

MatterControl.Printing/Settings/SliceSettingsFields.cs
MatterControlLib/ControlElements/MHNumberEdit.cs
MatterControlLib/DesignTools/Operations/CurveObject3D.cs
MatterControlLib/SlicerConfiguration/Slicer.cs
MatterControlLib/SlicerConfiguration/UIFields/Vector2Field.cs
MatterControlLib/SlicerConfiguration/UIFields/Vector3Field.cs

- Issue MatterHackers/MCCentral#4805
Consider embedded single char labels

Add embedded label option

---

MatterControlLib/MatterControlLib.csproj
Tests/MatterControl.Tests/MatterControl/InteractiveSceneTests.cs

Improved GetLongHashCode for vectors
Make sure CreatHulMesh does not crash on 0 size meshes
Upgraded MIConvexHull

Fixed combine and subtract tests

---

MatterControlLib/SlicerConfiguration/SliceSettingsWidget.cs
Program.cs
Tests/MatterControl.AutomationTests/MatterControlTests.cs

- Add missing test validating printer count after ReloadAll 
- Revise for changes since creation

Validate printer count after ReloadAll

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/DesignTools/Operations/RotateObject3D_2.cs
MatterControlLib/DesignTools/Operations/ScaleObject3D.cs
MatterControlLib/DesignTools/Primitives/TextObject3D.cs
Tests/MatterControl.Tests/MatterControl/InteractiveSceneTests.cs

issue: MatterHackers/MCCentral#4818
MatterHackers/MCCentral#4802 Can't add to inner combine content as expected (write another test)

Fixed rotate object 2 to have correct aabb on construction

---

MatterControlLib/DesignTools/PublicPropertyEditor.cs
MatterControlLib/DesignTools/SupportGenerator.cs
MatterControlLib/PartPreviewWindow/GenerateSupportPanel.cs
MatterControlLib/SettingsManagement/UserSettings.cs

Made 'support type' work selectable

Support has first release quality

---

MatterControlLib/ApplicationView/SettingsValidation.cs
MatterControlLib/Library/Export/GCodeExport.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PrintPopupMenu.cs

- Issue MatterHackers/MCCentral#4884

Split print and slice validation to reduce non-relevant reporting

---

MatterControlLib/DesignTools/Operations/OperationSourceObject3D.cs
MatterControlLib/PartPreviewWindow/View3D/Actions/CombineObject3D.cs

Fix combine position

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/DesignTools/Braille/BrailleCardObject3D.cs
MatterControlLib/DesignTools/Operations/PinchObject3D.cs
MatterControlLib/DesignTools/Primitives/CubeObject3D.cs
MatterControlLib/PartPreviewWindow/View3D/Actions/CombineObject3D.cs
Tests/MatterControl.Tests/MatterControl/InteractiveSceneTests.cs
Tests/MatterControl.Tests/MatterControl/MeshRebuildTests.cs

Fixed a bug with multiple items in combine

Get pinch to use new source pattern

---

MatterControlLib/DesignTools/Obsolete/CombineObject3D.cs
MatterControlLib/DesignTools/Obsolete/CurveObject3D.cs
MatterControlLib/DesignTools/Obsolete/FitToBoundsObject3D.cs
MatterControlLib/DesignTools/Obsolete/IntersectionObject3D.cs
MatterControlLib/DesignTools/Obsolete/MirrorObject3D.cs
MatterControlLib/DesignTools/Obsolete/PinchObject3D.cs
MatterControlLib/DesignTools/Obsolete/RotateObject3D.cs
MatterControlLib/DesignTools/Operations/FitToBoundsObject3D_2.cs

Making it easier to see that you have opened the obsolete version of a file

Improving fit to bounds default position on rebuild

---

MatterControlLib/PartPreviewWindow/View3D/SceneActions.cs

Also improved it to look for the largest face now that we have triangles
This was the intent before but the move to simple mesh lost it and it
was never as accurate as the new method.
issue: MatterHackers/MCCentral#4954
Lay flat should be un-doable

Make lay flat un-doable

---

MatterControlLib/DesignTools/Primitives/ConeObject3D.cs

- Issue MatterHackers/MCCentral#4968
Cone thumbnail fails to generate

Await async Rebuild call

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/DesignTools/Operations/FitToBoundsObject3D_2.cs
MatterControlLib/DesignTools/Operations/RotateObject3D_2.cs
MatterControlLib/DesignTools/Operations/ScaleObject3D.cs
MatterControlLib/DesignTools/Operations/TransformWrapperObject3D.cs
MatterControlLib/DesignTools/Operations/TranslateObject3D.cs
MatterControlLib/PartPreviewWindow/Object3DTreeBuilder.cs
Tests/MatterControl.Tests/MatterControl/InteractiveSceneTests.cs

Made Transform Wrapper Object work with list
issue: MatterHackers/MCCentral#4979
Crash when scaling model with support

Fixed rotate, scale, translate to work with multiple objects

---

MatterControlLib/DesignTools/SupportGenerator.cs
MatterControlLib/PartPreviewWindow/View3D/UndoCommands/DeleteCommand.cs

issue: MatterHackers/MCCentral#4978
Cannot remove support after saving and reopening design

Make all the supports remove when we ask to remove supports

---

MatterControlLib/ActionBar/TemperatureWidgetExtruder.cs
MatterControlLib/SlicerConfiguration/PresetSelectorWidget.cs

Put a shop button in the extruder menu

Put in a shop button

---

MatterControl.Printing/Settings/SettingsHelpers.cs
MatterControlLib/ActionBar/TemperatureWidgetBase.cs
MatterControlLib/ActionBar/TemperatureWidgetBed.cs
MatterControlLib/ActionBar/TemperatureWidgetExtruder.cs
MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ApplicationView/PrinterConfig.cs
MatterControlLib/ConfigurationPage/PrintLeveling/LoadFilamentWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/ProbeCalibrationWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/UnloadFilamentWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/AutoProbeFeedback.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/CalibrateProbeLastPagelInstructions.cs
MatterControlLib/Library/Providers/SDCard/SDCardContainer.cs
MatterControlLib/PartPreviewWindow/PrinterTabPage.cs
MatterControlLib/PartPreviewWindow/Tabs.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PrinterConnectButton.cs
MatterControlLib/PrinterCommunication/Io/OffsetStream.cs
MatterControlLib/PrinterCommunication/Io/PauseHandlingStream.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs
MatterControlLib/PrinterControls/ControlWidgets/CalibrationControls.cs
MatterControlLib/RootSystemWindow.cs
MatterControlLib/SlicerConfiguration/PresetSelectorWidget.cs

issue: MatterHackers/MCCentral#4880
Calibrate extruder 2 z offset
issue: MatterHackers/MCCentral#5014
Make switch extruders (T0, T1) do the MatterControl required actions (switch) to be functional

extruder 2 z calibration

---

MatterControl.Printing/GCode/GCodeMemoryFile.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/WaitForTempPage.cs
MatterControlLib/PrinterCommunication/Io/QueuedCommandsStream.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs

issue: MatterHackers/MCCentral#5044
When printing only with extruder 2, MC waits for extruder 1 to heat to 0 degrees
issue: MatterHackers/MCCentral#5043
Load filament wizard for filament 2 does not finish

Fixing problems with heating extruder 2

---

MatterControl.Printing/Settings/SettingsHelpers.cs
MatterControl.Printing/Settings/SettingsKey.cs
MatterControl.Printing/Settings/SliceSettingsFields.cs
MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ApplicationView/SettingsValidation.cs
MatterControlLib/ConfigurationPage/PrintLeveling/LoadFilamentWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/PrintLevelingWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/LastPageInstructions.cs
MatterControlLib/DataStorage/Models.cs
MatterControlLib/DesignTools/Operations/FitToCylinderObject3D.cs
MatterControlLib/DesignTools/Operations/Image/ImageToPathObject3D.cs
MatterControlLib/DesignTools/Primitives/BaseObject3D.cs
MatterControlLib/PartPreviewWindow/View3D/Actions/ImageEditor.cs
MatterControlLib/PrinterCommunication/Io/BabyStepsStream.cs
MatterControlLib/PrinterCommunication/Io/OffsetStream.cs
MatterControlLib/PrinterCommunication/Io/WaitForTempStream.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs
MatterControlLib/PrinterControls/ControlWidgets/MovementControls.cs
MatterControlLib/PrinterControls/EditLevelingSettingsPage.cs
MatterControlLib/PrinterControls/JogControls.cs

issue: MatterHackers/MCCentral#5053
verify baby stepping not affecting probe calibration

baby stepping working on extruder 2

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/PartPreviewWindow/View3D/Actions/SubtractAndReplaceObject3D_2.cs
MatterControlLib/PartPreviewWindow/View3D/Actions/SubtractObject3D_2.cs

issue: MatterHackers/MCCentral#4929
Move away from mesh wrapper to source item

Finishing up subtract and replace

---

MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/PrintLevelingWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/ProbeCalibrationWizard.cs

- Restore original baby stepping value when cancelling wizard
- Issue MatterHackers/MCCentral#5091
Babystepping not cleared after running probe calibration wizard

Revise when baby stepping is cleared

---

StaticData/OEMSettings/ProductTour.json

Update ProductTour.json grammar

---

MatterControl.OpenGL/GCodeRenderer/GCodeRenderer.cs
MatterControl.OpenGL/GCodeRenderer/RenderFeatures/RenderFeatureBase.cs
MatterControl.OpenGL/GCodeRenderer/RenderFeatures/RenderFeatureExtrusion.cs
MatterControl.OpenGL/GCodeRenderer/RenderFeatures/RenderFeatureRetract.cs
MatterControl.OpenGL/GCodeRenderer/RenderFeatures/RenderFeatureTravel.cs
MatterControl.Printing/GCode/GCodeFile.cs
MatterControl.Printing/GCode/GCodeMemoryFile.cs
MatterControlLib/Library/Export/GCodeExport.cs
MatterControlLib/PartPreviewWindow/GCodeDetails/GCodeDebugView.cs
MatterControlLib/PrinterCommunication/Io/HotendTemperatureStream.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs

In the gcode line view show time to next extruder switch
refactored gcode memory file
gcode render features keep track of their gcode line index
issue: MatterHackers/MCCentral#4679
Turn off hot end temp if not used for remainder of print

added a hotend temperature stream

---

MatterControl.Printing/Settings/PrinterSettings.cs
MatterControlLib/SlicerConfiguration/PresetSelectorWidget.cs
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs

- Issue MatterHackers/MCCentral#5125
CopyFrom fails to copy all properties
- Issue MatterHackers/MCCentral#5122
MaterialSettingsKey listed more than once
- Issue MatterHackers/MCCentral#5084
Brim settings do not enable

Fix Sync regressions

---

MatterControlLib/ActionBar/TemperatureWidgetBed.cs
MatterControlLib/ActionBar/TemperatureWidgetExtruder.cs
MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/LoadFilamentWizard.cs

- Issue MatterHackers/MCCentral#4867
Can't turn off extruder during printing, can't adjust bed temperature

Enable heater toggles while printing

---

MatterControlLib/ApplicationView/Themes/ThemeConfig.cs
MatterControlLib/ApplicationView/Themes/ThemeSet.cs
MatterControlLib/ControlElements/MHDropDownList.cs
MatterControlLib/PartPreviewWindow/DropButton.cs
MatterControlLib/PartPreviewWindow/PopupMenuButton.cs
MatterControlLib/PartPreviewWindow/SystemWindowExtension.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PrintPopupMenu.cs
MatterControlLib/PartPreviewWindow/ViewControls3D.cs
StaticData/Themes/System/Classic/Classic-Dark.json
StaticData/Themes/System/Classic/Classic-Light.json
StaticData/Themes/System/Light/Light-White.json
StaticData/Themes/System/Menus/White-Menu.json
StaticData/Themes/System/Modern/Modern-Dark-Menu.json
StaticData/Themes/System/Modern/Modern-Dark.json
StaticData/Themes/System/Solarized/Solarized-Dark.json
StaticData/Themes/System/Solarized/Solarized-Light-Menu.json
StaticData/Themes/System/Solarized/Solarized-Light.json

- Issue MatterHackers/MCCentral#5145
Improve popup styling

Only show mouse down/highlight colors when popup closed

---

MatterControl.Printing/Settings/SettingsKey.cs
MatterControl.Printing/Settings/SliceSettingsFields.cs
MatterControlLib/SlicerConfiguration/EngineMappingMatterSlice.cs
StaticData/SliceSettings/Layouts.txt

- Issue MatterHackers/MCCentral#5006

Add interface layer speed

---

MatterControlLib/CustomWidgets/GCodeSketch.cs
MatterControlLib/CustomWidgets/NozzleOffsetCalibrationPage.cs
MatterControlLib/CustomWidgets/NozzleOffsetTemplatePrinter.cs

- Issue MatterHackers/MCCentral#5148
End of xy calibration retracts T0

Revise GCodeSketch retraction processing

---

Program.cs

this is to allow launching of application when .net pipe is in use

Wrap Service Host in try catch 

---

MatterControlLib/PartPreviewWindow/View3D/SceneActions.cs
MatterControlLib/PartPreviewWindow/ViewControls3D.cs

issue: MatterHackers/MCCentral#3989
Consider excluding support from layflat

exclude support from lay flat consideration (if there is non-support)

---

MatterControlLib/PartPreviewWindow/RunningTaskRow.cs

- Issue MatterHackers/MCCentral#5180

Remove redundant progress bar on expanded progress widget

---

MatterControlLib/ActionBar/TemperatureWidgetBase.cs
MatterControlLib/ActionBar/TemperatureWidgetBed.cs
MatterControlLib/ActionBar/TemperatureWidgetExtruder.cs
MatterControlLib/ApplicationView/PrinterConfig.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs
Tests/MatterControl.AutomationTests/SliceSettingsTests.cs

- Issue MatterHackers/MCCentral#5176
Changing material selection turns on heaters

Move temp processing into PrinterConnection

---

MatterControl.Printing/Settings/SliceSettingsFields.cs
MatterControlLib/PartPreviewWindow/View3D/SceneActions.cs

issue: MatterHackers/MCCentral#5168
Arrange All Parts does not work with a single item on the bed

changing undo replace command to transform command

---

MatterControlLib/CustomWidgets/XyCalibrationCollectDataPage.cs
MatterControlLib/CustomWidgets/XyCalibrationDataRecieved.cs
MatterControlLib/CustomWidgets/XyCalibrationSelectPage.cs
MatterControlLib/CustomWidgets/XyCalibrationStartPrintPage.cs
MatterControlLib/DesignTools/Primitives/XyCalibrationFaceObject3D.cs
MatterControlLib/DesignTools/Primitives/XyCalibrationTabObject3D.cs

Changing to 7 points rather than 5
Added fix to not save if response page is canceled

Changing to offsets based on nozzle diameter

---

MatterControl.Printing/Settings/SettingsKey.cs
MatterControl.Printing/Settings/SliceSettingsFields.cs
MatterControlLib/ApplicationView/SettingsValidation.cs
MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/PrintLevelingWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/ProbeCalibrationWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/LastPageInstructions.cs
MatterControlLib/PrinterCommunication/Io/BabyStepsStream.cs
MatterControlLib/PrinterControls/ControlWidgets/MovementControls.cs
MatterControlLib/PrinterControls/JogControls.cs
Tests/MatterControl.Tests/MatterControl/GCodeStreamTests.cs

will calibrate extruder relative offsets separately

Made a global baby step for all extruders

---

MatterControlLib/PrinterControls/TerminalWindow/TerminalWidget.cs

issue: MatterHackers/MCCentral#5228
Re-order terminal filter menu

re-organized and improved language of terminal filters

---

MatterControlLib/PrinterCommunication/Io/ToolChangeStream.cs

issue: MatterHackers/MCCentral#5223
Temperature progressively drops during dual extrusion prints.

make sure we return to correct temp on tool change

---

MatterControlLib/DesignTools/EditorTools/DesignApps/Parts/Braille/BrailleContainer.cs
MatterControlLib/DesignTools/EditorTools/DesignApps/Parts/ChairFootObject3D.cs
MatterControlLib/DesignTools/EditorTools/DesignApps/Parts/ImageCoinObject3D.cs
MatterControlLib/DesignTools/EditorTools/DesignApps/Parts/PipeWorks/ElbowObject3D.cs
MatterControlLib/DesignTools/EditorTools/DesignApps/Parts/PipeWorks/PipeWorksBaseObject3D.cs
MatterControlLib/DesignTools/EditorTools/DesignApps/Parts/PipeWorks/PipeWorksContainer.cs
MatterControlLib/DesignTools/EditorTools/DesignApps/Parts/PipeWorks/TeeObject3D.cs
MatterControlLib/DesignTools/EditorTools/DesignApps/Parts/RibbonWithNameObject3D.cs
MatterControlLib/DesignTools/EditorTools/EditorToolsPlugin.cs
MatterControlLib/DesignTools/EditorTools/LithophanePlugin.cs
MatterControlLib/DesignTools/EditorTools/RotateControls/RotateCornerControl.cs
MatterControlLib/DesignTools/EditorTools/RotateControls/RotateInteractionPlugins.cs
MatterControlLib/DesignTools/EditorTools/ScaleControls/ScaleCornerControl.cs
MatterControlLib/DesignTools/EditorTools/ScaleControls/ScaleInteractionPlugins.cs
MatterControlLib/DesignTools/EditorTools/ScaleControls/ScaleTopControl.cs
MatterControlLib/Library/PartSheets/PartSheetPlugin.cs
MatterControlLib/Library/PartSheets/PartsSheetCreator.cs
MatterControlLib/MatterControlLib.csproj

moved part sheet creator into MatterControlLib
moved some other experimental parts to MatterControlLib
issue: MatterHackers/MatterControl#4388
Build from source: No Tools menu

Moved the primitives contain into MatterControlLib

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ApplicationView/PrinterConfig.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/CalibrateProbeLastPageInstructions.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/LastPageInstructions.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/SelectMaterialPage.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/WizardPage.cs
MatterControlLib/PrinterControls/ControlWidgets/CalibrationControls.cs
MatterControlLib/PrinterControls/ControlWidgets/IStagedSetupWizard.cs
MatterControlLib/PrinterControls/ControlWidgets/PrinterCalibrationWizard.cs
MatterControlLib/SetupWizard/DialogWindow.cs
MatterControlLib/SetupWizard/StagedSetupWindow.cs

- Issue MatterHackers/MCCentral#5235
Use staged wizard in place of old setup wizard hooks

Improve support for StagedSetupWizards

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ApplicationView/SettingsValidation.cs
MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/LoadFilamentWizard.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PrinterConnectButton.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs
MatterControlLib/PrinterControls/ControlWidgets/CalibrationControls.cs
MatterControlLib/PrinterControls/ControlWidgets/FilamentSetupWizard.cs
MatterControlLib/PrinterControls/ControlWidgets/TemperatureControls.cs
MatterControlLib/PrinterControls/ManualPrinterControls.cs

- Issue MatterHackers/MCCentral#3457
Setup Wizard does not show error if connection fails

 Extract and reuse printer connect behavior

---

MatterControlLib/PrinterControls/TerminalWindow/TerminalLog.cs

- Issue MatterHackers/MCCentral#5257
Overlapping messages in terminal

Convert newlines into separate TerminalLines

---

MatterControl.Printing/Settings/SettingsKey.cs
MatterControl.Printing/Settings/SliceSettingsFields.cs
MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/PrintLevelingWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/ProbeCalibrationWizard.cs
MatterControlLib/DesignTools/SupportGenerator.cs
MatterControlLib/SlicerConfiguration/EngineMappingMatterSlice.cs
StaticData/SliceSettings/Layouts.txt
Tests/MatterControl.Tests/MatterControl/SupportGeneratorTests.cs

issue: MatterHackers/MCCentral#5275
Dual extruder support fail

Improving support generation in dual extrusion scenarios

---

MatterControlLib/PartPreviewWindow/SceneViewer/FloorDrawable.cs
MatterControlLib/SetupWizard/StagedSetupWindow.cs
Tests/MatterControl.AutomationTests/HardwareLevelingUITests.cs
Tests/MatterControl.AutomationTests/PrintingTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

- Issue MatterHackers/MCCentral#5309

Fix automation tests

---

MatterControlLib/DesignTools/Operations/CurveObject3D_2.cs

started work on alternate ways to specify curve amount

Curve generates less geometry

---

MatterControlLib/Library/Widgets/ListView/LibraryListView.cs
MatterControlLib/Library/Widgets/PrintLibraryWidget.cs
MatterControlLib/PartPreviewWindow/ViewControls3D.cs

Fix MatterHackers/MCCentral#5357

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/DataStorage/ApplicationDataStorage.cs
MatterControlLib/Utilities/WebUtilities/WebCache.cs
MatterControlLib/VersionManagement/WebRequestHandler.cs

issue: MatterHackers/MCCentral#5361
Revise UndoBuffer tests

fix WebCache path

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ControlElements/StyledMessageBoxWindow.cs
MatterControlLib/CustomWidgets/XyCalibrationStartPrintPage.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs
MatterControlLib/SettingsManagement/UserSettings.cs

issue: MatterHackers/MCCentral#5339
Change to Dialog Print Completed implementation

move the print canceled and complete messages to a dialog

---

MatterControlLib/DesignTools/Operations/CurveObject3D_2.cs

issue: MatterHackers/MCCentral#5363
Cube moved after curve removed

fixed bend down and remove centering

---

MatterControlLib/DesignTools/Operations/CurveObject3D_2.cs

issue: MatterHackers/MCCentral#4950
Fix curve center when source item

Make the curve object editor in correct position

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ApplicationView/PartWorkspace.cs
MatterControlLib/PartPreviewWindow/MainViewWidget.cs
MatterControlLib/PartPreviewWindow/PartTabPage.cs
MatterControlLib/PartPreviewWindow/PrinterTabPage.cs
MatterControlLib/PartPreviewWindow/Tabs.cs
MatterControlLib/SettingsManagement/UserSettings.cs

- Issue MatterHackers/MCCentral#5375
Restore to previously active tab on startup

Restore to previously active tab on startup

---

MatterControl.Printing/Settings/SliceSettingsFields.cs
MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/UnloadFilamentWizard.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs

issue: MatterHackers/MCCentral#5338
Unload filament bug

fixing the unload bug

---

Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

issue: MatterHackers/MCCentral#5398
complete print turns off heat test needs to dismiss 'print complete' dialog

Fixing more tests

---

MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/ProbeCalibrationWizard.cs

- Issue MatterHackers/MCCentral#5380
Step 6 of 3

Update totalSteps to consider hotendCount

---

MatterControlLib/PartPreviewWindow/View3D/MeshViewerWidget.cs
MatterControlLib/PrinterCommunication/Drivers/Emulator/Emulator.cs

made it possible to turn the emulator speed to fast or slow in the terminal

improved emulator simulation view

---

MatterControlLib/PartPreviewWindow/View3D/MeshViewerWidget.cs

issue: MatterHackers/MCCentral#5460
Test failures on automation server caused by emulator null reference

fix problem with checking printer when null

---

MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/ProbePositionsWidget.cs

- Issue MatterHackers/MCCentral#5439
Leveling Summary view should size itself as expected

Revise scaling logic

---

MatterControlLib/PrinterCommunication/PrinterConnection.cs

issue: MatterHackers/MCCentral#5468
Hotend 1 controls move Hotend 2 instead

Make active extruder come from the tool change streams data

---

MatterControlLib/ConfigurationPage/PrintLeveling/ISetupWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/PrintLevelingWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/PrinterSetupWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/ProbeCalibrationWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/XyCalibrationWizard.cs
MatterControlLib/PrinterControls/ControlWidgets/WizardSummaryPage.cs
MatterControlLib/SetupWizard/DialogPage.cs
MatterControlLib/SetupWizard/DialogWindow.cs
MatterControlLib/SetupWizard/StagedSetupWindow.cs

- Issue MatterHackers/MCCentral#5478
Esc key in the PrinterSetupWizard exits the window without any warning

Ensure previous page is closed in ChangeToPage

---

MatterControl.Printing/GCode/GCodeMemoryFile.cs
MatterControlLib/PartPreviewWindow/PrinterTabPage.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs

Made the ratio complete be based on time

Showing the time to the end of the print

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ApplicationView/PrinterConfig.cs
MatterControlLib/ApplicationView/SettingsValidation.cs
MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/LoadFilamentWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/XyCalibrationWizard.cs
MatterControlLib/Library/Export/GCodeExport.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PrintPopupMenu.cs
MatterControlLib/PrinterControls/ControlWidgets/PrinterCalibrationWizard.cs
MatterControlLib/SlicerConfiguration/Slicer.cs
Tests/MatterControl.Tests/MatterControl.Tests.csproj

issue: MatterHackers/MCCentral#5497
Create protocol for single material setup on dual printer

Making T1 setup dependent on having T1 used in the print

---

MatterControlLib/DesignTools/GeneratedSupportObject3D.cs
MatterControlLib/DesignTools/SupportGenerator.cs
MatterControlLib/SlicerConfiguration/Slicer.cs

issue: MatterHackers/MCCentral#5532
Support becomes much larger after slicing

Fix issue with support generating too big

---

MatterControlLib/PrinterCommunication/Drivers/Emulator/Emulator.cs
MatterControlLib/PrinterCommunication/Drivers/Emulator/Heater.cs
Tests/MatterControl.Tests/MatterControl/ToolChangeTests.cs

put in correct extruder index
better time estimate for extrusions
refactoring

improving emulator state tracking

---

MatterControlLib/PrinterControls/ControlWidgets/CalibrationControls.cs

This was causing problems on Linux.

Fixed casing of icon file

---

MatterControlLib/SlicerConfiguration/MappingClasses/MapStartGCode.cs

issue: MatterHackers/MCCentral#5538
Doesn't wait for bed to reach temp before printing

Make sure we finish heating the bed before the start gcode

---

MatterControl.Printing/GCode/GCodeFile.cs
MatterControl.Printing/GCode/GCodeFileStreamed.cs
MatterControl.Printing/GCode/GCodeMemoryFile.cs
MatterControlLib/Library/Export/GCodeExport.cs
MatterControlLib/PartPreviewWindow/PrinterTabPage.cs
MatterControlLib/PrinterCommunication/Io/ToolChangeStream.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs
Tests/MatterControl.Tests/MatterControl/ToolChangeTests.cs

issue: MatterHackers/MCCentral#5550
Spiral Vase check box in Export dialog has no effect

Make sure we use the right settings when exporting

---

MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/WaitForTempPage.cs
MatterControlLib/Library/Widgets/AddPrinterWidget.cs
MatterControlLib/Library/Widgets/HardwarePage/HardwareTabPage.cs
MatterControlLib/Library/Widgets/HardwarePage/PrinterDetails.cs

- Issue MatterHackers/MatterControl#4543
Consider showing printer detail if available on create printer view

Reuse PrinterDetails widget on AddPrinter page

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/DesignTools/EditorTools/RotateControls/PathControl.cs

- Issue MatterHackers/MCCentral#5568
MC gets stuck on 'Reloading' screen.

Inform users of reload failure and remove overlay

---

MatterControlLib/DataStorage/ApplicationDataStorage.cs
MatterControlLib/Utilities/WebUtilities/WebCache.cs
MatterControlLib/VersionManagement/WebRequestHandler.cs

issue: MatterHackers/MCCentral#5579
Recent WebCache addition should use existing practices for location

using normal cache paths

---

MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/LoadFilamentWizard.cs
MatterControlLib/SlicerConfiguration/Slicer.cs

issue: MatterHackers/MCCentral#5601
Spiral vase should ignore material index

Only use 1 extruder when in spiral vase

---

MatterControlLib/SlicerConfiguration/Slicer.cs

issue: MatterHackers/MCCentral#5614
Spiral vase mode does not work with T1

make sure we can spiral vase on extruder T1

---

MatterControlLib/Utilities/MarkdigAgg/AggRenderer.cs
MatterControlLib/Utilities/MarkdigAgg/Inlines/AggCodeInlineRenderer.cs

Added formatting for inline code in markdown

---

MatterControlLib/ApplicationView/BrandMenuButton.cs

issue: MatterHackers/MCCentral#5630
Community links broken

updating support links

---

MatterControlLib/DesignTools/PublicPropertyEditor.cs
MatterControlLib/PartPreviewWindow/SelectedObjectPanel.cs

issue: MatterHackers/MCCentral#5703
Design Apps not unlockable

Make sure we can show unlock on component

---

MatterControlLib/AboutPage/UpdateControlData.cs
MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ConfigurationPage/ApplicationSettings/PluginsPage.cs
MatterControlLib/CustomWidgets/ExportPrintItemPage.cs
MatterControlLib/EeProm/EePromRepetierWindow.cs
MatterControlLib/PartPreviewWindow/LibraryBrowserPage.cs
MatterControlLib/PartPreviewWindow/MainViewWidget.cs
MatterControlLib/PartPreviewWindow/MarkdownEditPage.cs
MatterControlLib/PrinterControls/ControlWidgets/WizardSummaryPage.cs
MatterControlLib/PrinterControls/MovementSpeedsPage.cs
MatterControlLib/PrinterControls/PrinterConnections/SetupStepComPortManual.cs
MatterControlLib/RootSystemWindow.cs
MatterControlLib/SetupWizard/DialogWindow.cs
MatterControlLib/SetupWizard/InputBoxPage.cs
MatterControlLib/SetupWizard/Printer/OpenPrinterPage.cs
MatterControlLib/SetupWizard/StagedSetupWindow.cs
MatterControlLib/SetupWizard/TourPopover.cs
MatterControlLib/SetupWizard/WelcomePage.cs
MatterControlLib/SlicerConfiguration/UIFields/SurfacedEditorPage.cs

- Issue MatterHackers/MCCentral#5755
Cannot access disposed object exception during application exit
- Issue MatterHackers/MCCentral#5756
Cross-Thread operation not valid exception in CommunicationStateChanged
event handlers

Restore CloseOnIdle

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/PartPreviewWindow/PlatingHelper.cs
MatterControlLib/PartPreviewWindow/ViewControls3D.cs

issue: MatterHackers/MCCentral#5794
ArgumentOutOfRangeException

Fixed bug with arrange all when no items on bed

---

MatterControlLib/PartPreviewWindow/CreateDiscreteMeshes.cs

issue: MatterHackers/MCCentral#5800
Ungrouping certain models crashes MC

make sure we only add valid meshes while ungrouping

---

MatterControlLib/Library/Export/GCodeExport.cs

Export with spiral vase not working from print menu

issue : MatterHackers/MCCentral#5829

---

MatterControl.Printing/Settings/SliceSettingsFields.cs
MatterControlLib/ApplicationView/SettingsValidation.cs
StaticData/SliceSettings/Layouts.txt

if per layer support turned on don't warn about support

Make sure we show air gap speed

---

MatterControlLib/PartPreviewWindow/SelectedObjectPanel.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PrintPopupMenu.cs

Calculate HasTransparency correctly

Made print button disabled while printing

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/Library/Widgets/StorePage/UpgradeToProTabPage.cs
MatterControlLib/Utilities/WebUtilities/WebCache.cs

Fixes https://github.com/MatterHackers/MatterControl/issues/4783

Add default implementation to prevent crash due to null reference error

---

MatterControl.Printing/Settings/PrinterSettings.cs
MatterControl.Printing/Settings/SettingsKey.cs
MatterControl.Printing/Settings/SliceSettingsFields.cs
MatterControlLib/EeProm/EePromMarlinWindow.cs
MatterControlLib/EeProm/EePromRepetierWindow.cs
MatterControlLib/PrinterCommunication/Io/PauseHandlingStream.cs
StaticData/SliceSettings/Layouts.txt

Option to turn on run out sensor diagnostics

Make sure we dispose delegates correctly

---

MatterControlLib/CustomWidgets/SceneOperation.cs
MatterControlLib/PartPreviewWindow/GenerateSupportPanel.cs
MatterControlLib/PartPreviewWindow/ViewControls3D.cs
Tests/MatterControl.AutomationTests/MatterControlTests.cs

Made test for support button
Fixed tool bar drop saving

Fixed support button (put back in)

---

MatterControlLib/CustomWidgets/InlineStringEdit.cs
MatterControlLib/PrinterCommunication/Io/ValidatePrintLevelingStream.cs

issue: MatterHackers/MCCentral#6126
Add leveling feedback to printing dialog (like heating)

make validation have feedback

---

MatterControlLib/History/PrintHistoryEditor.cs

issue: MatterHackers/MCCentral#6148
Create canceled / failed options hierarchy

Made better history input

---

Community.CsharpSqlite/Community.CsharpSqlite.csproj
MatterControl.Common/MatterControl.Common.csproj
MatterControl.MeshOperations/MatterControl.MeshOperations.csproj
MatterControl.OpenGL/MatterControl.OpenGL.csproj
MatterControl.Printing/MatterControl.Printing.csproj
MatterControl.csproj
MatterControlLib/DesignTools/Primitives/WedgeObject3D.cs
MatterControlLib/MatterControlLib.csproj
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
MatterHackers.gsSlicer/MatterControl.gsSlicer.csproj
Tests/MatterControl.AutomationTests/MatterControl.AutomationTests.csproj
Tests/MatterControl.Tests/MatterControl.Tests.csproj

https://developercommunity.visualstudio.com/content/problem/1248649/error-netsdk1005-assets-file-projectassetsjson-doe.html

attempting to fix command line build

---

MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/ZCalibrationWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/ConductiveProbeFeedback.cs

Added error message when conductive probe moves too low

Added G4 P1 to conductive probe

---

MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/DesignTools/Attributes/VectorFieldLabelsAttribute.cs
MatterControlLib/DesignTools/Primitives/BaseObject3D.cs
MatterControlLib/DesignTools/PublicPropertyEditor.cs
MatterControlLib/PrinterCommunication/Drivers/Emulator/Emulator.cs
MatterControlLib/PrinterControls/TerminalWindow/TerminalLog.cs
MatterControlLib/PrinterControls/TerminalWindow/TerminalWidget.cs
MatterControlLib/PrinterControls/TerminalWindow/TextScrollWidget.cs
MatterControlLib/SlicerConfiguration/UIFields/Vector4Field.cs

issue: MatterHackers/MatterControl#4968
Printer Error Dialog Box, to include Export print log button

Add export button to error dialog

---

MatterControlLib/PartPreviewWindow/MainViewWidget.cs
MatterControlLib/PartPreviewWindow/SceneViewer/FloorDrawable.cs

Enable and disable move buttons

Don't draw texture when looking up from bed

---

MatterControlLib/PartPreviewWindow/SceneViewer/FloorDrawable.cs
MatterControlLib/PrinterCommunication/Io/GCodeSwitcher.cs

Fixing mesh blend error

---

MatterControlLib/PartPreviewWindow/View3D/TrackballTumbleWidgetExtended.cs
MatterControlLib/PartPreviewWindow/View3D/TumbleCubeControl.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs

Fixes #4970 
It works as requested if the mouse is over nothing it zooms to the center, otherwise it zooms exactly to the mouse cursor.
You can modify the zoom amount with `View3DWidget.ZoomDelta`. Only tested on windows.

Added zoom to mouse position

---

MatterControlLib/ApplicationView/SceneOperations.cs
MatterControlLib/DesignTools/Primitives/DescriptionObject3D.cs
MatterControlLib/DesignTools/Primitives/MeasureToolObject3D.cs
MatterControlLib/DesignTools/PublicPropertyEditor.cs
MatterControlLib/Library/Providers/GitHub/GitHubContainer.cs
MatterControlLib/PartPreviewWindow/View3D/SceneActions.cs

Fixed error with GitHub images
Improved multi line editor

Made description and measure tools work when grouped

---

MatterControlLib/DesignTools/Primitives/DescriptionObject3D.cs
MatterControlLib/DesignTools/Primitives/ImageObject3D.cs

issue: MatterHackers/MCCentral#6389
Opening the Bottle Opener with a fresh install fails

Making Design Apps require a login

---

MatterControl.MeshOperations/BooleanProcessing.cs
MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ApplicationView/Config/BedConfig.cs
MatterControlLib/CustomWidgets/XyCalibrationSelectPage.cs
MatterControlLib/DesignTools/Attributes/DisplayAsTime.cs
MatterControlLib/DesignTools/PublicPropertyEditor.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PrintPopupMenu.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
MatterControlLib/PrinterCommunication/PrinterConnection.cs
Tests/MatterControl.Tests/MatterControl/ToolChangeTests.cs

Making autopilot write to history

making autopilot report time better

---

MatterControlLib/DesignTools/Operations/ArrayLinearObject3D.cs
MatterControlLib/DesignTools/Sheets/SheetObject3D.cs

Fixing [index] for long running children

---

MatterControlLib/Library/Providers/FileSystem/FileSystemContainer.cs
MatterControlLib/PartPreviewWindow/MainViewWidget.cs
Program.cs

Save assets correctly

---

MatterControlLib/ApplicationView/EditContext.cs
MatterControlLib/Library/ContentProviders/MeshContentProvider.cs

They need to be available for cloud library and other library opperations

When loading from zip it is important that we cache the assets

---

MatterControlLib/ApplicationView/EditContext.cs
MatterControlLib/ApplicationView/SceneOperations.cs
MatterControlLib/DesignTools/Braille/BrailleCardObject3D.cs
MatterControlLib/DesignTools/Braille/BrailleObject3D.cs
MatterControlLib/DesignTools/Operations/AlignObject3D_2.cs
MatterControlLib/DesignTools/Operations/Object3DExtensions.cs
MatterControlLib/DesignTools/SupportGenerator.cs
MatterControlLib/PartPreviewWindow/SelectedObjectPanel.cs
MatterControlLib/PartPreviewWindow/View3D/SceneActions.cs
MatterControlLib/PartPreviewWindow/View3D/UndoCommands/DeleteCommand.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
StaticData/Translations/Master.txt
Tests/MatterControl.Tests/MatterControl/InteractiveSceneTests.cs

Started work on align object 2

Make sure we don't have selections on save

---

.gitignore
MatterControlLib/CustomWidgets/TreeView/TreeNode.cs
MatterControlLib/PartPreviewWindow/View3D/UndoCommands/InsertCommand.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
Tests/MatterControl.AutomationTests/PartPreviewTests.cs
Tests/MatterControl.Tests/MatterControl/MatterControlUtilities.cs

This goes with a matching pull request for agg-sharp.
Fixes #5188

Issue 5188

---

MatterControlLib/ApplicationView/Config/BedConfig.cs
MatterControlLib/ApplicationView/EditContext.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/AligningZAxisPageInstructions.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/ConductiveProbeFeedback.cs
MatterControlLib/Library/DynamicContentStore.cs
MatterControlLib/Library/Interfaces/IContentStore.cs
MatterControlLib/Library/Providers/FileSystem/FileSystemContainer.cs
MatterControlLib/Library/Providers/Sqlite/SqliteLibraryContainer.cs
MatterControlLib/Library/Providers/WritableContainer.cs
MatterControlLib/PartPreviewWindow/SelectedObjectPanel.cs

Wait for start of G34 before looking for 'ok'

Wait for Save to conclude before exiting

---

MatterControlLib/ConfigurationPage/PrintLeveling/LevelingFunctions.cs
MatterControlLib/Library/Export/GCodeExport.cs
MatterControlLib/PartPreviewWindow/View3D/TrackballTumbleWidgetExtended.cs
MatterControlLib/SlicerConfiguration/SliceSettingsRow.cs

Limit recalculating slice settings display

Improved leveling polygon selection

---

MatterControlLib/ApplicationView/Application.cs
MatterControlLib/ApplicationView/ApplicationController.cs
MatterControlLib/ApplicationView/SceneOperations.cs
MatterControlLib/CustomWidgets/SceneOperation.cs
MatterControlLib/DesignTools/Operations/GroupObject3D.cs
MatterControlLib/DesignTools/Primitives/OperationSourceContainerObject3D.cs
MatterControlLib/PartPreviewWindow/View3D/Object3DControlsLayer.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PrintPopupMenu.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
MatterControlLib/PartPreviewWindow/ViewToolBarControls.cs
MatterControlLib/SetupWizard/HelpTreePanel.cs
StaticData/Translations/Master.txt

updating ui hints

---

MatterControlLib/ConfigurationPage/PrintLeveling/SetupWizards/ZCalibrationWizard.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/ConductiveProbeFeedback.cs
MatterControlLib/ConfigurationPage/PrintLeveling/WizardPages/WizardPage.cs
MatterControlLib/PartPreviewWindow/View3D/Object3DControlsLayer.cs
MatterControlLib/PartPreviewWindow/View3D/TrackballTumbleWidgetExtended.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs
MatterControlLib/PrinterCommunication/Drivers/Emulator/Emulator.cs
StaticData/Translations/Master.txt

Added support for conductive probing to emulator
spend up rendering a bit (check less bounds)
Refactoring trackball a bit

Finishing up warning messages for conductive probing

---

MatterControlLib/PartPreviewWindow/PrinterTabPage.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/PrintPopupMenu.cs
MatterControlLib/PartPreviewWindow/View3D/PrinterBar/SliceButton.cs
MatterControlLib/PartPreviewWindow/View3D/View3DWidget.cs

Disable re-slice button on loaded g-code
